### ISSUE TITLE
[0.36.0.beta.2] Could not use google-plus-ios-sdk - Undefined symbols for architecture

### ISSUE THREAD

**Issue by darrarski** [CocoaPods/CocoaPods#3106]
After updating to Cocoapods 0.36 beta 2 I experienced following problems in my Swift project:

I am not able to import `google-plus-ios-sdk` the old way, in my bridging header file:

    #import <GooglePlus/GooglePlus.h> --> FILE NOT FOUND
    #import <GoogleOpenSource/GoogleOpenSource.h> --> FILE NOT FOUND

Which seems to be ok, as for other pods (having the same issue when imported in bridging header) I can simply import proper frameworks in my swift source code files. 
When trying to import Google frameworks in swift it works like expected:

    import google_plus_ios_sdk --> OK, no error here

...but it gives me an compilation error when trying to use any of Google's SDK class:

    Undefined symbols for architecture i386:
    "_OBJC_CLASS_$_GPPURLHandler", referenced from:
      __TMaCSo13GPPURLHandler in AppDelegate.o
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation) 

I am able to integrate most of my old, Obj-C pods without an issue, but this one is causing problems like described above. I have already cleaned up project, as well as removed all files stored in Xcode's DeliveredData directory but it didn't solve the problems.

Is there something I am doing wrong, or it's the problem inside the `google-plus-ios-sdk` pod? If so, are there any steps I could make to fix it?

**Comment by neonichu** [comment]
I don't know what the current state of the Facebook SDK is, but it used to be broken for building as a framework, see facebook/facebook-ios-sdk#688.

**Comment by darrarski** [comment]
My mistake. FacebookSDK is now working correctly with Cococapods 0.36.beta.2 after updating to version 3.22.0.

**Comment by neonichu** [comment]
The Google Plus SDK can indeed not be integrated at the moment when using frameworks.

Seems like integrating static vendored artifacts inside a framework actually doesn't work, because there is no way to re-export those symbols from the framework. I only see two solutions for this:

1) Mixing any static vendored artifacts and `source_files` is simply forbidden when using frameworks - we could check this and show some message to the user.
2) We have to actually revert our decision on mixing frameworks with static libraries and integrate such specs as a static library still.

@mrackwitz what's your opinion?

In this special case, there is actually no use in defining `source_files` as the google-plus-ios-sdk spec does and it can be fixed at the source by declaring `public_header_files` instead.

**Comment by neonichu** [comment]
This approach could be relevant: <http://lists.apple.com/archives/xcode-users/2014/Apr/msg00132.html> - however it does not work with the *GooglePlus.framework* for some reason.

**Comment by kylef** [comment]
There is a test project exhibiting this issue at https://github.com/lammertw/PodTests.

**Comment by neonichu** [comment]
Since we do not have a workable solution for this, let's change the logic for `should_build?` so that it doesn't matter if headers are defined via `public_headers` or `source_files`. This should allow things like the GooglePlus framework to work without changes, mitigating most of the problem.

**Comment by hectormatos2011** [comment]
So what is the actual solution to this? This still seems to be a problem with Cocoapods 0.36.3

**Comment by grizzly** [comment]
Any solutions so far?

**Comment by neonichu** [comment]
@grizzly this should work with 0.37 as far as we know. Do you see any issues?
