### ISSUE TITLE
undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by wangjoshuah** [CocoaPods/CocoaPods#5970]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.
> 
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
> 
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

`pod spec lint OptimizelySDKCore.podspec`
`pod install` with a project including OptimizelySDKCore
## What did you expect to happen?

Lints podspec and lets me know if there are any errors in the podspec.
## What happened instead?

Got this unknown error: - ERROR | [iOS] unknown: Encountered an unknown error (undefined method `strip' for nil:NilClass) during validation.
### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 44876cb2b966dadc62bd2fd75385b84a2075f35b
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
cocoapods_debug       : 0.1.0
```
## Project that demonstrates the issue

```
NoMethodError - undefined method `strip' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/config.rb:278:in `block in merge_attributes!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/config.rb:277:in `merge!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/config.rb:277:in `merge_attributes!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/config.rb:196:in `merge!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:63:in `block in generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:62:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:62:in `generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:35:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:205:in `create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:22:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:618:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by amorde** [comment]
Could you post the version of `OptimizelySDKCore.podspec` that you tested this with?

Most likely an Xcode config setting is being set to nil where it is expected to be a string

**Comment by benasher44** [comment]
Looks like there was a bad target dependency in one of your targets. This patch fixes it and allows pod install to continue.
```
diff --git a/IntuneFeatures.xcodeproj/project.pbxproj b/IntuneFeatures.xcodeproj/project.pbxproj
index aaf43fa..b6fa99e 100644
--- a/IntuneFeatures.xcodeproj/project.pbxproj
+++ b/IntuneFeatures.xcodeproj/project.pbxproj
@@ -821,10 +821,6 @@
                        target = 61BBC3B51C407891006C6DF0 /* IntuneFeatures.iOS */;
                        targetProxy = 61BBC3C11C407891006C6DF0 /* PBXContainerItemProxy */;
                };
-               A94555841CAED97E00E62839 /* PBXTargetDependency */ = {
-                       isa = PBXTargetDependency;
-                       name = PeakOSX;
-               };
 /* End PBXTargetDependency section */
 
 /* Begin XCBuildConfiguration section */
```
Going to keep this open, since this issue comes up every now and then, and we could have better error messaging here about where to go to look for this.

**Comment by benasher44** [comment]
@wangjoshuah is this still something you're experiencing with CocoaPods 1.1.1? If so, can you please post the podspec you were using with this, so that we can reproduce? Thanks!

**Comment by wangjoshuah** [comment]
Issue is with .xcconfig files. If I have comments in the .xcconfig files then Cocoapods will try and parse the comments

**Comment by benasher44** [comment]
@wangjoshuah thanks for the update! This seems like something relatively easy to fix. I'll tag this issue appropriately, and then this'll make a great starter ticket for someone to get started contributing.

**Comment by amorde** [comment]
I don't think this should have been closed
