### ISSUE TITLE
Pod spec lint fails after upgrading to 1.0 -fatal error: could not build module 'Foundation'

### ISSUE THREAD

**Issue by nicolasbraun** [CocoaPods/CocoaPods#5417]
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?
- Updated to Cocoapods 1.0
- Trying to `pod spec lint` one of my pods
## What did you expected to happen?
- Validate spec like it did with 0.39
## What happened instead?
- The spec validation fails.

```
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:436:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:438:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:439:44: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:441:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:442:54: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:444:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:444:50: error: declaration of 'Protocol' must be imported from module 'ObjectiveC.runtime' before it is required
    - NOTE  | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/objc/runtime.h:78:28: note: previous declaration is here
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:445:62: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:449:30: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:449:53: error: format argument not an NSString
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:450:31: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:450:63: error: format argument not an NSString
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/objc/module.map:8:10: error: module 'ObjectiveC.NSObject' requires feature 'objc'
    - NOTE  | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:9: note: submodule of top-level module 'ObjectiveC' implicitly imported here
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:8:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:18:64: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:19:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:11:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:17:1: error: expected identifier or '('
    - NOTE  | [iOS] xcodebuild:  fatal error: too many errors emitted, stopping now [-ferror-limit=]
    - NOTE  | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccelerometer.h:8:9: fatal error: could not build module 'Foundation'
    - NOTE  | [iOS] xcodebuild:  Target Support Files/libela/libela-umbrella.h:1:9: fatal error: could not build module 'UIKit'
```
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.2
Ruby lib dir : /Users/nicolas.braun/.rbenv/versions/2.3.1/lib
Repositories : applidium-cocoapodsspecs - git@scm.applidium.net:CocoaPodsSpecs.git @ a2f3f3e321e6625eff6f3b08badde4c5a38ac30e
               master - https://github.com/CocoaPods/Specs.git @ 29899a823ade046b65e9c537f5bc7f0bc569e112
               smartnsoft - https://github.com/smartnsoft/SmartCocoapods.git @ cf7384e32554b705b5eec4894ecf68c0d9654fd6
```
### Installation Source

```
Executable Path: /Users/nicolas.braun/.rbenv/versions/2.3.1/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
source 'git@scm.applidium.net:CocoaPodsSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'CPRequestManager', '~> 0.1.2', :inhibit_warnings => true
pod 'librudp', '~> 1.0', :inhibit_warnings => true
pod 'foils_hid', '~> 1.0', :inhibit_warnings => true
pod 'libela', '~> 1.0', :inhibit_warnings => true

target 'CPDecoder'
```
## Project that demonstrates the issue

This project is private but uses the dependecie libela which is just a pod wrapper around https://github.com/fbx/libela using this podspec

```
Pod::Spec.new do |spec|
  spec.name         = 'libela'
  spec.version      = '1.0.2'
  spec.authors      = 'AD'
  spec.license      = 'none'
  spec.homepage     = 'http://ad.com'
  spec.summary      = 'libela'
  spec.platform     = 'ios', '6.0'
  spec.source       = { :git => 'git@scm.mycompany.net:libela.git', :tag => "v#{spec.version}" }
  spec.source_files = 'include/**/*.{h,c}', 'src/ela.c', 'src/ela_cf.c'
  spec.framework    = 'Foundation'
  spec.requires_arc = true
end
```

This pod spec validates. 

This issue may be linked to #5409

**Comment by neonichu** [comment]
Hm, this sounds as if `xcodebuild` isn't being executed with the correct parameters internally. Could you please try running `pod spec lint —verbose` and share the xcodebuild command which fails? Please also share the output of `xcrun simctl list`.

**Comment by nicolasbraun** [comment]
Hello @neonichu 

Thanks for stepping in.

## Spec lint with Pod 1.0

```

The following build commands failed:
	CompileC /Users/nicolas.braun/Library/Developer/Xcode/DerivedData/App-ebjhnvnawqlrfdfdzeakpscuudmt/Build/Intermediates/Pods.build/Release-iphonesimulator/librudp.build/Objects-normal/i386/endpoint.o librudp/src/endpoint.c normal i386 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> CPDecoder (1.2.1)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:436:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:438:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:439:44: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:441:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:442:54: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:444:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:444:50: error: declaration of 'Protocol' must be imported from module 'ObjectiveC.runtime' before it is required
    - NOTE  | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/objc/runtime.h:78:28: note: previous declaration is here
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:445:62: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:449:30: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:449:53: error: format argument not an NSString
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:450:31: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:450:63: error: format argument not an NSString
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/objc/module.map:8:10: error: module 'ObjectiveC.NSObject' requires feature 'objc'
    - NOTE  | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:9: note: submodule of top-level module 'ObjectiveC' implicitly imported here
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:8:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:18:64: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:19:19: error: unknown type name 'NSString'
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:11:1: error: expected identifier or '('
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:17:1: error: expected identifier or '('
    - NOTE  | [iOS] xcodebuild:  fatal error: too many errors emitted, stopping now [-ferror-limit=]
    - NOTE  | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccelerometer.h:8:9: fatal error: could not build module 'Foundation'
    - NOTE  | [iOS] xcodebuild:  Target Support Files/libela/libela-umbrella.h:1:9: fatal error: could not build module 'UIKit'
    - NOTE  | [iOS] xcodebuild:  librudp/include/rudp/endpoint.h:31:10: fatal error: could not build module 'libela'
    - WARN  | [iOS] xcodebuild:  librudp/include/rudp/rudp_time.h:62:21: warning: implicit conversion loses integer precision: 'long long' to '__darwin_time_t' (aka 'long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  librudp/src/rudp.c:32:18: warning: implicit conversion loses integer precision: 'rudp_time_t' (aka 'long long') to 'unsigned int' [-Wshorten-64-to-32]

Analyzed 1 podspec.
[!] The spec did not pass validation, due to 20 errors.

```

## xcrun simctl list

```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
== Runtimes ==
iOS 9.3 (9.3 - 13E230) (com.apple.CoreSimulator.SimRuntime.iOS-9-3)
tvOS 9.1 (9.1 - 13U85) (com.apple.CoreSimulator.SimRuntime.tvOS-9-1)
tvOS 9.2 (9.2 - 13Y227) (com.apple.CoreSimulator.SimRuntime.tvOS-9-2)
watchOS 2.2 (2.2 - 13V143) (com.apple.CoreSimulator.SimRuntime.watchOS-2-2)
== Devices ==
-- iOS 9.3 --
    iPhone 4s (E872205D-B8F5-4317-B6F3-389B8ED85D21) (Shutdown)
    iPhone 5 (6BDCF83B-C56E-4147-8272-06D957E6CF23) (Shutdown)
    iPhone 5s (59B80025-B0D4-4713-B760-E5A30DC4767E) (Shutdown)
    iPhone 6 (5FA91228-3ACD-49FC-ADF4-BE03DFF7E998) (Shutdown)
    iPhone 6 Plus (CCEB5AFA-8A32-45F8-8057-E18B852B9385) (Shutdown)
    iPhone 6s (F96BCE19-F393-41D1-96F1-43943BB42CF7) (Shutdown)
    iPhone 6s Plus (82C6801E-5253-4639-BE44-DE2857900AC6) (Shutdown)
    iPad 2 (9DF998D2-DBB4-406F-9E7A-BAACBB0AF7C7) (Shutdown)
    iPad Retina (591E1FE1-2C5B-40EE-9187-5FFEF8605078) (Shutdown)
    iPad Air (799A4A2D-8B06-4F7C-A2EB-702A60AEBB18) (Shutdown)
    iPad Air 2 (707F1D2B-84F8-4CF4-9AB3-49F98787C149) (Shutdown)
    iPad Pro (D204B114-07DC-4284-A174-1A7EF708F0DA) (Shutdown)
-- tvOS 9.1 --
    Apple TV 1080p (57A7B47F-D43F-4409-AFC5-8680C2EA1E01) (Shutdown)
-- tvOS 9.2 --
    Apple TV 1080p (9D8B86A6-6570-4C49-AE01-D2A59B457A2A) (Shutdown)
-- watchOS 2.2 --
    Apple Watch - 38mm (BFC5AD5E-9BD5-4E5C-94BC-0E05C44613ED) (Shutdown)
    Apple Watch - 42mm (40C3621A-0664-4651-88A1-90194E05B2EB) (Shutdown)
== Device Pairs ==
A79222B0-D376-43CF-9F65-9773E789E918 (active, disconnected)
    Watch: Apple Watch - 38mm (BFC5AD5E-9BD5-4E5C-94BC-0E05C44613ED) (Shutdown)
    Phone: iPhone 6s (F96BCE19-F393-41D1-96F1-43943BB42CF7) (Shutdown)
FA33C5FF-939B-4066-B3B3-533CAC504DAB (active, disconnected)
    Watch: Apple Watch - 42mm (40C3621A-0664-4651-88A1-90194E05B2EB) (Shutdown)
    Phone: iPhone 6s Plus (82C6801E-5253-4639-BE44-DE2857900AC6) (Shutdown)```

**Comment by segiddins** [comment]
This might be fixed by https://github.com/CocoaPods/CocoaPods/pull/5408

**Comment by nicolasbraun** [comment]
I did not run into this issue lately. 
Will reopen if needed.

Thanks

Nicolas
