### ISSUE TITLE
Should error during install when there are duplicate library names

### ISSUE THREAD

**Issue by samurai00** [CocoaPods/CocoaPods#4014]
I am building an app which uses cocoapods to handle my external dependencies.
Cocoapods version 0.37.2 this works fine.
But I got error after I upgrade Cocoapods to 0.38.2.
Xcode version: 6.4
My Podfile:
```
platform :ios, "7.0"
pod "Pingpp", "~> 2.1.0"
pod "AFNetworking"
```
error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PingppInternal", referenced from:
      l_OBJC_$_CATEGORY_PingppInternal_$_Alipay in libpingpp+alipay.a(PingppInternal+Alipay.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Bfb in libpingpp+bfb.a(PingppInternal+Bfb.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Up in libpingpp+up.a(PingppInternal+Up.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Wx in libpingpp+wx.a(PingppInternal+Wx.o)
  "_OBJC_CLASS_$_PingppUtil", referenced from:
      objc-class-ref in libpingpp+alipay.a(PingppInternal+Alipay.o)
      objc-class-ref in libpingpp+bfb.a(PingppViewController.o)
      objc-class-ref in libpingpp+bfb.a(PingppInternal+Bfb.o)
      objc-class-ref in libpingpp+up.a(PingppInternal+Up.o)
      objc-class-ref in libpingpp+wx.a(PingppInternal+Wx.o)
  "_PingppLocalizedString", referenced from:
      -[PingppInternal(Alipay) alipayResult:] in libpingpp+alipay.a(PingppInternal+Alipay.o)
      -[PingppInternal(Bfb) channelBfb:withViewController:] in libpingpp+bfb.a(PingppInternal+Bfb.o)
      ___53-[PingppInternal(Bfb) channelBfb:withViewController:]_block_invoke103 in libpingpp+bfb.a(PingppInternal+Bfb.o)
      -[PingppInternal(Up) channelUpmp:withViewController:] in libpingpp+up.a(PingppInternal+Up.o)
      -[PingppInternal(Wx) onResp:] in libpingpp+wx.a(PingppInternal+Wx.o)
ld: symbol(s) not found for architecture arm64
```

And it works when using subspecs of [Pingpp](https://github.com/PingPlusPlus/pingpp-ios).
Podfile:
```
platform :ios, '7.0'
pod "Pingpp/Alipay", "~> 2.1.0"
pod "Pingpp/Wx", "~> 2.1.0"
pod "Pingpp/UnionPay", "~> 2.1.0"
pod "AFNetworking"
```

I'm not sure if the podspec file is correct.

**Comment by jasongrlicky** [comment]
I'm not sure if this is your issue, but I just ran into the same thing. It seems like deleting all of the schemes in Xcode and auto-creating them again "fixed" it for me. Obviously it would be great to understand why! :stuck_out_tongue:

**Comment by gregpassmore** [comment]
I just spent most of today on this issue. I went back to CocoaPods 0.37.2 and it worked. Didn't try the schemes thing.

**Comment by segiddins** [comment]
I think this might be fixed in 0.39.0.beta.3?

**Comment by samurai00** [comment]
@segiddins I tried 0.39.0.beta.4. Still not work. 😢

**Comment by vatrif** [comment]
I have a similar issue with Flurry (6.7) and 0.39.0 beta 4. Pure Swift app, iOS 8, Xcode 7 beta 6.

**Comment by vatrif** [comment]
Official Flurry-iOS-SDK 7.1 pod fixed my build issues.

**Comment by samurai00** [comment]
I found this subspec caused this problem

**Comment by samurai00** [comment]
I found this subspec caused the error.
```
  s.subspec 'Bfb' do |bfb|
    bfb.frameworks = 'CoreTelephony', 'AddressBook', 'AddressBookUI', 'AudioToolbox', 'CoreAudio', 'CoreGraphics', 'ImageIO', 'MapKit', 'MessageUI', 'MobileCoreServices', 'QuartzCore'
    bfb.source_files = 'lib/Channels/Bfb/Dependencies/**/*.{h,m}'
    bfb.public_header_files = 'lib/Channels/Bfb/Dependencies/**/*.h'
    bfb.resource = 'lib/Channels/Bfb/*.bundle'
    bfb.vendored_libraries = 'lib/Channels/Bfb/**/*.a'
    bfb.dependency 'Pingpp/Core'
  end
```
It include both `source_files` and `vendored_libraries`.
If I delete the `bfb.source_files` line and complies the source files manually, the error disappears.

**Comment by samurai00** [comment]
I know what caused the problem now.
My spec name is `Pingpp`. It will produce `libPingpp.a`.
And I have a static library file named `libpingpp.a`.
So the two files conflicted. Only the `libPingpp.a` was imported and built.

**Comment by segiddins** [comment]
@samurai00 good catch! We definitely need to error out during `pod install` if there a duplicate library names.

**Comment by segiddins** [comment]
Something like the following is a good start:

```diff
diff --git a/lib/cocoapods/installer.rb b/lib/cocoapods/installer.rb
index 8e7b930..dd161b2 100644
--- a/lib/cocoapods/installer.rb
+++ b/lib/cocoapods/installer.rb
@@ -105,6 +105,7 @@ module Pod
       resolve_dependencies
       download_dependencies
       determine_dependency_product_types
+      verify_no_duplicate_library_names
       verify_no_duplicate_framework_names
       verify_no_static_framework_transitive_dependencies
       verify_framework_usage
@@ -394,7 +395,7 @@ module Pod
       aggregate_targets.each do |aggregate_target|
         aggregate_target.user_build_configurations.keys.each do |config|
           pod_targets = aggregate_target.pod_targets_for_build_configuration(config)
-          vendored_frameworks = pod_targets.flat_map(&:file_accessors).flat_map(&:vendored_frameworks)
+          vendored_frameworks = pod_targets.flat_map(&:file_accessors).flat_map(&:vendored_frameworks).uniq
           frameworks = vendored_frameworks.map { |fw| fw.basename('.framework') }
           frameworks += pod_targets.select { |pt| pt.should_build? && pt.requires_frameworks? }.map(&:product_module_name)
 
@@ -407,6 +408,22 @@ module Pod
       end
     end
 
+    def verify_no_duplicate_library_names
+      aggregate_targets.each do |aggregate_target|
+        aggregate_target.user_build_configurations.keys.each do |config|
+          pod_targets = aggregate_target.pod_targets_for_build_configuration(config)
+          libraries = pod_targets.flat_map(&:file_accessors).flat_map(&:vendored_libraries).uniq.map(&:basename)
+          libraries += pod_targets.select { |pt| pt.should_build? && !pt.requires_frameworks? }.map(&:product_name)
+
+          duplicates = p(libraries).group_by { |l| l.to_s.downcase }.select { |_, v| v.size > 1 }.keys
+          unless duplicates.empty?
+            raise Informative, "The '#{aggregate_target.label}' target has " \
+              "libraries with conflicting names: #{duplicates.to_sentence}."
+          end
+        end
+      end
+    end
+
     def verify_no_static_framework_transitive_dependencies
       aggregate_targets.each do |aggregate_target|
         next unless aggregate_target.requires_frameworks?
diff --git a/spec/unit/installer_spec.rb b/spec/unit/installer_spec.rb
index ab97595..23decf9 100644
--- a/spec/unit/installer_spec.rb
+++ b/spec/unit/installer_spec.rb
@@ -52,6 +52,7 @@ module Pod
         @installer.stubs(:resolve_dependencies)
         @installer.stubs(:download_dependencies)
         @installer.stubs(:determine_dependency_product_types)
+        @installer.stubs(:verify_no_duplicate_library_names)
         @installer.stubs(:verify_no_duplicate_framework_names)
         @installer.stubs(:verify_no_static_framework_transitive_dependencies)
         @installer.stubs(:verify_framework_usage)
@@ -223,6 +224,27 @@ module Pod
 
     #-------------------------------------------------------------------------#
 
+    describe '#verify_no_duplicate_library_names' do
+      it 'detects duplicate library names' do
+        Sandbox::FileAccessor.any_instance.stubs(:vendored_libraries).returns([Pathname('/libMonkey.a')])
+        fixture_path = ROOT + 'spec/fixtures'
+        config.repos_dir = fixture_path + 'spec-repos'
+        podfile = Pod::Podfile.new do
+          platform :ios, '8.0'
+          xcodeproj 'SampleProject/SampleProject'
+          pod 'BananaLib',       :path => (fixture_path + 'banana-lib').to_s
+          pod 'monkey',          :path => (fixture_path + 'monkey').to_s
+        end
+        lockfile = generate_lockfile
+        config.integrate_targets = false
+
+        @installer = Installer.new(config.sandbox, podfile, lockfile)
+        should.raise(Informative) { @installer.install! }.message.should.match /conflict.*monkey/
+      end
+    end
+
+    #-------------------------------------------------------------------------#
+
     describe '#verify_no_static_framework_transitive_dependencies' do
       before do
         fixture_path = ROOT + 'spec/fixtures'
```
