### ISSUE TITLE
Pod with ResearchKit as dependency fails to build with linker error

### ISSUE THREAD

**Issue by apbendi** [CocoaPods/CocoaPods#5304]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Attempted to add [ResearchKit](https://github.com/ResearchKit/ResearchKit) as a dependency to a pod created with `pod lib create` and CocoaPods 1.0.0

## What did you expected to happen?

The pod to include ResearchKit and build the example target properly.

## What happened instead?

The example target fails to build with the following error: `ld: 252 duplicate symbols for architecture x86_64`

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a4621b9995a1ca718cccdb60baa1a999b09b27aa
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

https://github.com/apbendi/ORKPodFailure

** P.S. Thanks for all the hard work and congrats on CocoaPods 1.0 🎉  **

**Comment by neonichu** [comment]
Seems to me as if `ORKScrollToTopAnimationDuration` and `ORKCGFloatInvalidValue` should be declared `extern` in the `ORKHelpers.h` header?

**Comment by apbendi** [comment]
@neonichu interesting, that seems to be true. I'll try a fork to see if that resolves the issue. Curious- why did this manifest in 1.0.0 when it worked fine in 0.39 (which, I know from my actual project, it did)?

**Comment by neonichu** [comment]
No idea, tbh. I suppose their own Xcode project also compiles, but I don't know why :)

**Comment by apbendi** [comment]
@neonichu well, fixing the header docs resolved the problem, anyway. Will open a pull request with RK shortly. Am I right in thinking the RK team will have to push a new version to CocoaPods before this can be resolved without pointing to git in your Podfile?

**Comment by apbendi** [comment]
For reference, here is the PR submitted to ResearchKit: https://github.com/ResearchKit/ResearchKit/pull/680

**Comment by segiddins** [comment]
@apbendi yup, that assumption is correct

**Comment by apbendi** [comment]
thanks for confirming @segiddins. Hopefully the RK folks won't be opposed to getting a new release out there or we'll be answering support requests nonstop! 😬
