### ISSUE TITLE
Xcode 8: Project with private cocoapods fails to build.

### ISSUE THREAD

**Issue by AtharvaVaidya** [CocoaPods/CocoaPods#5904]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Cloned the project to a new folder. Tried to build project in Xcode 8, note, this project uses private cocoapods as wells as works perfectly in Xcode 7.3.1.

## What did you expect to happen?

Expected pods to install correctly and be able to build/run the project (Project working in Xcode 7.3.1).

## What happened instead?

The app generated 2 errors: 

- error: include of non-modular header inside framework module 'CloudMine.CMWebService' below is the log.
```
While building module 'CloudMine' imported from /Users/atharvavaidya/Developer/DeveloperApp400-master/Pods/BMUtilities/BMUtilities/Classes/BMExperimentData.h:9:
In file included from <module-includes>:1:
In file included from /Users/atharvavaidya/Developer/DeveloperApp400-master/Pods/Target Support Files/CloudMine/CloudMine-umbrella.h:3:
In file included from /Users/atharvavaidya/Developer/DeveloperApp400-master/Pods/CloudMine/ios/ios/src/CloudMine.h:66:
/Users/atharvavaidya/Developer/DeveloperApp400-master/Pods/CloudMine/ios/ios/src/Web Services/CMWebService.h:18:9: error: include of non-modular header inside framework module 'CloudMine.CMWebService' [-Werror,-Wnon-modular-include-in-framework-module]
#import <AFNetworking/AFNetworking.h>
        ^
1 error generated. 
```

- Was unable to build module below is the log. 
```
In file included from /Users/atharvavaidya/Developer/DeveloperApp400-master/Pods/BMUtilities/BMUtilities/Classes/BMExperimentData.m:9:
/Users/atharvavaidya/Developer/DeveloperApp400-master/Pods/BMUtilities/BMUtilities/Classes/BMExperimentData.h:9:9: fatal error: could not build module 'CloudMine'
@import CloudMine;
 ~~~~~~~^~~~~~~~~
2 errors generated.
```

## CocoaPods Environment

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : biomeme - https://github.com/Biomeme/DeveloperApp400.git @ 219e3633d07a3dda1525567a418ef17e9d3bd46c
               master - https://github.com/Biomeme/DeveloperApp400.git @ 219e3633d07a3dda1525567a418ef17e9d3bd46c
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/Biomeme/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'DeveloperApp400' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'BMUtilities' #=> '1.0.21'
  pod 'BMCameraStack' #=> '1.0.5'
  pod 'BMLightningConnectorStack' #=> '1.0.1'
  pod 'BMAlgorithm' #=> '1.0.1'
  pod 'BMThermoCycler' #=> '1.0.2'
  pod 'CocoaLumberjack'
  pod 'Canvas'
  pod 'BugfenderSDK', '~> 0.3'
  # Pods for DeveloperApp400

end
```

## Project that demonstrates the issue

The project is proprietary we cannot provide it. However, clearly this is an issue relating solely to using cocapods in Xcode 8, as this project works perfectly in Xcode 7.3.1

**Comment by maksutovic** [comment]
+1 having the *exact* same issue.

**Comment by ztaylor** [comment]
+1

**Comment by okcomp** [comment]
+1

**Comment by neonichu** [comment]
Hard to say if this is an issue with CP or if the Pod simply needs an update to work correctly with Xcode 8. Can you try to recreate the issue without your private Pods somehow?

**Comment by benasher44** [comment]
@AtharvaVaidya you'll need to use at least CocoaPods 1.1.0.rc.2, since this contains many Xcode 8 fixes. You can get this version by specifying it in your Gemfile or installing it at the system level via `gem install cocoapods --pre`. Once you do this, you can verify it's been installed successfully by running `pod --version`.

**Comment by AtharvaVaidya** [comment]
Issue seems fixed with the latest version(1.1.0rc2).
