### ISSUE TITLE
Pod install broken due to pre_integrate

### ISSUE THREAD

**Issue by Brett-Best** [CocoaPods/CocoaPods#10367]
[x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

_I wasn’t sure whether to report this given I’m using CP from master._

# Report

## What did you do?

Run `pod install` using cocoa pods @ https://github.com/CocoaPods/CocoaPods/commit/7a910c51fa07116bfd9a6da82b676e2d8e18b176

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

The command fails, I suspect due to https://github.com/CocoaPods/CocoaPods/pull/9935

```
Comparing resolved specification to the sandbox manifest
  A nanopb

Downloading dependencies

-> Installing nanopb (2.30907.0)
  > Copying nanopb from `/Users/brettbest/Library/Caches/CocoaPods/Pods/Release/nanopb/2.30907.0-59221` to `Pods/nanopb`
  - Running pre install hooks
  - Running pre integrate hooks
[!] An error occurred while processing the pre-integrate hook of the Podfile.

undefined method `pre_integrate!' for #<Pod::Podfile:0x00007fc9e8555028>
Did you mean?  post_integrate!
               post_integrate

/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/installer.rb:915:in `run_podfile_pre_integrate_hook'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/installer.rb:903:in `block in run_podfile_pre_integrate_hooks'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/user_interface.rb:145:in `message'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/installer.rb:902:in `run_podfile_pre_integrate_hooks'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/installer.rb:179:in `integrate'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/installer.rb:167:in `install!'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/command/update.rb:63:in `run'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/lib/cocoapods/command.rb:52:in `run'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-7a910c51fa07/bin/pod:55:in `<top (required)>'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/pod:23:in `<top (required)>'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:494:in `exec'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/exe/bundle:49:in `block in <top (required)>'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/exe/bundle:37:in `<top (required)>'
/Users/brettbest/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
/Users/brettbest/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
    RubyGems : 3.2.5
        Host : macOS 11.2 (20D5042d)
       Xcode : 12.3 (12C33)
         Git : git version 2.30.0
Ruby lib dir : /Users/brettbest/.rbenv/versions/2.7.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/brettbest/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.1'

inhibit_all_warnings!

target 'medCompanion iOS' do
  use_frameworks!
  
  pod 'nanopb'

  target 'medCompanion iOS Tests' do
    inherit! :search_paths
  end

  target 'medCompanion iOS UI Tests' do
    
  end

end
```

**Comment by dnkoutso** [comment]
Did you also update cocoapods-core gem?

**Comment by dnkoutso** [comment]
This feature is not released yet.
