### ISSUE TITLE
Pod fail to compile with CocoaPods v1.0  - headers not found -  but compiles fine with v0.39

### ISSUE THREAD

**Issue by Iftahh** [CocoaPods/CocoaPods#5337]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

I'm trying to use libFLAC - it works fine with CocoaPods 0.39  but has a compile error (missing header file) with CocoaPods 1.0
## What did you do?

I started a completely new iOS project, and wrote Podfile to install libFLAC - and ran "pod install" once with version 0.39 and repeated the process once with version 1.0
## What happened instead?

The resulting xcworkspace compiled fine only when the 0.39 was used.
The 1.0 xcworkspace failed to compile with missing header files (included by the libFLAC source itself)
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.6.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : evature - https://github.com/evature/Eva-Pods.git @ 85f6ea763410c056ed778ee050594a76191aab68
               flac-ios - https://github.com/evature/flac-ios.git @ aba567fc6d0731ee3c793506fbad790f3aa47381
               master - https://github.com/CocoaPods/Specs.git @ e72d9d59f8a9a8bfab446eef7623ba1d6d2a00aa
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/evature/Eva-Pods.git'

platform :ios, '8.0'

use_frameworks!

target "testFlac" do
    pod 'libFLAC', '~>1.3.0'
end
```
## Project that demonstrates the issue

example project:  https://github.com/Iftahh/testFlac

the libFLAC podspec is at  https://github.com/evature/flac-ios/blob/master/libFLAC.podspec
## $ xcodeproj project-diff

$ xcodeproj project-diff good_v039/Pods.xcodeproj/ bad_v100/Pods.xcodeproj/

```

---
rootObject:
  attributes:
    LastSwiftUpdateCheck:
      good_v039/Pods.xcodeproj/: '0700'
      bad_v100/Pods.xcodeproj/: '0730'
  buildConfigurationList:
    buildConfigurations:
      Debug:
        buildSettings:
          GCC_PREPROCESSOR_DEFINITIONS:
            bad_v100/Pods.xcodeproj/:
            - POD_CONFIGURATION_DEBUG=1
          ENABLE_TESTABILITY:
            good_v039/Pods.xcodeproj/: 
            bad_v100/Pods.xcodeproj/: 'YES'
          CLANG_ANALYZER_NONNULL:
            good_v039/Pods.xcodeproj/: 
            bad_v100/Pods.xcodeproj/: 'YES'
      Release:
        buildSettings:
          GCC_PREPROCESSOR_DEFINITIONS:
            good_v039/Pods.xcodeproj/:
            - RELEASE=1
            bad_v100/Pods.xcodeproj/:
            - POD_CONFIGURATION_RELEASE=1
            - $(inherited)
          CLANG_ANALYZER_NONNULL:
            good_v039/Pods.xcodeproj/: 
            bad_v100/Pods.xcodeproj/: 'YES'
  mainGroup:
    children:
      Podfile:
        lastKnownFileType:
          good_v039/Pods.xcodeproj/: text
          bad_v100/Pods.xcodeproj/: 
        explicitFileType:
          good_v039/Pods.xcodeproj/: 
          bad_v100/Pods.xcodeproj/: text.script.ruby
      Frameworks:
        children:
          iOS:
            children:
              Foundation.framework:
                path:
                  good_v039/Pods.xcodeproj/: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/Foundation.framework
                  bad_v100/Pods.xcodeproj/: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework
      Pods:
        children:
          libFLAC:
            name:
              good_v039/Pods.xcodeproj/: libFLAC
              bad_v100/Pods.xcodeproj/: 
            children:
              Base:
                children:
                  bitmath.c:
                    lastKnownFileType:
                      good_v039/Pods.xcodeproj/: 
                      bad_v100/Pods.xcodeproj/: sourcecode.c.c
          ... many more files - trimmed for brevity ...
                  window.c:
                    lastKnownFileType:
                      good_v039/Pods.xcodeproj/: 
                      bad_v100/Pods.xcodeproj/: sourcecode.c.c
              Support Files:
                children:
                  libFLAC.modulemap:
                    lastKnownFileType:
                      good_v039/Pods.xcodeproj/: 
                      bad_v100/Pods.xcodeproj/: sourcecode.module-map
      Products:
        children:
          FLAC.framework:
            name:
              good_v039/Pods.xcodeproj/: FLAC.framework
              bad_v100/Pods.xcodeproj/: 
          Pods_testFlac.framework:
            name:
              good_v039/Pods.xcodeproj/: Pods_testFlac.framework
              bad_v100/Pods.xcodeproj/: 
      Targets Support Files:
        children:
          Pods-testFlac:
            children:
              Pods-testFlac.modulemap:
                lastKnownFileType:
                  good_v039/Pods.xcodeproj/: 
                  bad_v100/Pods.xcodeproj/: sourcecode.module-map
  productRefGroup:
    children:
      FLAC.framework:
        name:
          good_v039/Pods.xcodeproj/: FLAC.framework
          bad_v100/Pods.xcodeproj/: 
      Pods_testFlac.framework:
        name:
          good_v039/Pods.xcodeproj/: Pods_testFlac.framework
          bad_v100/Pods.xcodeproj/: 
  targets:
    libFLAC:
      productReference:
        name:
          good_v039/Pods.xcodeproj/: FLAC.framework
          bad_v100/Pods.xcodeproj/: 
      buildConfigurationList:
        buildConfigurations:
          Debug:
            buildSettings:
              LD_RUNPATH_SEARCH_PATHS:
                good_v039/Pods.xcodeproj/:
                - $(inherited)
                - '@executable_path/Frameworks'
                - '@loader_path/Frameworks'
                bad_v100/Pods.xcodeproj/: $(inherited) @executable_path/Frameworks
                  @loader_path/Frameworks
              GCC_NO_COMMON_BLOCKS:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: 'YES'
              DEBUG_INFORMATION_FORMAT:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: dwarf
          Release:
            buildSettings:
              LD_RUNPATH_SEARCH_PATHS:
                good_v039/Pods.xcodeproj/:
                - $(inherited)
                - '@executable_path/Frameworks'
                - '@loader_path/Frameworks'
                bad_v100/Pods.xcodeproj/: $(inherited) @executable_path/Frameworks
                  @loader_path/Frameworks
              GCC_NO_COMMON_BLOCKS:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: 'YES'
              DEBUG_INFORMATION_FORMAT:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: dwarf-with-dsym
      buildPhases:
        SourcesBuildPhase:
          files:
            bitmath.c:
              fileRef:
                lastKnownFileType:
                  good_v039/Pods.xcodeproj/: 
                  bad_v100/Pods.xcodeproj/: sourcecode.c.c
            bitreader.c:
              fileRef:
                lastKnownFileType:
                  good_v039/Pods.xcodeproj/: 
                  bad_v100/Pods.xcodeproj/: sourcecode.c.c
            ... many more files - trimmed for brevity ...
            window.c:
              fileRef:
                lastKnownFileType:
                  good_v039/Pods.xcodeproj/: 
                  bad_v100/Pods.xcodeproj/: sourcecode.c.c
        FrameworksBuildPhase:
          files:
            Foundation.framework:
              fileRef:
                path:
                  good_v039/Pods.xcodeproj/: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/Foundation.framework
                  bad_v100/Pods.xcodeproj/: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework
    Pods-testFlac:
      productReference:
        name:
          good_v039/Pods.xcodeproj/: Pods_testFlac.framework
          bad_v100/Pods.xcodeproj/: 
      buildConfigurationList:
        buildConfigurations:
          Debug:
            buildSettings:
              LD_RUNPATH_SEARCH_PATHS:
                good_v039/Pods.xcodeproj/:
                - $(inherited)
                - '@executable_path/Frameworks'
                - '@loader_path/Frameworks'
                bad_v100/Pods.xcodeproj/: $(inherited) @executable_path/Frameworks
                  @loader_path/Frameworks
              PRODUCT_BUNDLE_IDENTIFIER:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
              GCC_NO_COMMON_BLOCKS:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: 'YES'
              DEBUG_INFORMATION_FORMAT:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: dwarf
          Release:
            buildSettings:
              LD_RUNPATH_SEARCH_PATHS:
                good_v039/Pods.xcodeproj/:
                - $(inherited)
                - '@executable_path/Frameworks'
                - '@loader_path/Frameworks'
                bad_v100/Pods.xcodeproj/: $(inherited) @executable_path/Frameworks
                  @loader_path/Frameworks
              PRODUCT_BUNDLE_IDENTIFIER:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
              GCC_NO_COMMON_BLOCKS:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: 'YES'
              DEBUG_INFORMATION_FORMAT:
                good_v039/Pods.xcodeproj/: 
                bad_v100/Pods.xcodeproj/: dwarf-with-dsym
      buildPhases:
        FrameworksBuildPhase:
          files:
            Foundation.framework:
              fileRef:
                path:
                  good_v039/Pods.xcodeproj/: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/Foundation.framework
                  bad_v100/Pods.xcodeproj/: Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework
```

**Comment by Coeur** [comment]
Hello @Iftahh, and thank you for providing a sample project.

    /Users/me/Development/Eva-Pods/libFLAC/1.3.1
    $ pod spec lint
    
     -> libFLAC (1.3.1)
        - WARN  | compiler_flags: Warnings must not be disabled(`-Wno compiler` flags).
        - ERROR | [libFLAC/Base] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
        - NOTE  | [libFLAC/Base] xcodebuild:  libFLAC/flac/src/libFLAC/bitmath.c:37:10: fatal error: 'private/bitmath.h' file not found
        - NOTE  | [libFLAC/Base] xcodebuild:  libFLAC/flac/src/libFLAC/cpu.c:37:10: fatal error: 'private/cpu.h' file not found
    
    Analyzed 1 podspec.
    
    [!] The spec did not pass validation, due to 1 error and 1 warning.

**Comment by Coeur** [comment]
Someone recently added some header paths: https://github.com/evature/flac-ios/commit/be06de363928c17020415237049dc63085c6d8a7

But there is still this error:

        - ERROR | [libFLAC/Base] xcodebuild:  /Users/me/Library/Developer/Xcode/DerivedData/App-drsencmoqhmxfvgsvszghveecdot/Build/Products/Release-iphonesimulator/libFLAC/FLAC.framework/Modules/module.modulemap:2:19: error: umbrella header 'libFLAC-umbrella.h' not found

**Comment by Iftahh** [comment]
Yea, a colleague of mine is trying to find a work-around, he made those changes and for him it works now.
But I'm facing the same headers not found errors...

**Comment by Coeur** [comment]
Try to edit the .modulemap and set this line:

    umbrella header "flac/include/FLAC/all.h"

**Comment by Coeur** [comment]
I've tried it and it works, so I made a PR: https://github.com/evature/flac-ios/pull/3

**Comment by Iftahh** [comment]
thanks!

**Comment by Iftahh** [comment]
Still the spec doesn't validate for me -

the verbose error  (trimmed)
```
/Users/iftah/Library/Developer/Xcode/DerivedData/App-beqtekkynztnljaqeihdasscnlkd/Build/Products/Release-iphonesimulator/libFLAC/FLAC.framework/Modules/module.modulemap:2:19: error: umbrella header 'flac/include/FLAC/all.h' not found
  umbrella header "flac/include/FLAC/all.h"
                  ^
1 error generated.
/var/folders/xr/p5lbb6dj5r9_gd34md99w8sh0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'FLAC'
@import FLAC;
 ~~~~~~~^~~~
2 errors generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/iftah/Library/Developer/Xcode/DerivedData/App-beqtekkynztnljaqeihdasscnlkd/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/main.o App/main.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/iftah/Library/Developer/Xcode/DerivedData/App-beqtekkynztnljaqeihdasscnlkd/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/main.o App/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
 -> libFLAC (1.3.2)
    - WARN  | compiler_flags: Warnings must not be disabled(`-Wno compiler` flags).
    - ERROR | [libFLAC/Base] xcodebuild: Returned an unsuccessful exit code.
    - WARN  | [libFLAC/Base] xcodebuild:  libFLAC/flac/src/libFLAC/stream_encoder.c:4006:72: warning: loop will run at most once (loop increment never executed) [-Wunreachable-code-loop-increment]
    - ERROR | [libFLAC/Base] xcodebuild:  /Users/iftah/Library/Developer/Xcode/DerivedData/App-beqtekkynztnljaqeihdasscnlkd/Build/Products/Release-iphonesimulator/libFLAC/FLAC.framework/Modules/module.modulemap:2:19: error: umbrella header 'flac/include/FLAC/all.h' not found
    - NOTE  | [libFLAC/Base] xcodebuild:  /var/folders/xr/p5lbb6dj5r9_gd34md99w8sh0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'FLAC'

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors and 2 warnings.
```

**Comment by Coeur** [comment]
`pod update` on https://github.com/Iftahh/testFlac does work for me.

`pod spec lint` fails because I think we can remove the line `s.module_map = "libFLAC.modulemap"` entirely from the podspec.

    libFLAC.podspec passed validation.

**Comment by Iftahh** [comment]
Thanks again for your help - I really appreciate it.

The update worked because I added the 1.3.2 podspec manually... without passing lint.  Now the test project compiles fine - hurray!

After merging I still get lint error, but of a different kind - 
```
libFLAC (1.3.3)
    - WARN  | compiler_flags: Warnings must not be disabled(`-Wno compiler` flags).
    - ERROR | [libFLAC/Base] xcodebuild: Returned an unsuccessful exit code.
    - ERROR | [libFLAC/Base] xcodebuild:  libFLAC/flac/src/libFLAC/cpu.c:39:10: error: use of private header from outside its module: 'memory.h' [-Wprivate-header]
```

**Comment by Iftahh** [comment]
err - sorry my bad - the pod spec validated fine with CocoaPods 1.0!

it failed with 0.39   (I forgot I switched versions a few minutes ago)

**Comment by Coeur** [comment]
Good. So, you can close the issue :)

**Comment by Iftahh** [comment]
Unfortunately - I'm still having issues that do not happen in CocoaPods 0.39 -  

I'm concerned they may have started because of the USER_HEADER_SEARCH_PATHS override,
so I'm not sure if I should close this issue or maybe the solution found above isn't final.  

The real project I'm working on - https://github.com/evature/ios -  now has a warning when I run "pod install" -  
```
The `EvaKit [Release]` target overrides the `USER_HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-EvaKit/Pods-EvaKit.release.xcconfig'. This can lead to problems with the CocoaPods installation
```

I tried contacting Yegor who provided the USER_HEADER patch, but he is unavailable now and I'm not sure how to work around it.

And (not surprisingly) there are indeed errors - the libFLAC compiles fine but it fails to find another pod `#import <RXPromise/RXPromise.h>`  fails

**Comment by segiddins** [comment]
You'll need to stop overriding the build setting, as the warning says.

**Comment by Coeur** [comment]
@segiddins, I think they did the override because otherwise `#include "private/bitmath.h"` wasn't working in libflac.

**Comment by segiddins** [comment]
@Coeur we can't really support people who override the build settings, hence the warnings when they're not `$(inherit)`ed

**Comment by Iftahh** [comment]
but when I remove the override of the USER_HEADER_SEARCH_PATHS then the podspec fail to validate with different headers not found

**Comment by Coeur** [comment]
Maybe, to fix `#include "private/bitmath.h"`, you can try:

    ph.header_mappings_dir = 'flac/src/libFLAC/include', 'flac/src/libFLAC/include/private'

**Comment by Iftahh** [comment]
nope,  CocoaPods expects a single string for header_mappings_dir -
this is the lint error:

- ERROR | [iOS] attributes: Unacceptable type `Array` for `header_mappings_dir`. Allowed values: `[String]`.

**Comment by Hmachalani** [comment]
@Iftahh did you resolve your issue? I'm running into the same issue with a similar upgrade path and podspec.
