### ISSUE TITLE
NoMethodError - undefined method `skip_import_validation=' when trying to trunk push a podspec

### ISSUE THREAD

**Issue by mentzen** [CocoaPods/CocoaPods#6697]
### Command

```
/usr/local/bin/pod trunk push openEars1.podspec
```

### Report

* What did you do?

tried to push the podspec to CocoaPods

* What did you expect to happen?

CocoaPods registers my podspec

* What happened instead?

An Error Occured

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ecfbfbd3fce400567f3fe9ba608b9797c330b0a3
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `skip_import_validation=' for #<Pod::Validator:0x007f9b06c8e558>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.2.0/lib/pod/command/trunk/push.rb:121:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.2.0/lib/pod/command/trunk/push.rb:66:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by AndriyGo** [comment]
+1

Am also seeing this issue

**Comment by orta** [comment]
Can you try it on 1.2.1?

**Comment by mentzen** [comment]
Well... i didn't expect something to change with the new version but apparently it works on 1.2.1.

**Comment by AndriyGo** [comment]
Yep works for me too!

**Comment by helinyu** [comment]
my pod version is 1.1.1 ,and I see this issue , should i change it to 1.2.1 version?

**Comment by dtartaglia** [comment]
FYI. I saw this issue on 1.2.0. I updated to 1.2.1 and it worked.
