### PR TITLE
Include dependent vendored frameworks in linker flags

### PR DESCRIPTION
**Pull request by drcapulet**
Accompanying PR to CocoaPods/cocoapods-integration-specs#242.

### CODE REVIEW

**Comment by dnkoutso** [comment]
I'd like @segiddins to review this since he made the change in https://github.com/CocoaPods/CocoaPods/pull/8314

**Comment by amorde** [comment]
+1 on @dnkoutso's comment, we had a bunch of regressions when changing this so would like to be 100% sure we get this right

**Comment by drcapulet** [comment]
Of course! Based on some cursory glancing, it should fix #8519.

**Comment by dnkoutso** [comment]
Does it break https://github.com/CocoaPods/CocoaPods/issues/8204 which is what #8314 fixed?

**Comment by drcapulet** [comment]
No, I don't think so - that was specifically related to libraries instead of frameworks. This only targets frameworks that wouldn't otherwise be compiled since those will get included in the "Link Binary With Libraries" phase, but I'm definitely no expert on all this stuff.

File: .gitmodules [hunk 1]
```diff
@@ -6,7 +6,7 @@
 	url = https://github.com/tonymillion/Reachability.git
 [submodule "spec/cocoapods-integration-specs"]
 	path = spec/cocoapods-integration-specs
-	url = https://github.com/CocoaPods/cocoapods-integration-specs.git
```
Comment (segiddins) [inline .gitmodules]: will need to point back to master

File: lib/cocoapods/target/build_settings.rb [hunk 2]
```diff
@@ -558,9 +558,8 @@ def initialize(target, non_library_spec = nil)
           if library_xcconfig? && (target.should_build? && target.build_as_dynamic?)
             frameworks.concat vendored_static_frameworks.map { |l| File.basename(l, '.framework') }
           end
-          if non_library_xcconfig?
-            frameworks.concat dependent_targets_to_link.flat_map { |pt| pt.build_settings.frameworks_to_import }
-          end
+          targets_to_link = library_xcconfig? ? dependent_targets.reject(&:should_build?) : dependent_targets_to_link
```
Comment (segiddins) [inline lib/cocoapods/target/build_settings.rb]: for unbbuilt dependent targets, should we only be linking dynamic frameworks here, instead of dynamic and static?

Comment (drcapulet) [reply lib/cocoapods/target/build_settings.rb]: Yes, updated.

**Comment by dnkoutso** [comment]
@drcapulet needs a rebase to fix CHANGELOG conflict.

**Comment by dnkoutso** [comment]
Also would need to rebase off of `1-8-stable` and point to that branch instead to have this change released for 1.8.0.beta.2.

File: lib/cocoapods/target/build_settings.rb [hunk 3]
```diff
@@ -559,12 +559,16 @@ def initialize(target, non_library_spec = nil)
...
           frameworks = []
           frameworks.concat consumer_frameworks
-          if library_xcconfig? && (target.should_build? && target.build_as_dynamic?)
-            frameworks.concat vendored_static_frameworks.map { |l| File.basename(l, '.framework') }
-          end
-          if non_library_xcconfig?
+          if library_xcconfig?
+            # We know that this library target is being built dynamically based
+            # on the guard above, so include any vendored static frameworks.
+            frameworks.concat vendored_static_frameworks.map { |l| File.basename(l, '.framework') } if target.should_build?
```
Comment (dnkoutso) [inline lib/cocoapods/target/build_settings.rb]: does this mean that a vendored static framework will be linked _twice_? Once for this dynamic framework and once on the app target itself?

Comment (drcapulet) [reply lib/cocoapods/target/build_settings.rb]: This line is just moved around, but no - since this is a dynamic library target, when it gets compiled it needs to include any vendored static frameworks, and then the whole dynamic library will get linked into it's parent (either app or another library).

Comment (dnkoutso) [reply lib/cocoapods/target/build_settings.rb]: If I recall correctly CocoaPods will link that vendored static framework to the app target as well not just the dynamic library target.

From its early days CocoaPods had a very (kinda annoying) naive approach to just link everything to the app level target.

Comment (dnkoutso) [reply lib/cocoapods/target/build_settings.rb]: I can verify my own question this week.

Comment (dnkoutso) [reply lib/cocoapods/target/build_settings.rb]: I guess you are right this was already happening before. I will still verify though

**Comment by dnkoutso** [comment]
@drcapulet needs a rebase. I will try to land it for a beta.2.

File: .gitmodules (hunk 1 above)
Comment (dnkoutso) [reply .gitmodules]: yes @drcapulet will need to revert this

**Comment by dnkoutso** [comment]
@drcapulet can you rebase to fix the `CHANGELOG` conflict and we can merge?

**Comment by ryang1428** [comment]
Still having issues installing vendors frameworks in 1.8.0 :/

**Comment by ryang1428** [comment]
@dnkoutso should I open a new issue? I am still having issues installing vendored frameworks via 1.8.1.. Getting the same compile time errors:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CardIO", referenced from:
      objc-class-ref in AppCoordinator.o
      objc-class-ref in VoiceController.o
      objc-class-ref in CheckController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by icecrystal23** [comment]
I think this may be causing us to have duplicate symbol errors, as most of our vendored frameworks are static and therefore we do NOT want them included in linker flags outside the project vendoring them.  

I will investigate and create an issue (and maybe a PR to fix) if I can repro for you.
