### ISSUE TITLE
Duplicate Symbols in Static Library Test after updating to 0.36.3

### ISSUE THREAD

**Issue by Buju77** [CocoaPods/CocoaPods#3413]
Hi,

I just updated my Cocoapods from 0.33.1 to 0.36.3. Yes I know its very old, but we knew there some breaking changes and we didn't have time to make the transition.

But now after executing pod update with 0.36.3 we are getting duplicate symbol in our unit test target. 

#### Project Setup
Here is the following setup (I picked a very simple private library from us to see what changes we need to make for the new Cocoapods version):

##### Podfile:

    # /usr/bin/ruby
    platform :ios, '6.0'
    inhibit_all_warnings!
    pod 'CocoaLumberjack', '~> 1.8.0'

##### Xcode (2 targets):
* JackWrapper (static library), 
* JackWrapperTests (XCTest) [1]
  * has **target dependency** on JackWrapper
  * is linking with libJackWraper.a
  * has only 1 source file (SimpleTest.m)
  * is based on `Pods.debug.xcconfig` config file (was using `Pods.xcconfig` in 0.33.1) (changed that manually so it is possible to compile and has access to Lumberjack)

When building the unit test target we are getting duplicate symbols because CocoaLumberjack is linked into JackWrapper and JackWrapperTests now.

After some digging I found out why its not building anymore after just updating Cocoapods to 0.36.x. The reason was in the config file.

##### `Pods.xcconfig` (0.33.1) looked like this

	GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
	HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers" "${PODS_ROOT}/Headers/CocoaLumberjack"
	OTHER_CFLAGS = $(inherited) "-isystem${PODS_ROOT}/Headers" "-isystem${PODS_ROOT}/Headers/CocoaLumberjack"
	OTHER_LDFLAGS = -ObjC
	PODS_ROOT = ${SRCROOT}/Pods

##### `Pods.debug.xcconfig` (0.36.3)

	GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
	HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/CocoaLumberjack"
	OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/CocoaLumberjack"
	OTHER_LDFLAGS = $(inherited) -ObjC -l"Pods-CocoaLumberjack"
	OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)
	PODS_ROOT = ${SRCROOT}/Pods

The line that is causing the the build to fail is because its also linking `Pods-CocoaLumberjack` into the unit test target --> `OTHER_LDFLAGS = $(inherited) -ObjC -l"Pods-CocoaLumberjack"`

Why was it necessary to add the linker flag to the config file in 0.36.3 and not in 0.33.1 which worked perfectly fine for unit test target?

#### Solution Proposal for Unit Test Targets
I have seen similar issues posted here and couldn't find a good fix for this problem (maybe I missed it?). Of course there are many proposed solutions but I'm proposing yet another solution [2]:

* add another line to Podfile (so Cocoapods will do everything for us): `link_with 'JackWrapper', 'JackWrapperTests'`
* while Cocoapods is installing pods into the targets, it should check if the target is an unit test target and has a target dependency on another target which is also in the list of `link_with`
  * If yes, create a new config file: `Pods.Tests.debug.xcconfig`
  * derive from `Pods.debug.xcconfig` and 
  * override `OTHER_LDFLAGS` so it doesn't link to any pods which is already linked by the static library (JackWrapper)
  * and set this new config file to the unit test target [2]

##### Example: `Pods.Tests.debug.xcconfig`

	#include "Pods.debug.xcconfig"          # derive from it

	OTHER_LDFLAGS = $(inherited) -ObjC      # this overrides the value from Pods.debug

By simply doing that, our unit test target builds and executes the tests successfully again. If there any other proper workaround for this issue I can apply?

[1] Unit Test Build Phases
![screen shot 2015-04-16 at 18 13 11](https://cloud.githubusercontent.com/assets/266349/7185668/66beadc6-e464-11e4-8519-6f3f965497af.png)
[2] Target Configurations
![screen shot 2015-04-16 at 18 12 53](https://cloud.githubusercontent.com/assets/266349/7185672/6f15dcd8-e464-11e4-9ecc-26ad7b4015da.png)

**Comment by jshier** [comment]
What version of Xcode are you using? My encounters with this issue stopped once my project was able to move to Xcode 6.

**Comment by Buju77** [comment]
I'm using Xcode Version 6.3 (6D570)

**Comment by neonichu** [comment]
It should be possible to limit linkage of your pod by putting it into a `target` block, see <https://guides.cocoapods.org/syntax/podfile.html#group_dependencies>

**Comment by Buju77** [comment]
@neonichu this doesn't really help, because it does the same as my Podfile described above.

    platform :ios, '6.0'
    inhibit_all_warnings!
    target :JackWrapper do
        pod 'CocoaLumberjack', '~> 1.8.0'
    end

The problem is that the unit test target can't find any lumberjack header files because header search path is not setup in unit test target (does not have a config set).

**Comment by neonichu** [comment]
The workaround for that is just adding some testing dependency to your test target. The problem will eventually be solved by the new Podfile DSL: CocoaPods/Core#81

**Comment by Buju77** [comment]
ok, this workaround is a little bit better than changing xcode project settings directly.

	platform :ios, '6.0'
	inhibit_all_warnings!

	target :JackWrapper do
	    pod 'CocoaLumberjack', '~> 1.8.0'
	end

	target :JackWrapperTests do
	    pod 'MyDummyLib', '~> 0.0.1'	# workaround
	end


is there any ETA for new Podfile DSL when we can except it?

**Comment by neonichu** [comment]
Nope, but it'll happen before 1.0 - see also CocoaPods/CocoaPods#840

**Comment by Buju77** [comment]
ok thanks for info
