### ISSUE TITLE
Cocopods 1.15.0, Error!!

### ISSUE THREAD

**Issue by Q-Time** [CocoaPods/CocoaPods#12225]
qinshijian@Bililiooos-MBP ArtiFusion % pod install
Analyzing dependencies
Downloading dependencies
Installing Ads-Global (5.4.0.9)
Installing Alamofire (5.8.1)
Installing AppLovinSDK (11.11.3)
Installing AppsFlyer-AdRevenue (6.9.1)
Installing AppsFlyerFramework (6.12.2)
Installing BURelyFoundation_Global (0.1.2.5)

[!] Error installing BURelyFoundation_Global

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.0
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
    RubyGems : 3.5.5
        Host : macOS 14.2.1 (23C71)
       Xcode : 15.2 (15C500b)
         Git : git version 2.43.0
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.0/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 90091ffd6f769d2e706ed6b16190fb2424aa354a

               trunk - CDN - https://cdn.cocoapods.org/
               yolo-specs-ios - git - git@gitlab.com:yolonet/yolo-specs-ios.git @ 50252981b65cfeda0938a2567a34fe7fbd54e52f

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
source 'git@gitlab.com:yolonet/yolo-specs-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

project 'ArtiFusion.xcodeproj' #指定让Pod命令编译的project

target 'ArtiFusion' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    pod 'KeychainAccess'
    pod 'MBProgressHUD'
    pod 'IQKeyboardManagerSwift'
    pod 'Reachability'
    pod 'SnapKit', '~> 5.0.0'
    pod 'Moya', '~> 15.0.0'
    pod 'lottie-ios', '~> 4.3.4'
    #图片加载框架
    pod 'SDWebImage', '~> 5.17.0'
    pod 'SDWebImageWebPCoder', '~> 0.13.0'
  #  pod 'SDWebImageHEIFCoder', '~> 0.10.1'
  # 刷新
    pod 'MJRefresh', '~> 3.7.5'

#    pod 'Masonry'
#    pod 'MJRefresh'
#    pod 'Toast'
#    pod 'SDWebImage', '~> 4.3.3'
#    #pod 'UMengAnalytics-NO-IDFA'
#    pod 'IQKeyboardManager'
    
    
  #图片选择器浏览
    pod 'Lantern'
  #防止截屏视图
    pod 'RyukieSwifty/ScreenShield'
    #图片转码
  #  pod 'libwebp', '~> 1.2.4'
  #  pod 'JPImageresizerView'
  #  pod 'JPCrop'
  #标签相关
    pod "ESTabBarController-swift"
    pod 'JXSegmentedView'
    pod 'JXPagingView/Paging'
    pod 'TagListView'
    pod 'FSPagerView'
  
#  pod 'MJExtension'
#  pod 'AFNetworking'
#  pod 'MBProgressHUD', '~> 1.1.0'
#  pod 'Bugly'
#  pod 'UITableView+FDTemplateLayoutCell'
#  pod 'GTMBase64'
#  pod 'FMDB', '~> 2.5'
  
  
    #工具扩展
    pod 'SwifterSwift', '~> 5.2.0' #Swift编程语言的扩展库

    # 私有库
    pod 'YLADCommon', '3.0.45'
    #  pod 'YLADCommon', :path => '/Users/qinshijian/Desktop/桌面文件/YoloWork/YoloAppGit/ads_common'
    pod 'IAPComponent', '1.6.1'
    #  pod 'IAPComponent', :path => '/Users/qinshijian/Desktop/桌面文件/YoloWork/YoloAppGit/IAPComponent'
    pod 'NetworkComponent', '2.0.1.41'
    #pod 'NetworkComponent', :path => '/Users/qinshijian/Desktop/桌面文件/YoloWork/YoloAppGit/yolo_networkcommon'

#    pod 'FLAnimatedImage', '~> 1.0'
#    pod 'UMengUShareModule' ,'~>0.1.2'
#    pod 'WeChat_SDK', '~> 1.7.5.1'
#    pod 'SVProgressHUD', '~> 2.2.5'
#    pod 'HcdGuideView'
#    pod 'BMKLocationKit', '~> 1.5.0'
#    pod 'BaiduMapKit', '~> 4.3.2'
#    pod 'JXCategoryView', '~> 1.3.7'
#    #pod 'JXPagingView/Pager', '~> 1.1.5'
#
#    pod 'GTSDK'
#    pod 'CYLTabBarController', '~> 1.17.4'
#    pod 'JSBadgeView'
#    pod 'lottie-ios', '~> 2.5.3'
    
    # 通知
    pod 'FirebaseMessaging'
    pod 'PurchaseConnector' #Appsflayer的订阅内购收入统计分析

    #业务层广告聚合
    #  pod 'GoogleMobileAdsMediationIronSource', '7.4.0.0' #对应谷歌sdk是10.9.0
    pod 'GoogleMobileAdsMediationAppLovin', '11.11.3.0'
    pod 'GoogleMobileAdsMediationMintegral', '7.4.3.0'

    # 调试工具
    pod 'LookinServer', '1.2.5' , :configurations => ['Debug']
    
    pod 'WCDB.swift'
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 arm64"
        end
      end
    end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
      end
    end
end
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/qinshijian/Library/Caches/CocoaPods/Pods/Release/BURelyFoundation_Global/0.1.2.5-cd9e0/Frameworks/SDK/BURelyFoundationGlobalFoundation/BURelyFoundationGlobalFoundation.xcframework/ios-arm64_armv7/Headers/NSArray+PAGUtilities.h
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2279:in `initialize'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2279:in `open'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2279:in `block in copy_file'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2278:in `open'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2278:in `copy_file'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2243:in `copy'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:1048:in `block in copy_entry'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2385:in `wrap_traverse'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:1045:in `copy_entry'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:990:in `block in cp_r'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2469:in `block in fu_each_src_dest'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2478:in `block in fu_each_src_dest0'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2476:in `each'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2476:in `fu_each_src_dest0'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2467:in `fu_each_src_dest'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:989:in `cp_r'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:343:in `block (2 levels) in copy_files'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `each'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `block in copy_files'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:128:in `lock'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:332:in `copy_files'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:269:in `block (2 levels) in uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `each'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `block in uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:291:in `in_tmpdir'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:42:in `download'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `each'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:257:in `download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:163:in `install!'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/gems/cocoapods-1.15.0/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.15.0/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fqinshijian%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FRelease%2FBURelyFoundation_Global%2F0.1.2.5-cd9e0%2FFrameworks%2FSDK%2FBURelyFoundationGlobalFoundation%2FBURelyFoundationGlobalFoundation.xcframework%2Fios-arm64_armv7%2FHeaders%2FNSArray%2BPAGUtilities.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil

why?

**Comment by maxim-narchuk-cleverside** [comment]
I have exactly the same problem after updating cocoapods

**Comment by Q-Time** [comment]
I hope to update 1.15.1 soon. I urgently need it to solve the problem that occurred in Xcode Cloud. Thank you for your hard work. I have no problem using ‘’sudo pod install --allow-root‘’ on Mac, but the use of ‘’sudo‘’ is prohibited in Xcode Cloud.

**Comment by Q-Time** [comment]
I installed Cocopods on Mac with the specified version 1.14.2 and there was no problem:
"sudo gem install cocoapods -v 1.14.2"
However, sudo is prohibited on Xcode Cloud. “gem install cocoapods -v 1.14.2” does not work on Xcode Cloud because there is no permission, or brew install cocoapods@1.14.2 also does not work.

**Comment by maxim-narchuk-cleverside** [comment]
If you have a Gemfile and CI is running fastlane (call the "bundle update" and "bundle install" command before starting the build processes), you can specify a version like, 

`gem 'cocoapods', '1.14.3'`


I installed cocoapods 1.14.3 on my system (macbook pro m1 max) after upgrading to 1.15.0, like this:

`sudo gem uninstall cocoapods`
`curl https://raw.githubusercontent.com/Homebrew/homebrew-core/30d5aab0ebd9e1b8f03c69e25a4ae95f9875eead/Formula/c/cocoapods.rb > cocoapods.rb`
`brew install cocoapods.rb`

or

`brew remove cocoapods`
`curl https://raw.githubusercontent.com/Homebrew/homebrew-core/30d5aab0ebd9e1b8f03c69e25a4ae95f9875eead/Formula/c/cocoapods.rb > cocoapods.rb`
`brew install cocoapods.rb`

P.S. this solution for arm64 mac (m1,m2,m3 etc.)
you can read more about downgrading [here](https://nelson.cloud/how-to-install-older-versions-of-homebrew-packages/)

**Comment by maxim-narchuk-cleverside** [comment]
> I installed Cocopods on Mac with the specified version 1.14.2 and there was no problem: "sudo gem install cocoapods -v 1.14.2" However, sudo is prohibited on Xcode Cloud. “gem install cocoapods -v 1.14.2” does not work on Xcode Cloud because there is no permission, or brew install cocoapods@1.14.2 also does not work.

I think, you can use this [article](https://medium.com/@nyagolovm/how-to-configure-bundler-and-cocoapods-for-xcode-cloud-a-comprehensive-guide-6136732d8eaa) and my solution to switch Xcod-Cloud on 1.14.3 cocoapods

**Comment by Sateesh7070** [comment]
### Command

```
/Users/kodecorp/.rbenv/versions/3.2.2/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.15.0
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
    RubyGems : 3.4.18
        Host : macOS 14.2.1 (23C71)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/kodecorp/.rbenv/versions/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'lifesongs' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'lifesongsTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

### Error

```
Errno::EEXIST - File exists @ syserr_fail2_in - /Users/kodecorp/Library/Caches/CocoaPods/Pods/External/hermes-engine/dbb153605ad16ff6beffe23b95032e38-54205/destroot/Library/Frameworks/macosx/hermes.framework/Resources
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2266:in `symlink'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2266:in `copy'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:1058:in `block in copy_entry'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2397:in `wrap_traverse'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2400:in `block in wrap_traverse'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2399:in `each'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2399:in `wrap_traverse'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:1055:in `copy_entry'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:1000:in `block in cp_r'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2481:in `block in fu_each_src_dest'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2490:in `block in fu_each_src_dest0'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2488:in `each'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2488:in `fu_each_src_dest0'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:2479:in `fu_each_src_dest'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/3.2.0/fileutils.rb:999:in `cp_r'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:343:in `block (2 levels) in copy_files'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `each'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `block in copy_files'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:128:in `lock'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:332:in `copy_files'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:269:in `block (2 levels) in uncached_pod'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `each'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `block in uncached_pod'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:291:in `in_tmpdir'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:42:in `download'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `each'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:257:in `download_dependencies'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:163:in `install!'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in `run'
/Users/kodecorp/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.15.0/bin/pod:55:in `<top (required)>'
/Users/kodecorp/.rbenv/versions/3.2.2/bin/pod:25:in `load'
/Users/kodecorp/.rbenv/versions/3.2.2/bin/pod:25:in `<main>'
```

**Comment by HieuGameDev** [comment]
> If you have a Gemfile and CI is running fastlane (call the "bundle update" and "bundle install" command before starting the build processes), you can specify a version like,
> 
> `gem 'cocoapods', '1.14.3'`
> 
> I installed cocoapods 1.14.3 on my system (macbook pro m1 max) after upgrading to 1.15.0, like this:
> 
> `sudo gem uninstall cocoapods` `curl https://raw.githubusercontent.com/Homebrew/homebrew-core/30d5aab0ebd9e1b8f03c69e25a4ae95f9875eead/Formula/c/cocoapods.rb > cocoapods.rb` `brew install cocoapods.rb`
> 
> or
> 
> `brew remove cocoapods` `curl https://raw.githubusercontent.com/Homebrew/homebrew-core/30d5aab0ebd9e1b8f03c69e25a4ae95f9875eead/Formula/c/cocoapods.rb > cocoapods.rb` `brew install cocoapods.rb`
> 
> P.S. this solution for arm64 mac (m1,m2,m3 etc.) you can read more about downgrading [here](https://nelson.cloud/how-to-install-older-versions-of-homebrew-packages/)

I love you
