### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by osamaazmat** [CocoaPods/CocoaPods#11134]
# Report

I am facing an issue where I cannot use 'pod deintegrate' and when I try any other pod command these warnings show up.

Error loading the plugin `cocoapods-deintegrate-1.0.5`
Error loading the plugin `cocoapods-plugins-1.0.0`
Error loading the plugin `cocoapods-search-1.0.1`
Error loading the plugin `cocoapods-trunk-1.6.0`.

Details are given below under pod env.

## What did you do?

I have removed cocoapods
I have updated Ruby Version 
Updated Gems
Installed Cocoapods 

Again I tried the same above process after installing rbenv aswell.

## What did you expect to happen?

I expected pod deintegrate to work

## What happened instead?

[SAME Error "loading the plugin" ERROR GIVEN BELOW]

[!] Unknown command: `deintegrate`
Did you mean: update?

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache        Manipulate the CocoaPods cache
    + env          Display pod environment
    + init         Generate a Podfile for the current directory
    + install      Install project dependencies according to versions from a
                   Podfile.lock
    + ipc          Inter-process communication
    + lib          Develop pods
    + list         List pods
    + outdated     Show outdated project dependencies
    + repo         Manage spec-repositories
    + setup        Setup the CocoaPods environment
    + spec         Manage pod specs
    + update       Update outdated project dependencies and create new Podfile.lock

Options:

    --allow-root   Allows CocoaPods to run as root
    --silent       Show nothing
    --version      Show the version of the tool
    --verbose      Show more debugging information
    --no-ansi      Show output without ANSI codes
    --help         Show help banner of specified command

## CocoaPods Environment

pod env | pbcopy

---------------------------------------------
Error loading the plugin `cocoapods-deintegrate-1.0.5`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x000000010d0e0048 @extension_dir=nil, @full_gem_path="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-deintegrate-1.0.5", @gem_dir=nil, @ignored=nil, @loaded_from="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/specifications/cocoapods-deintegrate-1.0.5.gemspec", @data=#<Gem::StubSpecification::StubLine:0x000000010cf4b660 @name="cocoapods-deintegrate", @version=#<Gem::Version "1.0.5">, @platform="ruby", @extensions=[], @full_name="cocoapods-deintegrate-1.0.5", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0", @gems_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems", @default_gem=false>

        spec.activate
            ^^^^^^^^^
Did you mean?  activated?
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `load'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `<main>'
---------------------------------------------

---------------------------------------------
Error loading the plugin `cocoapods-plugins-1.0.0`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x000000010cf6bfc8 @extension_dir=nil, @full_gem_path="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-plugins-1.0.0", @gem_dir=nil, @ignored=nil, @loaded_from="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/specifications/cocoapods-plugins-1.0.0.gemspec", @data=#<Gem::StubSpecification::StubLine:0x000000010cf4aa58 @name="cocoapods-plugins", @version=#<Gem::Version "1.0.0">, @platform="ruby", @extensions=[], @full_name="cocoapods-plugins-1.0.0", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0", @gems_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems", @default_gem=false>

        spec.activate
            ^^^^^^^^^
Did you mean?  activated?
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `load'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `<main>'
---------------------------------------------

---------------------------------------------
Error loading the plugin `cocoapods-search-1.0.1`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x000000010cf6bfa0 @extension_dir=nil, @full_gem_path="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-search-1.0.1", @gem_dir=nil, @ignored=nil, @loaded_from="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/specifications/cocoapods-search-1.0.1.gemspec", @data=#<Gem::StubSpecification::StubLine:0x000000010cf4a468 @name="cocoapods-search", @version=#<Gem::Version "1.0.1">, @platform="ruby", @extensions=[], @full_name="cocoapods-search-1.0.1", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0", @gems_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems", @default_gem=false>

        spec.activate
            ^^^^^^^^^
Did you mean?  activated?
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `load'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `<main>'
---------------------------------------------

---------------------------------------------
Error loading the plugin `cocoapods-trunk-1.6.0`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x000000010cf6bc30 @extension_dir=nil, @full_gem_path="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-trunk-1.6.0", @gem_dir=nil, @ignored=nil, @loaded_from="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/specifications/cocoapods-trunk-1.6.0.gemspec", @data=#<Gem::StubSpecification::StubLine:0x000000010cf498d8 @name="cocoapods-trunk", @version=#<Gem::Version "1.6.0">, @platform="ruby", @extensions=[], @full_name="cocoapods-trunk-1.6.0", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0", @gems_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems", @default_gem=false>

        spec.activate
            ^^^^^^^^^
Did you mean?  activated?
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `load'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `<main>'
---------------------------------------------

---------------------------------------------
Error loading the plugin `cocoapods-try-1.2.0`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x000000010cf6bc08 @extension_dir=nil, @full_gem_path="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-try-1.2.0", @gem_dir=nil, @ignored=nil, @loaded_from="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/specifications/cocoapods-try-1.2.0.gemspec", @data=#<Gem::StubSpecification::StubLine:0x000000010cf43e60 @name="cocoapods-try", @version=#<Gem::Version "1.2.0">, @platform="ruby", @extensions=[], @full_name="cocoapods-try-1.2.0", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0", @gems_dir="/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems", @default_gem=false>

        spec.activate
            ^^^^^^^^^
Did you mean?  activated?
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `load'
/Users/osamaazmatkhan/.rbenv/versions/3.1.0/bin/pod:25:in `<main>'
---------------------------------------------

**Comment by humbleAna** [comment]
i meet the same question

**Comment by vejei** [comment]
Also have the same issue.

**Comment by wlcode1** [comment]
Me too

**Comment by owenzhao** [comment]
Any idea how to solve this issue?

**Comment by owenzhao** [comment]
### Workaround

Install an old version of ruby.

```bash
> brew install ruby@2.7
```

Then add this line to your .bashrc file

```bash
export PATH="/usr/local/opt/ruby@2.7/bin:$PATH"
```

close and reopen terminal.

Now CocoaPods worked again.

**Comment by osamaazmat** [comment]
@owenzhao Worked Perfectly! 

1) Downgraded to Ruby 2.7.5 
2) Reinstalled Cocoapods

Plugins started working!

**Comment by mikehardy** [comment]
ruby-3.0.3 (the latest stable prior to ruby-3.1.0) works perfectly, using rvm to toggle between 3.0.3 and 3.1.0 can reliably cause this problem or fix it. From others above it's clear that 2.7.x works as well

@osamaazmat suggest a title edit for this bug to be more clear for future people: 'cocoapods 1.11.2 not compatible with ruby-3.1.0' and @dnkoutso  this is likely interesting for you as a direct ping (though with apologies, direct pings are no fun) since an incompatibility with a stable release will certainly result in a rain of issue traffic that cannot be avoided

**Comment by spade-zd** [comment]
It Works  for me @osamaazmat!
1. Install rvm
2. rvm install ruby-2.7.5
3. gem install cocopods
4. cd <project_dir>
5. pod install
6. flutter run or Build project on XCode

**Comment by mikehardy** [comment]
@spade-zd you have restated what previous comments show as successful results.
Yes, ruby 2.7.x works. Ruby 3.0.x also works. Those were detailed in comments above.
Cocoapods is currently not compatible with ruby-3.1.0 for whatever reason.

**Comment by ykhandelwal913** [comment]
@osamaazmat none of the solution(workaround) working for me. I have installed ruby 2.7.5 as well but still getting the same error.
 `---------------------------------------------
Error loading the plugin `cocoapods-try-1.2.0`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fa6b314ce98>
Did you mean?  activated?
---------------------------------------------
Error loading the plugin `slather-2.7.2`.

NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fa6b314ecc0>
Did you mean?  activated?
`

**Comment by owenzhao** [comment]
> @osamaazmat none of the solution(workaround) working for me. I have installed ruby 2.7.5 as well but still getting the same error. `--------------------------------------------- Error loading the plugin `cocoapods-try-1.2.0`.
> 
> ## NoMethodError - undefined method `activate' for #Gem::StubSpecification:0x00007fa6b314ce98
> Did you mean? activated?
> Error loading the plugin `slather-2.7.2`.
> 
> NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fa6b314ecc0> Did you mean? activated?`

Double check if you had used Ruby 2.7 after you reinstalled it.

```bash
$ ruby --version
```

**Comment by ykhandelwal913** [comment]
> > @osamaazmat none of the solution(workaround) working for me. I have installed ruby 2.7.5 as well but still getting the same error. `--------------------------------------------- Error loading the plugin `cocoapods-try-1.2.0`.
> > ## NoMethodError - undefined method `activate' for #Gem::StubSpecification:0x00007fa6b314ce98
> > Did you mean? activated?
> > Error loading the plugin `slather-2.7.2`.
> > NoMethodError - undefined method `activate' for #<Gem::StubSpecification:0x00007fa6b314ecc0> Did you mean? activated?`
> 
> Double check if you had used Ruby 2.7 after you reinstalled it.
> 
> ```shell
> $ ruby --version
> ```

ruby --version
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]

**Comment by mikehardy** [comment]
Looks like this is slightly mis-diagnosed above, while ruby-3.1.0 when freshly installed may trigger this, it appears possible on any ruby version, as the problem is actually located in a commit included in rubygems-3.3.0 release, that altered internals there, while cocoapods CLAide package uses those internals and thus no longer works as expected, which transitively breaks cocoapods in general.

https://github.com/rubygems/rubygems/issues/5235 is the upstream issue with details.

https://github.com/rubygems/rubygems/blob/master/UPGRADING.md

While that upstream issue is in progress, you may work around the issue following the 'UPGRADING' guide above, which includes downgrade instructions for rubygems.

I confirm it works in local testing after doing this to downgrade to last cocoapods-compatible version of rubygems:

`gem update --system 3.2.33`

@ykhandelwal913 you might try that command, then report if you also see successful `pod install` once `gem --version` reports 3.2.33 vs 3.3.x (3.3.4 is latest, for what it's worth)

**Comment by ykhandelwal913** [comment]
> gem --version

After updating the version to 3.2.33 i still see the issue.
`gem --version
3.2.33`

`pod --version`
---------------------------------------------
Error loading the plugin cocoapods-deintegrate-1.0.5.

NoMethodError - undefined method activate for #<Gem::StubSpecification:0x00007fd382856558>
Did you mean?  activated?
/Users/ctobuilduser/.rvm/gems/ruby-2.7.2/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in safe_activate_and_require'
/Users/ctobuilduser/.rvm/gems/ruby-2.7.2/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in block in load_plugins'`

**Comment by mikehardy** [comment]
@ykhandelwal913 there *must* be something else going on in your local environment such that the ruby (and the ruby gem version) that is actually in use when `pod` runs is not what you/we are expecting.
If you added a line in your podfile which prints the gem version in use while Podfile code is executing, my *guess* (could be wrong) is that you still have 3.3.x and not 3.2.x

The actual commit that causes this problem has been located by the rubygems current maintainer, from that it's possible to deduce the versions affected, so your result above is really unexpected

**Comment by ykhandelwal913** [comment]
@mikehardy Its working fine. you were right , it failed because of ruby configuration.  I validated it on other machines and this looking good.

**Comment by mikehardy** [comment]
Whew! :relieved: 
Okay, so that's two confirmed reports at least that this works if you are affected, as a temporary workaround:

`gem update --system 3.2.33`

There's a PR lodged in CLAide repo already https://github.com/CocoaPods/CLAide/issues/99, so it's just a matter of time for full resolution. Cheers

**Comment by mikehardy** [comment]
the `claide` gem has a new 1.1.0 release which cocoapods will pull in on a clean install of the cocoapods gem + dependencies (or I suppose if you do a gem update?), fixing this issue going forward.

My ruby environment is pretty disposable (I'm a react-native dev primarily, so I just throwaway whole toolchains and rebuild them all the time) so for me I cleaned with `\rm -fr ~/.rvm` then reinstalled rvm + ruby-3.1.0 + cocoapods and `pod install` works out of the box now.

Cheers

**Comment by ameerhamza65** [comment]
> It Works for me @osamaazmat!
> 
> 1. Install rvm
> 2. rvm install ruby-2.7.5
> 3. gem install cocopods
> 4. cd <project_dir>
> 5. pod install
> 6. flutter run or Build project on XCode

Thanks this solution works for me✌🏻

**Comment by EVANRAN** [comment]
my env is 
1. ruby 3.0.2 by homebrew
2.  gem 3.3.19

It works for me!

`gem install claide ` 

cheers!

**Comment by YonasGhebrebrhan-TomTom** [comment]
[!] Your Podfile requires that the plugin `cocoapods-pod-linkage` be installed. Please install it and try installation again.
