### ISSUE TITLE
Error: undefined method `enforce_available_locales=' for I18n:Module

### ISSUE THREAD

**Issue by podkovyrin** [CocoaPods/CocoaPods#1988]
After update to 0.30.0 get this error on `pod install`, `pod update`, ...

```
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.30.0/lib/cocoapods.rb:12:in `<top (required)>': undefined method `enforce_available_locales=' for I18n:Module (NoMethodError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.30.0/bin/pod:32:in `<top (required)>'
    from /usr/bin/pod:23:in `load'
    from /usr/bin/pod:23:in `<main>'
```

cocoapods.rb:12:

``` ruby
I18n.enforce_available_locales = false
```

Removing this line will fix the problem

**Comment by wellington1993** [comment]
Same issue. Same fix!
@podkovyrin @apalancat  @marcboquet Thanks!
