### ISSUE TITLE
Broken pod after update to 1.0

### ISSUE THREAD

**Issue by brightsider** [CocoaPods/CocoaPods#5325]
# Report

## What did you do?

1. Use Swift in project with Obj-C.
2. Import in Obj-C lib installed from git.
3. Import file with import of lib to Bridging Header.
4. Update CocoaPods to 1.0.
5. Update pod file to new guidelines.
4. pod install

## What did you expected to happen?

The app run correct.

## What happened instead?

I'm got error:

App-Bridging-Header.h:7:
#import "MainViewController.h"
        ^
MainViewController.h:13:9: error: 'SWRevealViewController/SWRevealViewController.h' file not found
#import <SWRevealViewController/SWRevealViewController.h>
        ^
<unknown>:0: error: failed to import bridging header 'App-Bridging-Header.h'
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Realm.h"

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d8ca0396c670ea4c7f009929f5d91f632db98bf8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'App' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'FBSDKCoreKit', '~> 4.11.0'
    pod 'FBSDKLoginKit', '~> 4.11.0'
    pod 'FBSDKShareKit', '~> 4.11.0'
    
    pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git', :tag => 'v2.4.0'
    
    pod 'Fabric', '~> 1.6.7'
    pod 'Crashlytics', '~> 3.7.0'
    target 'AppTests' do
        pod 'OCMock', '~> 3.2'
    end
    
    use_frameworks!
    pod 'RealmSwift', '~> 0.102.1'
end
```

## Project that demonstrates the issue

Can't provide

**Comment by tarigancana** [comment]
this problem happen with me after update to 1.0 also

**Comment by orta** [comment]
Can you please provide a sample project that  shows the problem?

**Comment by tarigancana** [comment]
this is my podfile 
```
platform :ios, '9.0'
use_frameworks!

target 'bible' do
  pod 'RealmSwift', '~> 0.97'
  pod 'ObjectMapper', '~> 1.0'
  pod 'XCGLogger', '~> 3.2'
  pod 'CarbonKit', '~>2.1'
  pod 'Alamofire', '~>3.0'
  pod 'Hue'
end
```

and this is the error that i got after update from 0.39 to 1.0

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Realm.h"
        ^
/Users/rencanatarigan/Library/Developer/Xcode/DerivedData/bible-dyosfnqjsrpgvbcihrzntxoquukk/Build/Products/Debug-iphonesimulator/Realm/Realm.framework/Headers/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found
#import <Realm/RLMArray.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Realm'
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/RealmSwift-Swift.h"
        ^
```

**Comment by neonichu** [comment]
@tarigancana I'm guessing you need to import `RealmSwift/RLMArray.h` since that is the pod you're asking for.

**Comment by neonichu** [comment]
@brightsider you're using a bridging header with `use_frameworks!`, IIRC that only works if you're using module imports. In any case, it should not be necessary to have a bridging header when using frameworks.

**Comment by brightsider** [comment]
@neonichu thanks, import with module import working.
@tarigancana for me helps this - https://github.com/realm/realm-cocoa/issues/3551

**Comment by tarigancana** [comment]
@brightsider Thank you, it's work :)
