### ISSUE TITLE
Errors with <angled> imports

### ISSUE THREAD

**Issue by matteonovelli** [CocoaPods/CocoaPods#5400]
[*] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I'm having errors while running `pod lib lint` with cocoapods v 1.0. 

```
- ERROR | xcodebuild:  /Users/matteo/Library/Developer/Xcode/DerivedData/App-agyylfaavsayemdgzozvlpmubnef/Build/Products/Release-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit.h:44:9: error: 'NSNotificationCenter+PromiseKit.h' file not found with <angled> include; use "quotes" instead
- ERROR | xcodebuild:  /Users/matteo/Library/Developer/Xcode/DerivedData/App-agyylfaavsayemdgzozvlpmubnef/Build/Products/Release-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit.h:50:9: error: 'NSURLConnection+PromiseKit.h' file not found with <angled> include; use "quotes" instead
- ERROR | xcodebuild:  /Users/matteo/Library/Developer/Xcode/DerivedData/App-agyylfaavsayemdgzozvlpmubnef/Build/Products/Release-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit.h:59:9: error: 'UIActionSheet+PromiseKit.h' file not found with <angled> include; use "quotes" instead
- ERROR | xcodebuild:  /Users/matteo/Library/Developer/Xcode/DerivedData/App-agyylfaavsayemdgzozvlpmubnef/Build/Products/Release-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit.h:62:9: error: 'UIAlertView+PromiseKit.h' file not found with <angled> include; use "quotes" instead
- ERROR | xcodebuild:  /Users/matteo/Library/Developer/Xcode/DerivedData/App-agyylfaavsayemdgzozvlpmubnef/Build/Products/Release-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit.h:65:9: error: 'UIView+PromiseKit.h' file not found with <angled> include; use "quotes" instead
- ERROR | xcodebuild:  /Users/matteo/Library/Developer/Xcode/DerivedData/App-agyylfaavsayemdgzozvlpmubnef/Build/Products/Release-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit.h:68:9: error: 'UIViewController+PromiseKit.h' file not found with <angled> include; use "quotes" instead
```
Everything works fine with cocoapods v 0.39.0

## What did you do?
run `pod lib lint`

## What did you expected to happen?

lint my podspec

## What happened instead?

I'm having errors with one of my dependencies => PromiseKit 1.7
I opened an issue on his repo but it seems a bug with cocoapods 1.0 https://github.com/mxcl/PromiseKit/issues/428 

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f7943d04d552105dde68b16e8793a2e9f3af2222
               OpenMobile - http://cvs1/Git/OpenMobilePods @ 42ea01b45ccaad400d9fa740429348b0672b44eb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.1.0
cocoapods-plugins     : 1.0.0
cocoapods-repo-hg     : 0.1.2
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
target 'OMApi' do

	pod 'AFNetworking', '2.6.0'
	pod 'AFNetworkActivityLogger', '2.0.4'
	pod 'PromiseKit', '~> 1.0'
	pod 'JSONModel', '~> 1.0'

end
```

## Project that demonstrates the issue

https://github.com/matteonovelli/PruebaCocoaPods/tree/master/OMApi

**Comment by orta** [comment]
To give some context, the PromiseKit imports look like this:

``` objc
#import <PromiseKit/Promise.h>

#ifdef PMK_WHEN
#import <PromiseKit/Promise+When.h>
#endif
#ifdef PMK_UNTIL
#import <PromiseKit/Promise+Until.h>
#endif
#ifdef PMK_PAUSE
#import <PromiseKit/Promise+Pause.h>
#endif
#ifdef PMK_JOIN
#import <PromiseKit/Promise+Join.h>
#endif

#ifdef PMK_ACACCOUNTSTORE
#import <ACAccountStore+PromiseKit.h>
#endif
#ifdef PMK_AVAUDIOSESSION
#import <AVAudioSession+PromiseKit.h>
#endif
#ifdef PMK_CLGEOCODER
#import <CLGeocoder+PromiseKit.h>
#endif
```

Wherein the top ones `<PromiseKit/Promise+When.h>` work, and the bottom `#import <CLGeocoder+PromiseKit.h>` don't. Personally, I'm not really sure why you'd use the bottom type, or why they use the two different import types.

**Comment by matteonovelli** [comment]
I don't know. I tried to open an issue on his repo but they answered that's probably a cocoapods 1.0 bug. With cocoapods 0.39 works fine

**Comment by matteonovelli** [comment]
Fixed on PromiseKit: https://github.com/mxcl/PromiseKit/pull/438
