### PR TITLE
[Acknowledgements] Prevent crash when license type is nil

### LINKED ISSUE #5826: Crash when generating acknowledgements
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` after updating CocoaPods to 1.1.0.beta.2

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

```
NoMethodError - undefined method `encode' for nil:NilClass
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:75:in `sanitize_encoding'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:40:in `hash_for_spec'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:27:in `block in licenses'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:26:in `each'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:26:in `licenses'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:16:in `plist'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/generator/acknowledgements/plist.rb:9:in `save_as'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:187:in `block in create_acknowledgements'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:183:in `each'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:183:in `create_acknowledgements'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:33:in `block in install!'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:160:in `block (2 levels) in install_libraries'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `each'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `block in install_libraries'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer.rb:115:in `install!'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command/update.rb:60:in `run'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command.rb:50:in `run'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.0.beta.2/bin/pod:55:in `<top (required)>'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/bin/pod:22:in `load'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/bin/pod:22:in `<main>'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/marcelofabri/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.6.0
        Host : Mac OS X 10.12 (16A319)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.3
Ruby lib dir : /Users/marcelofabri/.rvm/rubies/ruby-2.1.2/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 60f9327660e7b1aa44f4514ff3e954aa4ab80c17
```

### Installation Source

```
Executable Path: /Users/marcelofabri/.rvm/gems/ruby-2.1.2/bin/pod
```

### Plugins

```
cocoapods-acknowledgements : 1.1.1
cocoapods-deintegrate      : 1.0.1
cocoapods-keys             : 1.7.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.1.0
slather                    : 2.3.0
```

## Project that demonstrates the issue

It seems that https://github.com/CocoaPods/CocoaPods/commit/8447331639fa6a73eda3eecf8208d80704dfdb35 introduced this issue.

### PR DESCRIPTION
**Pull request by marcelofabri**
This should fix #5826

### CODE REVIEW

**Comment by segiddins** [comment]
Thanks!
