### ISSUE TITLE
NoMethodError - undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by dgobaud** [CocoaPods/CocoaPods#9239]
same error in 1.7.1, 1.8.0, and 1.8.3

```
NoMethodError - undefined method `each' for nil:NilClass
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:96:in `block in add_to_dependency_graph'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:94:in `each'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:94:in `add_to_dependency_graph'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:45:in `block in generate_version_locking_dependencies'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:44:in `each'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:44:in `generate_version_locking_dependencies'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:849:in `generate_version_locking_dependencies'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:123:in `analyze'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:410:in `analyze'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:156:in `install!'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/bin/pod:23:in `load'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/davidgobaud/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by dnkoutso** [comment]
There is insufficient information for us to diagnose this issue. Please provide a sample app and steps to reproduce.

Going to close preemptively until a sample app or steps to reproduce are included since we are getting a high volume of issues.

**Comment by bhandaribhumin** [comment]
@dnkoutso same issue I'm facing 

project-103524:ios bhumin3imac$ pod install

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/bhumin3imac/.gem/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G1012)
       Xcode : 11.2 (11B52)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target '@FirebaseApp' do
	project '@FirebaseApp.xcodeproj'
	pod 'FirebaseMessaging', '~> 2.0.0'
end
```

### Error

```
NoMethodError - undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:265:in `new_from_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:212:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:112:in `open'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1098:in `block (2 levels) in inspect_targets_to_integrate'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1097:in `each'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1097:in `block in inspect_targets_to_integrate'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1092:in `inspect_targets_to_integrate'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/bhumin3imac/.gem/bin/pod:22:in `load'
/Users/bhumin3imac/.gem/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%5B%5D%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `size' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9295 [closed] [2 comments]
   a week ago

 - NoMethodError - undefined method `real_path`
   https://github.com/CocoaPods/CocoaPods/issues/8082 [open] [13 comments]
   25 Feb 2019

 - NoMethodError - undefined method `each' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9239 [closed] [1 comment]
   5 weeks ago

and 206 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

**Comment by cchamb-gh** [comment]
In case anybody else gets this error and is routed here:

You will see this error if you've had a bad merge on your Podfile.lock. Specifically, when I saw the issue, it was because there was a trailing colon ":" on a pod line like so:

```
...
  - SomePod (1.0.0):
    - SomeDependency
  - TheProblemLine (0.0.1):
  - YetAnotherPod (2.0.0):
    - MoreDepdencies
...

```

You can delete that errant line and then re-run `pod install` to recreate a working Podfile.lock.

**Comment by sarykemmoun** [comment]
> In case anybody else gets this error and is routed here:
> 
> You will see this error if you've had a bad merge on your Podfile.lock. Specifically, when I saw the issue, it was because there was a trailing colon ":" on a pod line like so:
> 
> ```
> ...
>   - SomePod (1.0.0):
>     - SomeDependency
>   - TheProblemLine (0.0.1):
>   - YetAnotherPod (2.0.0):
>     - MoreDepdencies
> ...
> ```
> 
> You can delete that errant line and then re-run `pod install` to recreate a working Podfile.lock.

@cchamb-gh Thanks!
You saved my day!

**Comment by souzasmatheus** [comment]
@cchamb-gh 's solution really worked perfectly for me. I deleted the unnecessary semi-colon (which is used to indicate that the following packages, which are normally indented, are dependencies) and ran `pod install`. The dependency was added automatic and everything worked.

**Comment by kovkev** [comment]
I deleted Podfile.lock and ran `pod install` and it didn't solve it for me.

**Comment by w819314930** [comment]
flutter clean
flutter pub get
pod install
problem solving

**Comment by rafaelperozin** [comment]
The @cchamb-gh is right.
You only need to remove the semi-colon from items without children.

For example: On this case, you only need to remove the semi-colon from `TheProblemLine (0.0.1)`.
```
...
  - SomePod (1.0.0):
    - SomeDependency
  - TheProblemLine (0.0.1):
  - YetAnotherPod (2.0.0):
    - MoreDepdencies
...
```

**Comment by minhbaljeet2809** [comment]
> In case anybody else gets this error and is routed here:
> 
> You will see this error if you've had a bad merge on your Podfile.lock. Specifically, when I saw the issue, it was because there was a trailing colon ":" on a pod line like so:
> 
> ```
> ...
>   - SomePod (1.0.0):
>     - SomeDependency
>   - TheProblemLine (0.0.1):
>   - YetAnotherPod (2.0.0):
>     - MoreDepdencies
> ...
> ```
> 
> You can delete that errant line and then re-run `pod install` to recreate a working Podfile.lock.

Tks. this is  solve my problem

**Comment by Eobsv** [comment]
Hello

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I ran 'pod install'
* What did you expect to happen?
I wanted to get my pods included into my flutter project during the build, and then run the application on simulator.
* What happened instead?
I got error attached below

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.0 (13A233)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :rease,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
NoMethodError - undefined method `each' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/target/pod_target.rb:846:in `_add_recursive_dependent_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/target/pod_target.rb:833:in `block in recursive_dependent_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/target/pod_target.rb:832:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/target/pod_target.rb:832:in `recursive_dependent_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:88:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:88:in `flat_map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:88:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:597:in `validate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:163:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```


After updating MacOS once moreI tried solution from @w819314930, I couldn’t try solution from @cchamb-gh because I do not have Podfile.lock file. What more can I do? I’d be thankful for any suggestions.

**Comment by manjeetcars24** [comment]
> I deleted Podfile.lock and ran `pod install` and it didn't solve it for me.

This helped. Seems to be an issue with mixed info within Podfile.lock
