### ISSUE TITLE
NoMethodError - undefined method `repo' for nil:NilClass

### ISSUE THREAD

**Issue by AlejandroJL** [CocoaPods/CocoaPods#3291]
### Command

```
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.3 (14D105g)
       Xcode : 6.2 (6C131e)
         Git : git version 2.3.3
Ruby lib dir : /Users/AlejandroJL/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/Homebrew/homebrew @ cbd562038a66f7fb07a304bbbb464902e5643061
               master-1 - https://github.com/Homebrew/homebrew @ cbd562038a66f7fb07a304bbbb464902e5643061
               master-2 - https://github.com/Homebrew/homebrew @ cbd562038a66f7fb07a304bbbb464902e5643061
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.0'

target 'Dev' do
    pod "Alamofire",                        "1.1.4"
end

target 'DevTests' do

end
```

### Error

```
NoMethodError - undefined method `repo' for nil:NilClass
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:171:in `each'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:171:in `block in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:170:in `update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:155:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by neonichu** [comment]
Possible cause:

```
Repositories : master - https://github.com/Homebrew/homebrew @ cbd562038a66f7fb07a304bbbb464902e5643061
               master-1 - https://github.com/Homebrew/homebrew @ cbd562038a66f7fb07a304bbbb464902e5643061
               master-2 - https://github.com/Homebrew/homebrew @ cbd562038a66f7fb07a304bbbb464902e5643061
```

Those aren't actual spec repos, curious how those got there. Did you add those manually by any chance?

Can you `rm -rf /Users/boris/.cocoapods/repos/*` and try again?

**Comment by AlejandroJL** [comment]
Hello @neonichu,

Yes, I've tried in the past and still fails :(

Thanks for your answer!

**Comment by AlejandroJL** [comment]
@neonichu Result after deleting repositories

~/Desktop/Test  pod install
Analyzing dependencies
Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.3 (14D105g)
       Xcode : 6.2 (6C131e)
         Git : git version 2.3.3
Ruby lib dir : /Users/AlejandroJL/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/Homebrew/homebrew @ 39627dc244dab5ba804eb9da841887c72b795f5c
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
#platform :ios, '7.0'

target 'Dev' do
    #pod "Alamofire",                        "1.1.4"
end

target 'DevTests' do

end
```

### Error

```
NoMethodError - undefined method `repo' for nil:NilClass
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:171:in `each'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:171:in `block in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:170:in `update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by AlejandroJL** [comment]
If I do with the previous version (0.35.0) everything works fine: /.

**Comment by neonichu** [comment]
Curious, especially that it works fine with 0.35 - could you please also post the output of `pod install --verbose`?

**Comment by AlejandroJL** [comment]
Sure!

~/Desktop/Test  pod install --verbose
  Preparing
    Migrating to CocoaPods 0.36

Analyzing dependencies

Updating spec repositories

Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
  $ /usr/local/bin/git clone 'https://github.com/CocoaPods/Specs.git' master
  --depth=1
  Cloning into 'master'...
Checking out files: 100% (32626/32626), done.

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.3 (14D105g)
       Xcode : 6.2 (6C131e)
         Git : git version 2.3.3
Ruby lib dir : /Users/AlejandroJL/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/Homebrew/homebrew @ ca90526ce3a20e9a8052fd19bcc7ad5c03e1acdc
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
#platform :ios, '7.0'

target 'Dev' do
    #pod "Alamofire",                        "1.1.4"
end

target 'DevTests' do

end
```

### Error

```
NoMethodError - undefined method `repo' for nil:NilClass
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:171:in `each'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:171:in `block in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:170:in `update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by neonichu** [comment]
So doing

`/usr/local/bin/git clone 'https://github.com/CocoaPods/Specs.git' master
--depth=1`

somehow results in a checkout of <https://github.com/Homebrew/homebrew> :scream:

I would blame some crazy Git option, but you were saying it works fine with 0.35.

**Comment by AlejandroJL** [comment]
I've checked my configuration file gitconfig. And I see nothing strange :(

**Comment by neonichu** [comment]
Could you possibly post your ~/.gitconfig? Make sure to remove the `[name]` section so that you don't leak your email address :)

**Comment by AlejandroJL** [comment]
Yep, Thanks @neonichu 
[filter "media"]
	clean = git-media-clean %f
	smudge = git-media-smudge %f
[user]
	name = AlejandroJL
	email = XXXX
[core]
	editor = subl
	excludesfile = /Users/AlejandroJL/.gitignore_global
[merge]
	ff = false
	tool = Kaleidoscope
[push]
	default = matching
[mergetool]
	keepBackup = true
	prompt = false
[mergetool "Kaleidoscope"]
	cmd = ksdiff --merge --output \"$MERGED\" --base \"$BASE\" -- \"$LOCAL\" --snapshot \"$REMOTE\" --snapshot
	trustexitcode = true
[difftool "Kaleidoscope"]
	cmd = ksdiff --partial-changeset --relative-path \"$MERGED\" -- \"$LOCAL\" \"$REMOTE\"
[difftool]
	prompt = false
[diff]
	tool = Kaleidoscope

**Comment by orta** [comment]
Hrm, nothing suspicious there at all. 

Can you please try running `/usr/local/bin/git clone 'https://github.com/CocoaPods/Specs.git' master --depth=1` in a spare/temporary folder, and see if that does the correct clone?

**Comment by AlejandroJL** [comment]
~/Desktop/cocoapods   /usr/local/bin/git clone 'https://github.com/CocoaPods/Specs.git' master --depth=1
Cloning into 'master'...
remote: Counting objects: 74731, done.
remote: Compressing objects: 100% (51634/51634), done.
remote: Total 74731 (delta 12823), reused 73112 (delta 12794), pack-reused 0
Receiving objects: 100% (74731/74731), 12.56 MiB | 3.41 MiB/s, done.
Resolving deltas: 100% (12823/12823), done.
Checking connectivity... done.
Checking out files: 100% (33037/33037), done.
~/Desktop/cocoapods  ls
total 0
drwxr-xr-x   3 AlejandroJL  staff   102B 24 mar 00:42 .
drwx------+ 12 AlejandroJL  staff   408B 24 mar 00:42 ..
drwxr-xr-x   8 AlejandroJL  staff   272B 24 mar 00:42 master

**Comment by orta** [comment]
Odd too, the commit that you have for home-brew doesn't exist on home-brew or CocoaPods:

https://github.com/cocoapods/coocapods/commits/cbd562038a66f7fb07a304bbbb464902e5643061
https://github.com/Homebrew/homebrew/commits/cbd562038a66f7fb07a304bbbb464902e5643061

**Comment by kylef** [comment]
Could we get the output of `pod repo list` @AlejandroJL?

**Comment by AlejandroJL** [comment]
Hello @kylef,
Today:

 pod repo list                                                                                                                                                                                                      ‹2.2.0›

master
- Type: git ()
- URL:
- Path: /Users/AlejandroJL/.cocoapods/repos/master

master-1
- Type: git ()
- URL:
- Path: /Users/AlejandroJL/.cocoapods/repos/master-1

master-2
- Type: git ()
- URL:
- Path: /Users/AlejandroJL/.cocoapods/repos/master-2

**Comment by AlejandroJL** [comment]
@orta Today with version 0.36.3
rm -fr ~/.cocoapods
pod setup --verbose

Setting up CocoaPods master repo

Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master --depth\=1
  Cloning into 'master'...
Checking out files: 100% (34207/34207), done.
  $ /usr/local/bin/git checkout master
  Already on 'master'
  Your branch is up-to-date with 'origin/master'.
Setup completed

--- 
pod update --verbose

Update all pods
  Preparing
    Migrating to CocoaPods 0.36

Analyzing dependencies

Updating spec repositories

Creating shallow clone of spec repo `master-1` from `https://github.com/CocoaPods/Specs.git`
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master-1 --depth\=1
  Cloning into 'master-1'...
Checking out files: 100% (34207/34207), done.

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod update --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.36.3
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.3 (14D127a)
       Xcode : 6.2 (6C131e)
         Git : git version 2.3.3
Ruby lib dir : /Users/AlejandroJL/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/Homebrew/homebrew @ ea1666ed89973f7797ef9121ad859881c9900552
               master-1 - https://github.com/Homebrew/homebrew @ ea1666ed89973f7797ef9121ad859881c9900552
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Demo' do
	pod 'AFNetworking', '2.5.2'
end
```

### Error

```
NoMethodError - undefined method `repo' for nil:NilClass
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:171:in `each'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:171:in `block in update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:170:in `update_repositories_if_needed'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:189:in `analyze'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:90:in `install!'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:155:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/AlejandroJL/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by AlejandroJL** [comment]
The comment with id ea1666ed89973f7797ef9121ad859881c9900552 -> https://github.com/CocoaPods/Specs/commit/ea1666ed89973f7797ef9121ad859881c9900552

Version 0.35.0 continues to work all great :(

**Comment by AlejandroJL** [comment]
Same in 0.37.0 beta 1

**Comment by kylef** [comment]
@AlejandroJL Can you give me a `pod repo list` from 0.37.0.beta.1 too? I changed the output to make it more helpful.

**Comment by AlejandroJL** [comment]
@kylef 0.37.0 Final

 pod repo list                                                                                                      ‹2.2.0›

master
- Type: git (master)
- URL:  file:///Users/AlejandroJL/.cocoapods/repos/master/.git
- Path: /Users/AlejandroJL/.cocoapods/repos/master

1 repo

**Comment by kylef** [comment]
@AlejandroJL That's bizarre, the URL for the repository is reported as `file:///Users/AlejandroJL/.cocoapods/repos/master/.git` instead of `https://github.com/CocoaPods/Specs.git`.

Can you run the following and see what the output is:

```bash
$ cd ~/.cocoapods/repos/master
$ git remote -v
$ git config --local -l
```

**Comment by houmie** [comment]
I have the same problem. I better downgrade.

```
NoMethodError - undefined method `each' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:72:in `block in add_to_dependency_graph'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:70:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:70:in `add_to_dependency_graph'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:32:in `block in generate_version_locking_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:31:in `generate_version_locking_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer.rb:294:in `generate_version_locking_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer/analyzer.rb:54:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:190:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:112:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:111:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by mojtabacazi** [comment]
Getting same here with 3.7.1

### Command

```
/usr/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5bbeeed20c77b5f1de04d1ca5b5c2d5a61be1435
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'


pod 'AFNetworking', '~> 2.2'
pod 'AFJSONRPCClient', '~> 2.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'CocoaLumberjack', '~> 1.8'
pod 'PNChart', '~> 0.7'
pod 'SSKeychain', '~> 1.2'
pod 'Parse', '~> 1.7'
pod 'JSONModel', '~> 1.1'
```

### Error

```
NoMethodError - undefined method `exist?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:130:in `ensure in in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:130:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:101:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:31:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader.rb:34:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/pod_source_installer.rb:78:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/pod_source_installer.rb:45:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:304:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:279:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:278:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:270:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:270:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:122:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:120:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:92:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:155:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@mojtabacazi that's a different thing, please open a separate issue for it

**Comment by mojtabacazi** [comment]
@segiddins Oh yea, moved it here
https://github.com/CocoaPods/CocoaPods/issues/3587

**Comment by neonichu** [comment]
@AlejandroJL were you able to resolve this with 0.37.2 by any chance?

**Comment by nikfil89** [comment]
I had exactly the same error when I tryed to access my private specs repository and solved by 

**pod repo add [PrivateRepoName] [URL to private repo]**

so answer to original question may be to first remove invalid master with

**pod repo remove master**

and add valid with

**pod repo add master https://github.com/CocoaPods/Specs.git**

**Comment by AlejandroJL** [comment]
@neonichu nop, same problem in 0.38.2 :/

**Comment by neonichu** [comment]
@AlejandroJL so weird — did you already try to use the system git instead of your custom one?

**Comment by AlejandroJL** [comment]
@neonichu yep (current in El Capitan B5).
git  --version
git version 2.3.2 (Apple Git-55)
