### ISSUE TITLE
GCC_TREAT_WARNINGS_AS_ERRORS for development pod applies to transitive dependencies

### ISSUE THREAD

**Issue by k0nserv** [CocoaPods/CocoaPods#9317]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Created the following `Podfile`, ran `pod install`, and tried to build the resulting project.

<details>

<summary>
Podfile
</summary>

```ruby
platform :ios, '11.0'
use_frameworks!

install! 'cocoapods', disable_input_output_paths: true

target 'Backpack Native' do
  inhibit_all_warnings!

  pod 'Backpack', :path => '../', inhibit_warnings: false
  pod 'SwiftLint', '~> 0.31.0'
  pod 'AppCenter', '~> 2.4.0'
  pod 'AppCenter/Distribute', '~> 2.4.0'

  target 'Backpack_Tests' do
    inherit! :search_paths
  end

  target 'Backpack_SnapshotTests' do
      inherit! :search_paths
      pod 'iOSSnapshotTestCase/Core', '~> 4.0.0'
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end

  puts 'Removing static analyzer support'
  installer.pods_project.targets.each do |target|
    case target.name
    when "FSCalendar"
      target.build_configurations.each do |config|
          config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
      end
    when "Backpack"
      target.build_configurations.each do |config|
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      end
    end
  end
end
```

</details>

With the goal of setting `GCC_TREAT_WARNINGS_AS_ERRORS` to `YES` for the `Backpack` pod.

## What did you expect to happen?

For Xcode to treat warnings in the Backpack target within the `Pods.xcproject` as errors while inhibiting warnings in othe explicit pods declared  in the `Podfile` and transitive dependencies of `Backpack`.

## What happened instead?

The build fails due to warnings in Backpack's transitive dependencies being converted to errors rather than being supressed. 

Those specific targets within the `Pods.xcproject` have `GCC_TREAT_WARNINGS_AS_ERRORS` set to `NO` for all build configurations.

## CocoaPods Environment

<details>
<summary>CocoaPods env</summary>

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.0 (11A420a)
         Git : git version 2.23.0
Ruby lib dir : /Users/hugotunius/.rbenv/versions/2.5.1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 267d27795b6d370159911fc0c13f9db4b36f052b
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/hugotunius/Code/Personal/backpack-ios/vendor/bundle/ruby/2.5.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```
</details>
</summary>

## Project that demonstrates the issue

https://github.com/skyscanner/backpack-ios with the following patch:

<details>
<summary>patch.diff</summary>

```
diff --git a/Example/Podfile b/Example/Podfile
index fcf5ee0..805da88 100644
--- a/Example/Podfile
+++ b/Example/Podfile
@@ -4,7 +4,9 @@ use_frameworks!
 install! 'cocoapods', disable_input_output_paths: true
 
 target 'Backpack Native' do
-  pod 'Backpack', :path => '../'
+  inhibit_all_warnings!
+
+  pod 'Backpack', :path => '../', inhibit_warnings: false
   pod 'SwiftLint', '~> 0.31.0'
   pod 'AppCenter', '~> 2.4.0'
   pod 'AppCenter/Distribute', '~> 2.4.0'
@@ -27,10 +29,15 @@ post_install do |installer|
 
   puts 'Removing static analyzer support'
   installer.pods_project.targets.each do |target|
-      if target.name == "FSCalendar"
-          target.build_configurations.each do |config|
-              config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
-          end
+    case target.name
+    when "FSCalendar"
+      target.build_configurations.each do |config|
+          config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
+      end
+    when "Backpack"
+      target.build_configurations.each do |config|
+          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
       end
+    end
   end
 end
diff --git a/Example/Podfile.lock b/Example/Podfile.lock
index c9239d8..7790cc9 100644
--- a/Example/Podfile.lock
+++ b/Example/Podfile.lock
@@ -52,6 +52,6 @@ SPEC CHECKSUMS:
   SwiftLint: 7a0227733d786395817373b2d0ca799fd0093ff3
   TTTAttributedLabel: 0a2ac7b2dd726d32a070dafb01446026b11e624f
 
-PODFILE CHECKSUM: cdc99ac34e26556645e19d76b3756f3c725f7c2d
+PODFILE CHECKSUM: 281c486d3f923aa0035adc645079982c7045b1da
 
 COCOAPODS: 1.8.4
```

</details>

**Comment by k0nserv** [comment]
I tried another test using multiple pod projects in the hope that it would improve the isolation between compile units, no luck with that either.

<details>
<summary>patch.diff</summary>

```
diff --git a/Example/Podfile b/Example/Podfile
index fcf5ee0..04c6aec 100644
--- a/Example/Podfile
+++ b/Example/Podfile
@@ -1,10 +1,14 @@
 platform :ios, '11.0'
 use_frameworks!
 
-install! 'cocoapods', disable_input_output_paths: true
+install! 'cocoapods', disable_input_output_paths: true,
+                      generate_multiple_pod_projects: true,
+                      incremental_installation: true
 
 target 'Backpack Native' do
-  pod 'Backpack', :path => '../'
+  inhibit_all_warnings!
+
+  pod 'Backpack', :path => '../', inhibit_warnings: false
   pod 'SwiftLint', '~> 0.31.0'
   pod 'AppCenter', '~> 2.4.0'
   pod 'AppCenter/Distribute', '~> 2.4.0'
@@ -20,17 +24,23 @@ target 'Backpack Native' do
 end
 
 post_install do |installer|
-  installer.pods_project.build_configurations.each do |config|
-    config.build_settings.delete('CODE_SIGNING_ALLOWED')
-    config.build_settings.delete('CODE_SIGNING_REQUIRED')
-  end
+  installer.pod_target_subprojects.each do |subproject|
+    subproject.build_configurations.each do |config|
+      config.build_settings.delete('CODE_SIGNING_ALLOWED')
+      config.build_settings.delete('CODE_SIGNING_REQUIRED')
+    end
 
-  puts 'Removing static analyzer support'
-  installer.pods_project.targets.each do |target|
-      if target.name == "FSCalendar"
-          target.build_configurations.each do |config|
-              config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
-          end
+    subproject.targets.each do |target|
+      case subproject.project_name.strip
+      when "FSCalendar"
+        target.build_configurations.each do |config|
+            config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
+        end
+      when "Backpack"
+        target.build_configurations.each do |config|
+            config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
+        end
       end
+    end
   end
 end
diff --git a/Example/Podfile.lock b/Example/Podfile.lock
index c9239d8..743da4e 100644
--- a/Example/Podfile.lock
+++ b/Example/Podfile.lock
@@ -52,6 +52,6 @@ SPEC CHECKSUMS:
   SwiftLint: 7a0227733d786395817373b2d0ca799fd0093ff3
   TTTAttributedLabel: 0a2ac7b2dd726d32a070dafb01446026b11e624f
 
-PODFILE CHECKSUM: cdc99ac34e26556645e19d76b3756f3c725f7c2d
+PODFILE CHECKSUM: b51aa23f8ade37d8c01002d8fe4c1322d8d2b2c8
 
-COCOAPODS: 1.8.4
+COCOAPODS: 1.8.1
```
</details>

**Comment by dnkoutso** [comment]
@k0nserv is this the error you are seeing?
```
While building module 'MBProgressHUD' imported from /Users/dimitris/Development/ios/backpack-ios/Backpack/Toast/Classes/BPKToast.m:21:
In file included from <module-includes>:1:
In file included from /Users/dimitris/Development/ios/backpack-ios/Example/Pods/Target Support Files/MBProgressHUD/MBProgressHUD-umbrella.h:13:
/Users/dimitris/Development/ios/backpack-ios/Example/Pods/MBProgressHUD/MBProgressHUD.h:88:45: error: this block declaration is not a prototype [-Werror,-Wstrict-prototypes]
typedef void (^MBProgressHUDCompletionBlock)();
                                            ^
                                             void
1 error generated.
/Users/dimitris/Development/ios/backpack-ios/Backpack/Toast/Classes/BPKToast.m:21:9: fatal error: could not build module 'MBProgressHUD'
#import <MBProgressHUD/MBProgressHUD.h>
 ~~~~~~~^
2 errors generated.
```

Hm `GCC_TREAT_WARNINGS_AS_ERRORS` is set to `NO` for `MBProgressHUD` so I am still investigating.

 I am building with Xcode 11 but got the same error for Xcode 10.2.1

**Comment by dnkoutso** [comment]
How does Xcode without CocoaPods handle that? It is possible that invoking a target which treats warnings as error this gets passed into its dependencies?

**Comment by k0nserv** [comment]
Hey @dnkoutso thanks for getting back, yeah that's the error I got too. I think this is down to the fact that even though `MDProgressHUD` gets built on its own when building the main project it still needs to parse any headers for `MDProgressHUD` again in which case the main project's settting for `GCC_TREAT_WARNINGS_AS_ERRORS` is active rather than the `MDProgressHUD` target's settings.

I haven't tried an Xcode only build, but I'm confident the same thing would happen there so I think we can rule out CocoaPods here. Feel free to close this
