### ISSUE TITLE
pod lib lint can't find 'gvc.h' file

### ISSUE THREAD

**Issue by taozeyuMention** [CocoaPods/CocoaPods#6319]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I am using CocoaPods 1.1.1, pod lib lint does not work, it gives me an error:
```
fatal error: 'gvc.h' file not found
```
but it works fine  when I compiling my own project.
it also works fine with pod version 0.38.2.

## What did you do?

run pod lib lint with my podspec:

```
Pod::Spec.new do |s|


  s.name         = "HTR3"
  s.version      = "0.0.1"
  s.summary      = "高性能URLMatcher."

  s.description  = <<-DESC
                   高性能 URLMatcher .
                   DESC

  s.homepage     = "https://github.com/NEYouFan/HTR3"

  s.license      = "MIT"

  s.author       = { "netease" => "taozeyu890217@126.com"}

  s.source       = { :git => "https://git.hz.netease.com/git/mobile/HTR3.git" }

  s.platform     = :ios, "6.0"

  s.ios.deployment_target = "6.0"

  s.source_files  = "r3/project-mac/R3/R3/Sources/*.{h,m}",\
                    "r3/project-mac/R3/R3/Sources/include/*.h",\
                    "r3/project-mac/R3/R3/Sources/zmalloc.{c,h}"

  s.requires_arc = false

  s.public_header_files = "r3/project-mac/R3/R3/Sources/include/*.h"
  

end
```

## What did you expect to happen?

pod lib lint pass validation

## What happened instead?

pod lib lints fails:

```
 NOTE  | xcodebuild:  /Users/taozeyu/Library/Developer/Xcode/DerivedData/App-bwuapdqhvpbmpugawnpddmezukyj/Build/Products/Release-iphonesimulator/HTR3/HTR3.framework/Headers/r3_gvc.h:11:10: fatal error: 'gvc.h' file not found
```

## CocoaPods Environment

1.1.1 version

## Other

my project gitHub:
https://github.com/NEYouFan/HTR3

**Comment by benasher44** [comment]
Hi @taozeyuMention! I looked at your project on GitHub, and I don't see a `gvc.h`. It appears that `gvc.h` isn't in any of the paths listed in your podspec. When you `pod lib lint`, CocoaPods grabs all of the files listed in the file patterns in your podspec and uses those to try to build your project, if there are headers imported in your source code that are not included in your podspec, then the pod will fail to lint. Hope this helps!

**Comment by taozeyuMention** [comment]
Thank you， that helps me a lot~
