### ISSUE TITLE
Latest version breaks build

### ISSUE THREAD

**Issue by robbdimitrov** [CocoaPods/CocoaPods#2545]
[removed comment]

I'm having problems building since the update to 0.34

```
Undefined symbols for architecture x86_64:
  "_FXReachabilityNotificationStatusKey", referenced from:
     ...
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      ...
  "_OBJC_CLASS_$_EGOCache", referenced from:
      ...
  "_OBJC_CLASS_$_FXReachability", referenced from:
      ...
  "_OBJC_CLASS_$_MBProgressHUD", referenced from:
      ...
      l_OBJC_$_CATEGORY_MBProgressHUD_$_Helpers in MBProgressHUD+Helpers.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

[removed comment] 

Any ideas on what to do with this?
