### ISSUE TITLE
Undefined method 'to_ary' when running pod install v0.39

### ISSUE THREAD

**Issue by hmistry** [CocoaPods/CocoaPods#5716]
### Command

```
/Users/hm/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

Ran `pod _0.39.0_ install` on my Xcode Project. It doesn't matter whether it's our existing project or you create a new Xcode project, add the `Podfile` and run `pod install`.

Same issue as #4345 and #4391 . Tried with v1.0.1 but that didn't work without targets... will transition later.

I got this to work with ruby 2.2 and pod v0.39.

* What did you expect to happen?

It installs the pods. 😄 

* What happened instead?

Errors 😞 

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/hm/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 889733511feb92b748ecef917ee0f29a21d60253
               master-1 - http://github.com/CocoaPods/Specs.git @ 0e2c8ad52d8d50840181b559eb779d102062c766
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '8.0'

use_frameworks!

pod 'AFNetworking', '~> 3.0'
pod 'ECSlidingViewController', '~> 2.0'
pod 'DateTools', '~> 1.7'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9'
pod 'Fabric', '~> 1.6'
pod 'Crashlytics', '~> 3.7'
pod 'pop', '~> 1.0'
pod 'InstagramKit', :git => 'https://github.com/afilipowicz/InstagramKit.git', :branch => 'dev'
pod 'InstagramKit/UICKeyChainStore', :git => 'https://github.com/afilipowicz/InstagramKit.git', :branch => 'dev'

pod 'RxDataSources', '~> 0.7'
pod 'Moya/RxSwift', '~> 6.5'
pod 'Moya-ModelMapper/RxSwift', '~> 2.0'
pod 'RxCocoa', '~> 2.5'
pod 'RxOptional', '~> 2.0'
pod 'Moya-JASON/RxSwift', '~> 0.2'
pod 'Nuke', '~> 3.1'
pod 'SnapKit', '~> 0.21'
pod 'FBSDKCoreKit', '4.10.1'
pod 'FBSDKShareKit', '4.10.1'
pod 'FBSDKLoginKit', '4.10.1'
pod 'Bolts', '1.6.0'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
Did you mean?  to_query
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/hm/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/hm/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/hm/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/hm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/hm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Either update to 1.0 or use an older version of Ruby.

**Comment by sghiassy** [comment]
This problem started occurring on Ruby 2.3.0. As @segiddins mentioned. You can use an older version of Ruby to bypass this problem

```
rvm install ruby-2.2.3
rvm use ruby-2.2.3
```

**Comment by hmistry** [comment]
Yep. I already figured out the work around as I mentioned in my original post. The only reason for posting it was to inform the dev team of the issue should they wish to fix it. 😄
