### ISSUE TITLE
Undefined symbols with version 0.38.2

### ISSUE THREAD

**Issue by liamogierussell** [CocoaPods/CocoaPods#3972]
Hi,

I am building a static framework which uses cocoapods to handle my external dependencies. When using cocoapods version 0.37.2 this works fine. However I just updated to 0.38.2. My podfile is as follows.

```
def available_pods
    pod 'MJExtension', '2.4.4'
    pod 'CocoaLumberjack', '2.0'
    pod 'AFNetworking', '2.5.4'
    pod 'OCMock'
end

target 'mainTarget' do
    available_pods
end

target 'myTests' do
    available_pods
end
```
Pod install runs correctly giving no errors and the static framework builds fine. However when I add my framework to a host app I get the following errors.

![screen shot 2015-08-05 at 11 44 54](https://cloud.githubusercontent.com/assets/12812886/9084043/6c9abdac-3b67-11e5-980d-4c5de652c0b9.png)

Any reason why with version  version 0.38.2 my static framework can pick up the dependencies correctly however when added to a host app the symbols are undefined?

Just an extra note aswell, the symbols don't seem to be defined for any architecture i.e if i go to run on a device the undefined symbols error appears for that architecture. 

I have also checked a number of the usual issues if it helps - 

1. My configurations are set correctly in the project.
2. The pods project and static framework is set to build all architectures at all times.
3. The pods library is linked correctly in 'Link Binary With Libraries' in both my main and test targets.
4. I'v tried cleaning the derived data and reopening xcode. 
5. I'v tried using 'link_with' in the podfile instead of the seperate targets just to check. 
6. My 'Other Linker Flags' contains -ObjC and all the pods frameworks.
7. Iv deleted the pods project and podfile.lock and tried pod install again.

I'm also not on the Xcode 7 beta yet if that makes any difference?

Thanks,
Liam.

**Comment by Blackjacx** [comment]
I have the same issue in Xcode Version 6.4 (6E35b). I use a Xcode workspace containing the static library ("<APP_NAME>common") plus the app project (<APP_NAME>) itself. The podifle looks like this:

```
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

workspace '<APP_NAME>.xcworkspace'

xcodeproj '<APP_NAME>/<APP_NAME>.xcodeproj'
xcodeproj '<APP_NAME>-iOS-SDK/<APP_NAME>-iOS-SDK.xcodeproj'
xcodeproj '<APP_NAME>Common/<APP_NAME>Common.xcodeproj'

# <APP_NAME>

target '<APP_NAME>' do

  xcodeproj '<APP_NAME>/<APP_NAME>.xcodeproj'

  pod 'Appirater', '~> 2.0'
  pod 'Bugsnag', '~> 4.0'
  pod 'Facebook-iOS-SDK', '~> 3.20'
  pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
  pod 'GoogleConversionTracking', '~> 3.1'
  pod 'TPKeyboardAvoiding', '~> 1.2'
  pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git'

end

target '<APP_NAME>Tests', :exclusive => true do

    xcodeproj '<APP_NAME>/<APP_NAME>.xcodeproj'

    pod 'KIF', '~> 3.0', :configurations => ['Debug']

end

# <APP_NAME> SDK

target '<APP_NAME>-iOS-SDK' do

    xcodeproj '<APP_NAME>-iOS-SDK/<APP_NAME>-iOS-SDK.xcodeproj'

end


# <APP_NAME> common

target '<APP_NAME>Common' do

  xcodeproj '<APP_NAME>Common/<APP_NAME>Common.xcodeproj'

  pod 'AFNetworking', '~> 2.5'
  pod 'CocoaLumberjack', '~> 2.0.0'

end

target '<APP_NAME>CommonTests' do

    xcodeproj '<APP_NAME>Common/<APP_NAME>Common.xcodeproj'

    pod 'OHHTTPStubs', '~> 3.1', :configurations => ['Debug']

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts target.name
    end

    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-<APP_NAME>/Pods-<APP_NAME>-acknowledgements.plist', '<APP_NAME>/<APP_NAME>/Resources/Settings.bundle/Pods-<APP_NAME>-acknowledgements.plist', :remove_destination => true)
    FileUtils.cp_r('Pods/Target Support Files/Pods-<APP_NAME>Common/Pods-<APP_NAME>Common-acknowledgements.plist', '<APP_NAME>/<APP_NAME>/Resources/Settings.bundle/Pods-<APP_NAME>Common-acknowledgements.plist', :remove_destination => true)
end
```
"<APP_NAME>common" is set as dependency of the "<APP_NAME>" in the Xcode project. 

For some reason it is now necessary to link the libraries (AFNetworking and CocoaLumberjack) to the main app project too. But Cocoapods does not include these linker flags in the xcconfig file for the app project nor does it link the static lib against the app project.

**Comment by neonichu** [comment]
Have you both been using Xcode < 6 before? The behaviour definitely changed in that version regarding static libraries. In general, it might make more sense to use <https://github.com/CocoaPods/cocoapods-packager> to build static frameworks.

**Comment by liamogierussell** [comment]
No I was successfully using Xcode 6.3.1 with cocoapods 0.37.2. I only mentioned my Xcode version as I thought 0.38.2 might only work for Xcode 7 or something like that. 

And I was looking into cocoapods packager recently and am I right that that hasn't been updated for 0.38.2 yet? I also had a number of issues trying to use cocoapods packager (I could never get the podspec right) so I handled building the static framework and symbol prefixing myself.

**Comment by Blackjacx** [comment]
I was on Xcode 6.4 before too. Can you please post more information what exactly changed in xcode regarding static libraries? Maybe you have some links and we can solve the issue with that.

**Comment by liamogierussell** [comment]
Mine works fine on Xcode 6.3.1 if i just downgrade to 0.37.2 (as a temporary solution) so nothing has changed for me in terms of Xcode. Iv noticed a couple of changes to the pods project i.e the removing of the environment and umbrella files so I would assume it is a change similar to that in the pods project that would be causing the issue as opposed to Xcode.

**Comment by samurai00** [comment]
I got the same error on Xcode 6.4 and CocoaPods 0.38.2 with a totally new empty project.
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PingppInternal", referenced from:
      l_OBJC_$_CATEGORY_PingppInternal_$_Alipay in libpingpp+alipay.a(PingppInternal+Alipay.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Bfb in libpingpp+bfb.a(PingppInternal+Bfb.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Up in libpingpp+up.a(PingppInternal+Up.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Wx in libpingpp+wx.a(PingppInternal+Wx.o)
  "_OBJC_CLASS_$_PingppUtil", referenced from:
      objc-class-ref in libpingpp+alipay.a(PingppInternal+Alipay.o)
      objc-class-ref in libpingpp+bfb.a(PingppViewController.o)
      objc-class-ref in libpingpp+bfb.a(PingppInternal+Bfb.o)
      objc-class-ref in libpingpp+up.a(PingppInternal+Up.o)
      objc-class-ref in libpingpp+wx.a(PingppInternal+Wx.o)
  "_PingppLocalizedString", referenced from:
      -[PingppInternal(Alipay) alipayResult:] in libpingpp+alipay.a(PingppInternal+Alipay.o)
      -[PingppInternal(Bfb) channelBfb:withViewController:] in libpingpp+bfb.a(PingppInternal+Bfb.o)
      ___53-[PingppInternal(Bfb) channelBfb:withViewController:]_block_invoke103 in libpingpp+bfb.a(PingppInternal+Bfb.o)
      -[PingppInternal(Up) channelUpmp:withViewController:] in libpingpp+up.a(PingppInternal+Up.o)
      -[PingppInternal(Wx) onResp:] in libpingpp+wx.a(PingppInternal+Wx.o)
ld: symbol(s) not found for architecture arm64
```
Podfile:
```
platform :ios, "7.0"
pod "Pingpp", "~> 2.1.0"
pod "AFNetworking"
```

How to fix it?

**Comment by samurai00** [comment]
But it works fine with this Podfile:
```
platform :ios, '7.0'
pod "Pingpp/Alipay", "~> 2.1.0"
pod "Pingpp/Wx", "~> 2.1.0"
pod "Pingpp/UnionPay", "~> 2.1.0"
pod "AFNetworking"
```
The difference
succeded:
![succeded](https://cloud.githubusercontent.com/assets/685874/9107308/e150bd76-3c58-11e5-9506-53c66a373e4c.png)
failed:
![failed](https://cloud.githubusercontent.com/assets/685874/9107309/e17c95cc-3c58-11e5-972a-b8ceb9c20a93.png)

**Comment by Blackjacx** [comment]
You selected only subspecs of Pingpp or what did you change?

**Comment by samurai00** [comment]
No other changes.
Subspecs depends on Pingpp/Core.

**Comment by firstim** [comment]
We have same issue as @liamogierussell once upgrade to 0.38.2 from 0.37.1, any update?

**Comment by abillingsley** [comment]
We are also experiencing the same issue when upgrading to 0.38.2.

**Comment by pbradleyamcs** [comment]
We are also receiving these errors.  Has anyone found a solution or workaround?

**Comment by firstim** [comment]
Found out that `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)`  is removed (since cocoapods 0.38.2) in target's `.xconfig` file, like `Pods.debug.xcconfig`; As result dependencies are not included in a static library target's product.

**Comment by Blackjacx** [comment]
I can confirm this and this is exactly our main problem :-(

**Comment by segiddins** [comment]
@firstim @Blackjacx CocoaPods is not meant to integrate pods into new libraries, but rather into app targets. If you're looking to build a library, we only support making that library a pod itself.

**Comment by Blackjacx** [comment]
But Pods support spec dependencies. Isn't that exactly the integration of POD dependencies in PODS? This is the main purpose of package managers. Resolving Dependencies.

**Comment by segiddins** [comment]
Yes, it is? I'm unsure exactly what it is you're trying to say

**Comment by BruceRick** [comment]
What about a scenario like this: 

Podfile -
```
platform :ios, 7.0

inhibit_all_warnings!

xcodeproj 'MyProject'

link_with [ 'MyProject' ]

pod 'somepod1'
pod 'somepod2etcetc'

target :MyProjectSimulator, :exclusive => true do
  pod 'SomeCardReader' // this has some import checks based on whats imported in PaymentProcessor
  pod 'PaymentProcessor/Simulator'
end

target :MyProjectDevice, :exclusive => true do
  pod 'SomeCardReader' // this has some import checks based on whats imported in PaymentProcessor
  pod 'PaymentProcessor/Device'
end
```

You've also got 3 separate configurations of Debug/AdHoc/Release. Previously with 0.37, you could use the static libraries method to manage the different targets for running on the simulator or on the device. We'd create empty library targets and link the libraries to the configurations in the project file, eg.  

```
"OTHER_LDFLAGS[sdk=iphoneos*]" = (
					"-MyProjectDevice",
					"..."
				);

"OTHER_LDFLAGS[sdk=iphonesimulator*]" = (
					"-MyProjectSimulator",
					"..."
				);
```

What would be the best way to handle this scenario under 0.38?

**Comment by neonichu** [comment]
@samurai00 I think your case is a different story, could you please open a new issue for it, otherwise this thread will be very convoluted.

**Comment by neonichu** [comment]
We reverted some behaviour regarding static libraries in 0.38.x, see #3677 — this was needed because the previous fix was breaking more scenarios than it fixed. Basically, changes in libtool since Xcode 6 make this an either/or, we can't support all static library cases (see the linked PR and the issues it references for the whole story).

**Comment by evgeniyd** [comment]
I've just come up with this case:

We have a private pod for our internal needs. We tend to import it as a dependency into our other static frameworks. Obviously, we would not require the users of our libraries to install our private pod to work with our libraries. 

Because CocoaPods v1.2.0 does not generate `.xcconfig` with `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)` the dependency is not included into our library binary.

Am I missing something?
