### ISSUE TITLE
fails to links due to unknown symbols on >= 1.6.0.rc.1, success on .beta.2

### ISSUE THREAD

**Issue by AVVS** [CocoaPods/CocoaPods#8493]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

cocoapods >= 1.6.0.rc.1 fails to link Texture

## What did you do?

When I've built the project, I have received the following output:

```
Ld /Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/Texture/AsyncDisplayKit.framework/AsyncDisplayKit normal x86_64 (in target: Texture)
    cd /Users/vitaly/projects/radiofx-ios-v4.0/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -L/Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/Texture -F/Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/Texture -F/Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/PINCache -F/Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/PINOperation -F/Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/PINRemoteImage -filelist /Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Texture.build/Objects-normal/x86_64/AsyncDisplayKit.LinkFileList -install_name @rpath/AsyncDisplayKit.framework/AsyncDisplayKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Texture.build/Objects-normal/x86_64/AsyncDisplayKit_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lc++ -framework Foundation -framework PINRemoteImage -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Texture.build/Objects-normal/x86_64/AsyncDisplayKit_dependency_info.dat -o /Users/vitaly/projects/radiofx-ios-v4.0/DerivedData/RadioFx/Build/Products/Debug-iphonesimulator/Texture/AsyncDisplayKit.framework/AsyncDisplayKit

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in ASMultiplexImageNode.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Same thing works on 1.6.0.beta.2
Tried to build on xcode 10.1 and 10.2 beta - same result

**Comment by pcki11** [comment]
Happens on the release 1.6.0 as well:
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in libAppboyKitLibrary.a(ABKDevice.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am using `use_frameworks!` if that matters, Xcode 10.1

**Comment by dnkoutso** [comment]
Can you please paste the 1.6.0 xcconfig?

**Comment by pcki11** [comment]
```
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/Alamofire" "${PODS_CONFIGURATION_BUILD_DIR}/Appboy-iOS-SDK" "${PODS_CONFIGURATION_BUILD_DIR}/AssetsPickerViewController" "${PODS_CONFIGURATION_BUILD_DIR}/Bolts" "${PODS_CONFIGURATION_BUILD_DIR}/Braintree" "${PODS_CONFIGURATION_BUILD_DIR}/Branch" "${PODS_CONFIGURATION_BUILD_DIR}/BugfenderSDK" "${PODS_CONFIGURATION_BUILD_DIR}/CAAnimationBlocks" "${PODS_CONFIGURATION_BUILD_DIR}/Device" "${PODS_CONFIGURATION_BUILD_DIR}/Dimmer" "${PODS_CONFIGURATION_BUILD_DIR}/FBSDKCoreKit" "${PODS_CONFIGURATION_BUILD_DIR}/FBSDKLoginKit" "${PODS_CONFIGURATION_BUILD_DIR}/FBSDKShareKit" "${PODS_CONFIGURATION_BUILD_DIR}/FLAnimatedImage" "${PODS_CONFIGURATION_BUILD_DIR}/FadeView" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCore" "${PODS_CONFIGURATION_BUILD_DIR}/GTMOAuth2" "${PODS_CONFIGURATION_BUILD_DIR}/GTMSessionFetcher" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleAPIClientForREST" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleToolboxForMac" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleUtilities" "${PODS_CONFIGURATION_BUILD_DIR}/LMAlertView" "${PODS_CONFIGURATION_BUILD_DIR}/MDHTMLLabel" "${PODS_CONFIGURATION_BUILD_DIR}/ObjcExceptionBridging" "${PODS_CONFIGURATION_BUILD_DIR}/Protobuf" "${PODS_CONFIGURATION_BUILD_DIR}/PureLayout" "${PODS_CONFIGURATION_BUILD_DIR}/RBBAnimation" "${PODS_CONFIGURATION_BUILD_DIR}/SAConfettiView" "${PODS_CONFIGURATION_BUILD_DIR}/SDWebImage" "${PODS_CONFIGURATION_BUILD_DIR}/SkyFloatingLabelTextField" "${PODS_CONFIGURATION_BUILD_DIR}/SwiftARGB" "${PODS_CONFIGURATION_BUILD_DIR}/SwiftyDropbox" "${PODS_CONFIGURATION_BUILD_DIR}/SwiftyJSON" "${PODS_CONFIGURATION_BUILD_DIR}/TGPControls" "${PODS_CONFIGURATION_BUILD_DIR}/TTGTagCollectionView" "${PODS_CONFIGURATION_BUILD_DIR}/TinyLog" "${PODS_CONFIGURATION_BUILD_DIR}/UIViewKVO" "${PODS_CONFIGURATION_BUILD_DIR}/Whisper" "${PODS_CONFIGURATION_BUILD_DIR}/XCGLogger" "${PODS_CONFIGURATION_BUILD_DIR}/nanopb" "${PODS_ROOT}/Crashlytics/iOS" "${PODS_ROOT}/Fabric/iOS" "${PODS_ROOT}/FirebaseABTesting/Frameworks" "${PODS_ROOT}/FirebaseAnalytics/Frameworks" "${PODS_ROOT}/FirebaseInstanceID/Frameworks" "${PODS_ROOT}/FirebaseRemoteConfig/Frameworks" "${PODS_ROOT}/GoogleAppMeasurement/Frameworks" "${PODS_ROOT}/GoogleMaps/Base/Frameworks" "${PODS_ROOT}/GoogleMaps/Maps/Frameworks" "${PODS_ROOT}/GooglePlacePicker/Frameworks" "${PODS_ROOT}/GooglePlaces/Frameworks" "${PODS_ROOT}/GoogleSignIn/Frameworks" "${PODS_ROOT}/GoogleSymbolUtilities/Frameworks/frameworks" "${PODS_ROOT}/GoogleTagManager/Frameworks" "${PODS_ROOT}/GoogleUtilitiesLegacy/Frameworks/frameworks" "${PODS_ROOT}/OneSignal/iOS_SDK/Framework" "${PODS_ROOT}/PhotoEditorSDK/PhotoEditorSDK"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) GTM_OAUTH2_USE_FRAMEWORK_IMPORTS=1 $(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 $(inherited) PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/Alamofire/Alamofire.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Appboy-iOS-SDK/Appboy_iOS_SDK.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/AssetsPickerViewController/AssetsPickerViewController.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Bolts/Bolts.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Braintree/Braintree.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Branch/Branch.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/BugfenderSDK/BugfenderSDK.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/CAAnimationBlocks/CAAnimationBlocks.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Device/Device.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Dimmer/Dimmer.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FBSDKCoreKit/FBSDKCoreKit.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FBSDKLoginKit/FBSDKLoginKit.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FBSDKShareKit/FBSDKShareKit.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FLAnimatedImage/FLAnimatedImage.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FadeView/FadeView.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/FirebaseCore/FirebaseCore.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GTMOAuth2/GTMOAuth2.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GTMSessionFetcher/GTMSessionFetcher.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleAPIClientForREST/GoogleAPIClientForREST.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleToolboxForMac/GoogleToolboxForMac.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/GoogleUtilities/GoogleUtilities.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/LMAlertView/LMAlertView.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/MDHTMLLabel/MDHTMLLabel.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/ObjcExceptionBridging/ObjcExceptionBridging.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Protobuf/Protobuf.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/PureLayout/PureLayout.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/RBBAnimation/RBBAnimation.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/SAConfettiView/SAConfettiView.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/SDWebImage/SDWebImage.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/SkyFloatingLabelTextField/SkyFloatingLabelTextField.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/SwiftARGB/SwiftARGB.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/SwiftyDropbox/SwiftyDropbox.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/SwiftyJSON/SwiftyJSON.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/TGPControls/TGPControls.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/TTGTagCollectionView/TTGTagCollectionView.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/TinyLog/TinyLog.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/UIViewKVO/UIViewKVO.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/Whisper/Whisper.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/XCGLogger/XCGLogger.framework/Headers" "${PODS_CONFIGURATION_BUILD_DIR}/nanopb/nanopb.framework/Headers" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/CardIO" "${PODS_ROOT}/Headers/Public/Firebase" "${PODS_ROOT}/Headers/Public/GoogleAnalytics" $(inherited) ${PODS_ROOT}/Firebase/CoreOnly/Sources
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Appboy-iOS-SDK/AppboyKit" "${PODS_ROOT}/Braintree/BraintreePayPal/PayPalDataCollector/Risk" "${PODS_ROOT}/BugfenderSDK" "${PODS_ROOT}/CardIO/CardIO" "${PODS_ROOT}/GoogleAnalytics/Libraries"
OTHER_LDFLAGS = $(inherited) -ObjC -l"CardIO" -l"GoogleAnalytics" -l"c++" -l"opencv_core" -l"opencv_imgproc" -l"sqlite3" -l"z" -framework "AVFoundation" -framework "Accelerate" -framework "AdSupport" -framework "AddressBook" -framework "Alamofire" -framework "Appboy_iOS_SDK" -framework "AssetsPickerViewController" -framework "AudioToolbox" -framework "Bolts" -framework "Braintree" -framework "Branch" -framework "BugfenderSDK" -framework "CAAnimationBlocks" -framework "CFNetwork" -framework "CoreData" -framework "CoreGraphics" -framework "CoreImage" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreText" -framework "CoreVideo" -framework "Crashlytics" -framework "Device" -framework "Dimmer" -framework "FBSDKCoreKit" -framework "FBSDKLoginKit" -framework "FBSDKShareKit" -framework "FIRAnalyticsConnector" -framework "FLAnimatedImage" -framework "Fabric" -framework "FadeView" -framework "FirebaseABTesting" -framework "FirebaseAnalytics" -framework "FirebaseCore" -framework "FirebaseCoreDiagnostics" -framework "FirebaseInstanceID" -framework "FirebaseRemoteConfig" -framework "Foundation" -framework "GLKit" -framework "GTMOAuth2" -framework "GTMSessionFetcher" -framework "GoogleAPIClientForREST" -framework "GoogleAppMeasurement" -framework "GoogleMaps" -framework "GoogleMapsBase" -framework "GoogleMapsCore" -framework "GooglePlacePicker" -framework "GooglePlaces" -framework "GoogleSignIn" -framework "GoogleSymbolUtilities" -framework "GoogleTagManager" -framework "GoogleToolboxForMac" -framework "GoogleUtilities" -framework "GoogleUtilitiesLegacy" -framework "ImageIO" -framework "JavaScriptCore" -framework "LMAlertView" -framework "MDHTMLLabel" -framework "MessageUI" -framework "MobileCoreServices" -framework "ObjcExceptionBridging" -framework "OneSignal" -framework "OpenGLES" -framework "PassKit" -framework "PhotoEditorSDK" -framework "Photos" -framework "Protobuf" -framework "PureLayout" -framework "QuartzCore" -framework "RBBAnimation" -framework "SAConfettiView" -framework "SDWebImage" -framework "SafariServices" -framework "Security" -framework "SkyFloatingLabelTextField" -framework "StoreKit" -framework "SwiftARGB" -framework "SwiftyDropbox" -framework "SwiftyJSON" -framework "SystemConfiguration" -framework "TGPControls" -framework "TTGTagCollectionView" -framework "TinyLog" -framework "UIKit" -framework "UIViewKVO" -framework "WebKit" -framework "Whisper" -framework "XCGLogger" -framework "nanopb" -weak_framework "Accounts" -weak_framework "AdSupport" -weak_framework "AudioToolbox" -weak_framework "Contacts" -weak_framework "CoreGraphics" -weak_framework "CoreLocation" -weak_framework "CoreTelephony" -weak_framework "Foundation" -weak_framework "QuartzCore" -weak_framework "SafariServices" -weak_framework "Security" -weak_framework "Social" -weak_framework "UIKit" -weak_framework "UserNotifications"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
USER_HEADER_SEARCH_PATHS = $(inherited) $(SRCROOT)/FLAnimatedImage/FLAnimatedImage
```

**Comment by dnkoutso** [comment]
@pcki11 I'd love for you to upload a sample app. I just tried it locally with 
```ruby
target 'SampleApp' do
  pod 'Appboy-iOS-SDK'
end
```

And it worked OK for me. I also do not see double `-framework 'CoreTelephony'` and `-weak_framework 'CoreTelephony'` in the Pods-SampleApp.debug.xcconfig.

**Comment by dnkoutso** [comment]
Hold on I can reproduce with `use_frameworks!` however I still can't see the duplication.

**Comment by pcki11** [comment]
As far as I see there is no duplication, the issue is different:
After I run `pod install` I see this difference:
 - 1.5.3: OTHER_LDFLAGS contains `-framework "CoreTelephony"`
 - 1.6.0: OTHER_LDFLAGS contains `-weak_framework "CoreTelephony"`

Which (supposedly) leads to missing `-weak_framework "CoreTelephony"` from the `Other linker flags` property in build settings of the affected pod.

**Comment by skydivedan** [comment]
Appboy is a "vendored library" pod. I think this may be the same (or very related) as https://github.com/CocoaPods/CocoaPods/issues/8454

**Comment by AVVS** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/a/3/e/Texture/2.7/Texture.podspec.json

For me this happens with this pod if thats of any help and I also do “use_frameworks!”

**Comment by dnkoutso** [comment]
Found the issue.

**Comment by dnkoutso** [comment]
Fix is out. We will be doing a 1.6.1 but not yet until we wait a bit to see if new issues arise.

**Comment by gsbernstein** [comment]
Bump. This is keeping us on 1.5.3, please consider releasing the fix.

**Comment by mathaeus** [comment]
@dnkoutso any update on the release of `1.6.1`? When can we expect it? Thanks!

**Comment by TYRONEMICHAEL** [comment]
Can confirm this works when we downgraded to 1.5.3. Took us a while to figure this out, because it was failing on our CI where the team all had previous versions of cocoa pods running locally.

**Comment by shevakuilin** [comment]
I have the same problem as @AVVS 
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in ASMultiplexImageNode.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by dnkoutso** [comment]
Will try to release 1.6.1 this week.

**Comment by sch1111878** [comment]
$ pod env

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/Cyandnow/.rvm/rubies/ruby-2.6.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e78bf249399e543927634eeb4df68c3f7506f108
               YuTong - git@dev.yutong.com:iOS_librarys/Specs.git @ 82646375bb661517500cacd4fa585834087d5b2a
```

### Installation Source

```
Executable Path: /Users/Cyandnow/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@dev.xxx.com:iOS_librarys/Specs.git'

target 'YTVControl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for YTVControl
  pod 'YTBaseModule', '= 2.2.0'
  pod 'YTPushModule', '= 1.2.0'       
  pod 'SSZipArchive', '= 2.1.3'
  pod 'Internationalization', '= 0.0.2'
  pod 'YYModel', '= 1.0.4'
  pod 'lottie-ios', '= 2.5.0'
  pod 'BaiduMapKit_Subspec/Utils', '= 4.1.1'
  pod 'UMCCommon', '= 1.5.2'                    
  pod 'UMCSecurityPlugins', '= 1.0.6'
  pod 'UMCShare/UI', '= 6.9.4'
  pod 'UMCShare/Social/WeChat', '= 6.9.4'
  pod 'Bugly', '= 2.5.0'            
  pod 'YTBluetoothModule', '= 0.2.1'
#  pod 'MLeaksFinder'
  # Swift
  pod 'Moya/RxSwift', '= 11.0.2'     
  pod 'Moya-ObjectMapper/RxSwift', '= 2.7' 
  pod 'SnapKit', '= 4.0.0'           
  pod 'RxCocoa', '= 4.2.0'           
  pod 'Charts', '= 3.1.1'           
  pod 'SwiftDate', '= 5.0.4'         
  pod 'URLNavigator', '= 2.0.6'      
  pod 'Kingfisher', '= 4.9.0'       
  pod 'Toaster', '= 2.1.1'           
end
```

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_YTBase64", referenced from:
      objc-class-ref in YTPushDataManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

1.5.3 no problem

**Comment by dcorbatta** [comment]
I've a similar problem, the library search path is not copied to the Test Target

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories :  master - https://github.com/CocoaPods/Specs.git @ b73c1339aa778a60bf62c29857bf71d3603ffcb2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenSSLTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'OpenSSL-Universal'

  target 'OpenSSLTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
