### ISSUE TITLE
Broken import (header file not found)

### ISSUE THREAD

**Issue by djbe** [CocoaPods/CocoaPods#5168]
:rainbow:

* [x] I've searched for similar issues, and couldn't find the issue.

# Report

## What did you do?

Run `pod install` and also tried `pod update`

## What did you expected to happen?

Install all pod dependencies correctly.

## What happened instead?

I get the error:
`.../Classes/Helpers/SomePrivateLibFile.m:20:9: 'Fabric/Fabric.h' file not found`
for this include:
`#import <Fabric/Fabric.h>`

This is an import in a private pod that uses Fabric. This used to work with 1.0.0.beta4 (last I tested), but doesn't with beta8. The issue is that the compiler uses this command (abbreviated):
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c ... -I/Users/.../MyProject/Pods/Headers/Public/Fabric ...`

The problem is that in beta8, compared to beta4, the Fabric headers are not copied to the `Pods/Headers/Public/Fabric` folder. In fact, my whole `Pods/Headers` folder is empty. If I manually copy the headers from the (fake) Fabric framework into the correct location, everything works fine.

I think #5146 broke this, not sure though.

## Podfile

```ruby
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!
source 'git@bitbucket.org:myprivatelib/myprivatelib-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Vengo' do
	pod 'MyPrivateLib'
end

# fix for frameworks
pre_install do |installer|
	def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do | installer |
	# fix for duplicate symbols
	installer.pods_project.targets.each do |target|
		if (target.name.start_with?('Pods-'))
			target.build_configurations.each do |config|
				config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
				xcconfig_path = config.base_configuration_reference.real_path
				build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]
				build_settings['OTHER_LDFLAGS'][' -framework "Crashlytics"'] = ''
				build_settings['OTHER_LDFLAGS'][' -framework "Fabric"'] = ''
				File.open(xcconfig_path, "w") do |file|
					build_settings.each do |key,value|
						file.puts "#{key} = #{value}"
					end
				end
			end
		end
	end
end
```

**Comment by djbe** [comment]
Instead of manually copying the files, I was able to (temporarily) fix it using this post_install code:
```ruby
	# copy fabric and crashlytics headers (cocoapods beta8 fix)
	require 'fileutils'
	FileUtils.mkdir_p('Pods/Headers/Public/Fabric')
	FileUtils.cp_r(Dir['Pods/Fabric/iOS/Fabric.framework/Headers/*.h'], 'Pods/Headers/Public/Fabric', :remove_destination => true)
	FileUtils.mkdir_p('Pods/Headers/Public/Crashlytics')
	FileUtils.cp_r(Dir['Pods/Crashlytics/iOS/Crashlytics.framework/Headers/*.h'], 'Pods/Headers/Public/Crashlytics', :remove_destination => true)
```

**Comment by neonichu** [comment]
Well, you're intentionally using CocoaPods in an unsupported configuration by monkey patching a sanity check out. That your specific `post_install` hook worked in a previous beta was just a coincidence. 

Framework search paths seem to be set up correctly for the app target, so I think #5146 is working fine.

**Comment by djbe** [comment]
Actually the hooks still work, it's Cocoapods' behaviour that changed in the latest beta so it doesn't symlink the headers anymore. I understand this whole configuration is a bit bizarre, all because Fabric & Crashlytics are (still) not dynamic frameworks.

Should I assume the current behaviour is correct and will stay as it is? If so I'll just take it into account and close this issue.

**Comment by djbe** [comment]
Closing this as I assume the current behaviour is correct and will stay so.
