### ISSUE TITLE
"Undefined Symbol" Compier Error with Static Library Pod With use_frameworks!

### ISSUE THREAD

**Issue by Wenzhi** [CocoaPods/CocoaPods#3870]
I tried to install Appboy-iOS-SDK in my project with `use_frameworks`, it used to work in Cocoapods 0.37.2, but now break on 0.38.0. The Compiler error is 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Appboy", referenced from:
      __TMaCSo6Appboy in ViewController.o
      __TMaCSo6Appboy in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I checked the liAppboyKitLibrary.a by `lipo -info` and it returns:
`Architectures in the fat file: libAppboyKitLibrary.a are: armv7 armv7s i386 x86_64 arm64`, so this isn't the library not built for the architecture.

I also found that in the project's build folder, the dynamic framework generated by Cocoapods is different: The file `Appboy_iOS_SDK.framework/Appboy_iOS_SDK` is only 12KB, which was 1.3MB in Cocoapods 0.37.2. 

I'm using Xcode 6.4. I created a sample project to reproduce it [here](https://github.com/Wenzhi/CocoapodsTest). The Podfile is as simple as:
```
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'Appboy-iOS-SDK'
```

This issue might relate to https://github.com/CocoaPods/CocoaPods/issues/3773.

**Comment by neonichu** [comment]
This should be fixed by  #3832

**Comment by Wenzhi** [comment]
Hi,

I just tested this again but with Xcode 7. It seems the same issue still exist.

The issue can be fixed by putting following post_install hook in Podfile:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Appboy-iOS-SDK"
        config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
      end
    end
  end
end
```

**Comment by keith** [comment]
We still have this problem as well and are working around it the same way.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by gautamjain987** [comment]
I would say it's still relevant. I have the latest cocoapods. I just got here and the post install hook suggested by @Wenzhi worked for my library as well - MoEngage-iOS-SDK. Thanks Wenzhi 👍 . Without that, I was getting a linker error. 
Xcode doesn't recognise my SDK as a module without that post hook. Not reopening it and leaving it for you to decide @neonichu
