### ISSUE TITLE
Update 0.38.2, link error

### ISSUE THREAD

**Issue by chaoskyme** [CocoaPods/CocoaPods#3921]
When I update CocoaPods to 0.38.2, I have some `duplicate symbol _OBJC_CLASS` and `duplicate symbol _OBJC_METACLASS.`

**Comment by segiddins** [comment]
@chaoskyme can you please provide some more detail on the issue you're experiencing, ideally by sharing a project that reproduces it? Thanks!
