### ISSUE TITLE
Binary Dependency issue with Xcode 12 GM

### ISSUE THREAD

**Issue by tmspzz** [CocoaPods/CocoaPods#10063]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod install`

## What did you expect to happen?

 Install all pod dependencies correctly.

## What happened instead?

Cocoapods installed binary dependencies but they are unusable from Xcode 12 GM

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/tmpz/.rvm/rubies/ruby-2.6.3/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/tmpz/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

workspace 'GGTemplates.xcworkspace'
project 'GGTemplates'
project 'GGEditor/GGEditor'

def firebase
  # https://firebase.google.com/
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'
end

def facebook
  # https://github.com/facebook/facebook-ios-sdk
  pod 'FBSDKCoreKit'
end

def tagged
  # https://github.com/pointfreeco/swift-tagged
  pod 'Tagged', '~> 0.5'
end

def viewer
  # https://github.com/DaveWoodCom/XCGLogger
  pod 'XCGLogger', '~> 7.0.0'
  pod 'XCGLogger/UserInfoHelpers', '~> 7.0.0'
  
  firebase
  facebook

  # https://cocoapods.org/pods/IQKeyboardManagerSwift
  pod 'IQKeyboardManagerSwift'

  # https://github.com/JonasGessner/JGProgressHUD
  pod 'JGProgressHUD'
  
  # https://github.com/mac-cain13/R.swift
  pod 'R.swift'

  # https://github.com/SDWebImage/SDWebImage
  pod "SDWebImage"

  # https://github.com/Alamofire/Alamofire
  pod "Alamofire", '~> 5.0.0-rc.3'

  # https://github.com/davidstump/SwiftPhoenixClient
  pod "SwiftPhoenixClient"

  # https://github.com/CombineCommunity/CombineExt
  pod "CombineExt"

  # https://developers.giphy.com/docs/sdk/#ios
  pod "Giphy"

  pod 'LTMorphingLabel'

  tagged

end

def templates
end

def shared
  pod 'SwiftLint'
  # https://instabug.com/
  pod 'Instabug'
end

def editor
  pod 'SQLite.swift', '~> 0.12.0'
  tagged
end

target 'GGTemplates' do
  project 'GGTemplates'
  use_frameworks!
  viewer
  templates
  editor
  shared
end

target 'GGTemplatesTests' do
  project 'GGTemplates'
  use_frameworks!
  viewer
  templates
  editor
  shared
end

target 'GGTemplatesUITests' do
  project 'GGTemplates'
  inherit! :search_paths
end

target 'GGEditor' do
  project 'GGEditor/GGEditor'
  use_frameworks!
  editor
end

target 'GGEditorTests' do
  project 'GGEditor/GGEditor'
  use_frameworks!
  editor
end
```

## Project that demonstrates the issue

See https://github.com/Giphy/giphy-ios-sdk-ui-example/issues/96

**Comment by dnkoutso** [comment]
What does "unusable" mean?

**Comment by tmspzz** [comment]
@dnkoutso 

Results may vary but for us with deployment target >= 13.4 this is the outcome

```
Undefined symbols for architecture x86_64:
  "_swiftoverride_class_getSuperclass(swift::TargetMetadata<swift::InProcess> const*)", referenced from:
      swift::swift50override_conformsToProtocol(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, swift::TargetWitnessTable<swift::InProcess> const* (*)(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*)) in libswiftCompatibility50.a(ProtocolConformance.cpp.o)
  "swift::swift51override_conformsToSwiftProtocol(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, llvm::StringRef, swift::TargetProtocolConformanceDescriptor<swift::InProcess> const* (*)(swift::TargetMetadata<swift::InProcess> const*, swift::TargetProtocolDescriptor<swift::InProcess> const*, llvm::StringRef))", referenced from:
      _Swift50Overrides in libswiftCompatibility50.a(Overrides.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Lowering deployment target seems to work. Manually download the binaries or downloading the via Carthage also seems to work without changing the deployment target.

**Comment by dnkoutso** [comment]
Interesting, thank you. I am not on a place with fast internet today to download Xcode 12 GM so I will be able to do so tomorrow.

**Comment by dnkoutso** [comment]
Can certainly reproduce with Xcode 12 GM, but so far no leads on as to why...

**Comment by harishios** [comment]
@dnkoutso - Do you have any solution for this?

**Comment by zhangjianshuai** [comment]
have you tried to add an empty swift file on your project?
When you add an empty swift file, XCode will ask you "Create Bridging Header".

It will include to the Header Search Path on your build settings:

`$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)`

**Comment by Donhv** [comment]
Any solutions for this?

**Comment by vietstone-ng** [comment]
hi, I encounter this problem when upgrading minimum iOS version from 13.3 to 13.4
