### ISSUE TITLE
Build Fails with Linker Issue Only on Xcode 6.4 (Xcode 7 works)

### ISSUE THREAD

**Issue by benmarten** [CocoaPods/CocoaPods#5121]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
One of our pods libraries fails to build with Xcode 6.4, it works with 7.3 though.

The error is:
```
[...]
duplicate symbol _llvm.embedded.module in:
    /Users/Ben/dev/leanplum/Test/Pods/Leanplum-iOS-SDK/Leanplum.framework/Leanplum(LPInterfaceProperty.o)
    /Users/Ben/dev/leanplum/Test/Pods/Leanplum-iOS-SDK/Leanplum.framework/Leanplum(LPNewsfeed.o)
ld: 84 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## What did you do?

- Created a new single view iOS app with Xcode 6.4.
- `pod init`
- `vim Podfile`, insert line `pod 'LeanplumSegment', '~> 1.0.1'`
- `pod install`
- open xcworkspace with Xcode 6.4 --> build fails
- open xcworkspace with Xcode 7.3 --> build success

Sample repo: [https://github.com/benmarten/Leanplum-Segment-Test](https://github.com/benmarten/Leanplum-Segment-Test)

## What did you expected to happen?

The build should be successful with Xcode 7.3 and 6.4.

## What happened instead?

The build fails with Xcode 6.3.

## Podfile
```ruby
target 'Test' do
	pod 'LeanplumSegment', '~> 1.0.1'
end

target 'TestTests' do

end
```

**Comment by segiddins** [comment]
What version of CocoaPods are you using?

**Comment by segiddins** [comment]
Oh! My guess is that pod embeds something with bit code in it, which itself is incompatible with Xcode 6.4, nothing to do with CocoaPods.

**Comment by benmarten** [comment]
yes, thats it! with an older build without bit code in it it works, thx!
