### ISSUE TITLE
NoMethodError - undefined method `include?' for nil:NilClass when integrating / deintegrating with 1.0.0.rc.1

### ISSUE THREAD

**Issue by cargath** [CocoaPods/CocoaPods#5247]
### Command

```
/usr/local/bin/pod install --verbose
```

### Report

* What did you do?
I tried running "pod install".

* What did you expect to happen?
The pods to be installed and integrated with the project.

* What happened instead?
Installing succeeded including the creation of the Xcode workspace file, then the integration fails. btw, the same happens when running "pod deintegrate"

### Stack

```
   CocoaPods : 1.0.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 246-hmmh-cocoapods - ssh://80.228.246.200:29418/hmmh/cocoapods @ 34c446ee0a79f6ec0438d63d2e5150785bbac9d8
               hmmh - https://github.com/hmmh/iOSToolbox.git @ 04bef558088bda8defbb9ad03755e3a12a863fc3
               hmmh--hmmh-cocoapods.git - ssh://git.hmmh.de:29418//hmmh/cocoapods.git/ @ 34c446ee0a79f6ec0438d63d2e5150785bbac9d8
               hmmh-1 - https://github.com/hmmh/Specs.git @ 2cded57028dd2daa98eb9be7882143dc7c1512b3
               master - https://github.com/CocoaPods/Specs.git @ a8670db9bfcf30c5b4caf622c298d734d06e08b1
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.rc.1
cocoapods-plugins     : 1.0.0.rc.1
cocoapods-search      : 1.0.0.rc.1
cocoapods-stats       : 1.0.0.rc.1
cocoapods-trunk       : 1.0.0.rc.1
cocoapods-try         : 1.0.0.rc.1
```

### Podfile

The podfile is not relevant here. I tried running "pod install" with the exact same podfile on a new, clean project and it worked. I can't figure out the cause of this, but it worked with 1.0.0.beta.8.

### Error

```
NoMethodError - undefined method `include?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:57:in `block in deintegrate_shell_script_phase'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `deintegrate_shell_script_phase'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:22:in `block in deintegrate_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:21:in `deintegrate_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/user_project_integrator.rb:125:in `block (2 levels) in integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/user_project_integrator.rb:124:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/user_project_integrator.rb:124:in `block in integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/config.rb:39:in `with_changes'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/user_project_integrator.rb:119:in `integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:748:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:745:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:120:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.rc.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by segiddins** [comment]
This has already been fixed in cocoapods-deintegrate.
