### ISSUE TITLE
Linking issues installing vendored frameworks on v1.8.3

### ISSUE THREAD

**Issue by ryang1428** [CocoaPods/CocoaPods#9235]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Run `pod install`
- Attempt to run project 

## What did you expect to happen?

- The app built successfully to the simulator

## What happened instead?

- We are still getting this error with our vendored frameworks with v1.8.3. This issue was supposedly fixed in 1.8.0 (https://github.com/CocoaPods/CocoaPods/pull/9045), but we are still running into it. We cannot run our app with any cocoa pods version > 1.5.3.

Error we are seeing in Xcode:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CardIO", referenced from:
      objc-class-ref in AppCoordinator.o
      objc-class-ref in VoiceController.o
      objc-class-ref in CheckController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

We have 4 vendored frameworks. There still seems to be issues with them linking in newer cocoapods version. Again this is fine on 1.5.3 for us. 

We get the same result on Xcode 10 and 11.

- Heres the issue I was following for awhile thats got closed, but still happening https://github.com/CocoaPods/CocoaPods/issues/8519

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 9f8b4736b7c9ad9fd244e0961ec139f8c4b336f1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Will need a sample app here. Can you upload one?

**Comment by fancygeek** [comment]
I met this problem too~and downgrade to 1.6.1, everything is ok

**Comment by jes5199** [comment]
I'm seeing this too, in our app the main target correctly gets `OTHER_LDFLAGS` set with all of the frameworks, but all the targets that inherit from it are missing the vendored_frameworks (from the 'Firebase' pod)

**Comment by dnkoutso** [comment]
Still need a sample app here.
