### ISSUE TITLE
undefined method `root' for nil:NilClass with Xcode 8

### ISSUE THREAD

**Issue by ggo16** [CocoaPods/CocoaPods#5928]
🌈

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
> 
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).🌈
### Command

```
/Users/user_name/.rvm/rubies/ruby-2.2.0/bin/pod install --verbose
```
### Report
- What did you do?
  Run 'pod install --verbose'. I just updated my Macs to Sierra (10.12) and to Xcode 8. I tried with the latest release and release candidate (same problem), and updating Ruby (same problem). I also deleted all pod related files (podlock, pods folder in project, xcworkspace and files in /Library/Caches/CocoaPods/pods).
- What did you expect to happen?
  Pod to be updated.
- What happened instead?
  Encountered error.
### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/user_name/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3894314ef50b04598f1a26c597f6d2b5d07a6c20
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
target 'app'
pod 'Analytics'
pod 'APAddressBook'
pod 'AWSCognito', '~> 2.3.6'
pod 'AWSCore', '~> 2.3.6'
pod 'AWSS3', '~> 2.3.6'
pod 'Bolts'
pod 'Crashlytics'
pod 'Fabric'
pod 'Heap'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'PubNub'
pod 'Realm'
pod 'SDWebImage'
pod 'Segment-Flurry'
pod 'Segment-GoogleAnalytics'
pod 'Segment-Mixpanel'
pod 'ZXingObjC', '~> 3.0'
```
### Error

```
NoMethodError - undefined method `root' for nil:NilClass
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:160:in `root_spec'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:173:in `predownloaded?'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:313:in `each'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:111:in `install!'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/user_name/.rvm/rubies/ruby-2.2.0/bin/pod:23:in `load'
/Users/user_name/.rvm/rubies/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/user_name/.rvm/gems/ruby-2.2.0@global/bin/ruby_executable_hooks:15:in `<main>'
```
## Additional - verbose output before running into error

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-app`: (``)

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A APAddressBook
  A AWSCognito
  A AWSCore
  A AWSS3
  A Analytics
  A Bolts
  A Crashlytics
  A FBSDKCoreKit
  A FBSDKLoginKit
  A FBSDKShareKit
  A FBSDKTVOSKit
  A Fabric
  A Flurry-iOS-SDK
  A GoogleAnalytics
  A GoogleIDFASupport
  A Heap
  A Mixpanel
  A Parse
  A ParseFacebookUtilsV4
  A PubNub
  A Realm
  A SDWebImage
  A Segment-Flurry
  A Segment-GoogleAnalytics
  A Segment-Mixpanel
  A ZXingObjC
  A libPhoneNumber-iOS

Downloading dependencies

-> Installing APAddressBook (0.2.3)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/Alterplay/APAddressBook.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1h37sl5 --template=
>      --single-branch --depth 1 --branch 0.2.3
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1h37sl5'...
>      Note: checking out '8bf007797eb86fcd7546dd5e723f2ebe43835cf1'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying APAddressBook from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/APAddressBook/0.2.3-2a91b` to `Pods/APAddressBook`

-> Installing AWSCognito (2.3.6)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/aws/amazon-cognito-ios.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-i97vlq --template=
>      --single-branch --depth 1 --branch 2.3.6
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-i97vlq'...
>      Note: checking out '828cc43ec9e156e801ec877d4fa1b5989a67c464'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying AWSCognito from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/AWSCognito/2.3.6-af54f` to `Pods/AWSCognito`

-> Installing AWSCore (2.3.6)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/aws/aws-sdk-ios.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-vu25a6 --template= --single-branch
>      --depth 1 --branch 2.3.6
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-vu25a6'...
>      Note: checking out 'd234898f219f898aab2ac3f425111378ab067d82'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying AWSCore from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/AWSCore/2.3.6-917d8` to `Pods/AWSCore`

-> Installing AWSS3 (2.3.6)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/aws/aws-sdk-ios.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1sjaots --template= --single-branch
>      --depth 1 --branch 2.3.6
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1sjaots'...
>      Note: checking out 'd234898f219f898aab2ac3f425111378ab067d82'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying AWSS3 from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/AWSS3/2.3.6-1caaf` to `Pods/AWSS3`

-> Installing Analytics (3.5.0)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/segmentio/analytics-ios.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-mh1c8z --template=
>      --single-branch --depth 1 --branch 3.5.0
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-mh1c8z'...
>      Note: checking out '10e7a0604c9c2900de63b3d34f5744d02f4fc68c'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying Analytics from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/Analytics/3.5.0-79046` to `Pods/Analytics`

-> Installing Bolts (1.8.4)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/BoltsFramework/Bolts-ObjC.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1yg2j53 --template=
>      --single-branch --depth 1 --branch 1.8.4
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1yg2j53'...
>      Note: checking out 'e64deecb2f0e10ac0dbb71f522c7a5b9cafb0b4d'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying Bolts from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/Bolts/1.8.4-8a799` to `Pods/Bolts`

-> Installing Crashlytics (3.8.2)

> Http download
>    $ /usr/bin/curl -f -L -o /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/file.zip
>    https://kit-downloads.fabric.io/cocoapods/crashlytics/3.8.2/crashlytics.zip --create-dirs --netrc-optional
>      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                     Dload  Upload   Total   Spent    Left  Speed
>    100 9438k  100 9438k    0     0  6862k      0  0:00:01  0:00:01 --:--:-- 6859k
>    $ /usr/bin/unzip /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/file.zip -d
>    /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi
>    Archive:  /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/file.zip
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/Crashlytics.framework/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/Crashlytics.framework/README  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/Crashlytics.framework/submit  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/
>        linking: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Crashlytics  -> Versions/Current/Crashlytics 
>        linking: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Headers  -> Versions/Current/Headers 
>        linking: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Modules  -> Versions/Current/Modules 
>        linking: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Resources  -> Versions/Current/Resources 
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/run  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/submit  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/uploadDSYM  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Crashlytics  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/ANSCompatibility.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/Answers.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/CLSAttributes.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/CLSLogging.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/CLSReport.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/CLSStackFrame.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Headers/Crashlytics.h  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Modules/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Modules/module.modulemap  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Resources/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/A/Resources/Info.plist  
>        linking: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/Current  -> A 
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/README.md  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Crashlytics  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/ANSCompatibility.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/Answers.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/CLSAttributes.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/CLSLogging.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/CLSReport.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/CLSStackFrame.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Headers/Crashlytics.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Info.plist  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Modules/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/Modules/module.modulemap  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/run  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/submit  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/iOS/Crashlytics.framework/uploadDSYM  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/submit  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Crashlytics  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/ANSCompatibility.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/Answers.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/CLSAttributes.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/CLSLogging.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/CLSReport.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/CLSStackFrame.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Headers/Crashlytics.h  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Info.plist  
>       creating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Modules/
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/Modules/module.modulemap  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/run  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/submit  
>      inflating: /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/tvOS/Crashlytics.framework/uploadDSYM  
>    finishing deferred symbolic links:
>      /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Crashlytics -> Versions/Current/Crashlytics
>      /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Headers -> Versions/Current/Headers
>      /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Modules -> Versions/Current/Modules
>      /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Resources -> Versions/Current/Resources
>      /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1b9bxvi/OSX/Crashlytics.framework/Versions/Current -> A
> Copying Crashlytics from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/Crashlytics/3.8.2-27acc` to `Pods/Crashlytics`

-> Installing FBSDKCoreKit (4.15.1)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/facebook/facebook-ios-sdk.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1qq25uy --template=
>      --single-branch --depth 1 --branch sdk-version-4.15.1
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-1qq25uy'...
>      Note: checking out '4b4bd9504d70d99d6c6b1ca670f486ac8f494f17'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying FBSDKCoreKit from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/FBSDKCoreKit/4.15.1-fc7fa` to `Pods/FBSDKCoreKit`

-> Installing FBSDKLoginKit (4.15.1)

> Git download
> Git download
>      $ /usr/bin/git clone https://github.com/facebook/facebook-ios-sdk.git /var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-dm01ud --template=
>      --single-branch --depth 1 --branch sdk-version-4.15.1
>      Cloning into '/var/folders/ls/b5m7tk697xl4r4l6mngjvj300000gn/T/d20160921-55543-dm01ud'...
>      Note: checking out '4b4bd9504d70d99d6c6b1ca670f486ac8f494f17'.

```
 You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
 state without impacting any branches by performing another checkout.

 If you want to create a new branch to retain commits you create, you may
 do so (now or later) by using -b with the checkout command again. Example:

   git checkout -b <new-branch-name>
```

> Copying FBSDKLoginKit from `/Users/user_name/Library/Caches/CocoaPods/Pods/Release/FBSDKLoginKit/4.15.1-073f7` to `Pods/FBSDKLoginKit`

-> Installing FBSDKShareKit (4.15.1)

**Comment by promisenxu** [comment]
Waiting for help on this...

**Comment by shanyimin** [comment]
Make sure your podfile contains the following information
```
s.name = "DDEBusiness"
s.version = "0.0.1"
s.platform = :ios, "7.0"
s.authors = "dingdone"
s.license = "dingdone"
s.homepage = "http://www.dingdone.com"
s.summary = "dingdone"
s.source = { :git => "http://git.hoge.cn/dingdone_ios_spec/DDEBusiness.git", :tag => "0.0.1" }
```

**Comment by orta** [comment]
This should be fixed by CocoaPods 1.1.0 I think, can you try?

**Comment by benasher44** [comment]
@promisenxu @ggo16 are either of you still experiencing this issue with CocoaPods 1.1.1?

**Comment by orta** [comment]
Closing due to inactivity
