### ISSUE TITLE
Pods-environment.h is missing defines

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2876]
🌈

As can been seen in the session log, the `RKLogCoreDataError` symbol is undefined, which is because it’s only compiled in [if CoreData is used](https://github.com/RestKit/RestKit/blob/3e6bfeb05dd3e4e0994930f3f654991fb54a3aa7/Code/Support/RKLog.m#L206). Seeing as the `RKLog.*` files do not explicitly include anything related to CoreData, it is most likely dependent on the PCH file, that is shown in the session log as well, specifically this part:

```
#import "Pods-environment.h"
#ifdef COCOAPODS_POD_AVAILABLE_RestKit_CoreData
    #import <CoreData/CoreData.h>
#endif
```

As can be see, this _only_ imports the CoreData headers if the `COCOAPODS_POD_AVAILABLE_RestKit_CoreData` macro is set, which should have been defined in the environment file, which, as can be seen in the session log as well, is completely empty.

There are [tests](https://github.com/CocoaPods/CocoaPods/blob/a080f40e3b732494abc9cdcedccccceff2242065/spec/unit/generator/target_environment_header_spec.rb#L10-L29) for how this _should_ be working, but we are probably missing integration tests that verify this through the full stack, because it’s obviously not working atm.
### This appears to be broken since 0.34.x

```
~/t/C/TestRestKit » pod _0.34.4_ install --no-integrate --no-repo-update
[SNIP]
~/t/C/TestRestKit » cat Pods/Target\ Support\ Files/Pods/Pods-environment.h | grep RestKit_CoreData
~/t/C/TestRestKit »
```

```
~/t/C/TestRestKit » pod _0.33.1_ install --no-integrate --no-repo-update
[SNIP]
~/t/C/TestRestKit » cat Pods/Pods-environment.h | grep RestKit_CoreData
#define COCOAPODS_POD_AVAILABLE_RestKit_CoreData
#define COCOAPODS_VERSION_MAJOR_RestKit_CoreData 0
#define COCOAPODS_VERSION_MINOR_RestKit_CoreData 24
#define COCOAPODS_VERSION_PATCH_RestKit_CoreData 0
~/t/C/TestRestKit »
```
### Session log

```
~/t/C/TestRestKit » pod --version
0.35.0

~/t/C/TestRestKit » cat Podfile
platform :ios, '8'
pod 'RestKit'

~/t/C/TestRestKit » pod install --no-integrate --no-repo-update
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (1.3.4)
Installing ISO8601DateFormatterValueTransformer (0.6.0)
Installing RKValueTransformers (1.1.1)
Installing RestKit (0.24.0)
Installing SOCKit (1.1)
Installing TransitionKit (2.1.0)
Generating Pods project

~/t/C/TestRestKit » cd Pods

~/t/C/T/Pods » xcodebuild
=== BUILD TARGET Pods-AFNetworking OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===
[SNIP]
** BUILD SUCCEEDED **

~/t/C/T/Pods » nm build/Release-iphoneos/libPods-RestKit.a | grep RKLogCoreDataError
         U _RKLogCoreDataError
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: no name list
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: no name list
         U _RKLogCoreDataError
                 U _RKLogCoreDataError
                 U _RKLogCoreDataError

~/t/C/T/Pods » cat Target\ Support\ Files/Pods-RestKit/Pods-RestKit-prefix.pch 
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#endif

#import "Pods-environment.h"
#ifdef COCOAPODS_POD_AVAILABLE_RestKit_CoreData
    #import <CoreData/CoreData.h>
#endif
#import <Availability.h>

#define _AFNETWORKING_PIN_SSL_CERTIFICATES_

#if __IPHONE_OS_VERSION_MIN_REQUIRED
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <MobileCoreServices/MobileCoreServices.h>
  #import <Security/Security.h>
#else
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <CoreServices/CoreServices.h>
  #import <Security/Security.h>
#endif

~/t/C/T/Pods » cat Target\ Support\ Files/Pods/Pods-environment.h 

// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.
```

**Comment by matthewsinclair** [comment]
@segiddins I just bumped a project to `RestKit 0.24.0` (with `RubyMotion 3.2`) and I'm still getting link errors:

```
Undefined symbols for architecture i386:
  "_RKLogCoreDataError", referenced from:
      ___33-[RKEntityByAttributeCache load:]_block_invoke in libPods-RestKit.a(RKEntityByAttributeCache.o)
      ___43-[RKManagedObjectImporter finishImporting:]_block_invoke in libPods-RestKit.a(RKManagedObjectImporter.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
...
```

Seems to be the same kind of thing as before. Has this problem moved forward at all? This is a very small sample project with just one Pod in it (RestKit).

Any help much appreciated.

**Comment by segiddins** [comment]
@matthewsinclair that's because I fixed it in https://github.com/CocoaPods/CocoaPods/pull/2886, which shipped in 0.36.

**Comment by matthewsinclair** [comment]
Aha. Well, that's great news! So, for what it's worth, I can confirm that I'm not getting this problem anymore in `0.36.0.beta.1`.

**Comment by matthewsinclair** [comment]
Hmm ... nope. Not so much. It compiled and built, but I'm getting `uninitialized constant Class::RKObjectManager` errors at runtime. So, back to `0.20.3` of `RestKit` for me. :(

**Comment by segiddins** [comment]
@matthewsinclair that sounds like a rubymotion specific issue

**Comment by matthewsinclair** [comment]
Ok, I'll dig a bit further and see if I can track it down. Thanks. 

Regards,
M@

**Comment by rafaelks** [comment]
This seems to be happening with `0.38.0` again. This is what happens when I try to build my project with pods installed via `0.38.0` (0.37.2 works fine):

```
Undefined symbols for architecture x86_64:
  "_RKLogCoreDataError", referenced from:
      ___33-[RKEntityByAttributeCache load:]_block_invoke in libRestKit.a(RKEntityByAttributeCache.o)
      ___43-[RKManagedObjectImporter finishImporting:]_block_invoke in libRestKit.a(RKManagedObjectImporter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by neonichu** [comment]
Actually, CP 0.38 removes the environment header entirely, see <https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#breaking>

**Comment by rafaelks** [comment]
@neonichu Awesome!!! Thanks! :-)

**Comment by JanIsLearning** [comment]
@rafaelks I experienced the same problems using 0.38. Can you tell me how you solved them?

**Comment by rafaelks** [comment]
@JanIsLearning Since we're not using `RestKit/CoreData`, I just changed my `Podfile` to this:

```ruby
pod 'RestKit/Network', '~> 0.24.1'
```

If you're using `RestKit/CoreData` I suppose that if you use the last version and specify `RestKit/CoreData` it will work fine.

**Comment by JanIsLearning** [comment]
@rafaelks Perfect! Thank you very much!!

**Comment by pbrobst23** [comment]
I've run into the _RKLogCoreDataError as well. Reverting to 0.37.2 produced a different set of errors that I'm looking into.

Two interesting tidbits that I'm not sure are relevant, I'm creating a static library (served as a private pod) that includes RestKit and others via Cocoapods. My project builds fine in XCode (both under 0.38 and 0.37.2) but fails during pod lint.

Any guidance on how best to proceed is appreciated. Currently I am focused on making my 0.37.2 build functional.

**Comment by adamelliot** [comment]
I was having the same issue, and I switched from:  `pod 'RestKit', '~> 0.23.3'` to `pod 'RestKit', '~> 0.25.0'` which fixed my issue.

**Comment by arslaman** [comment]
Thank you @adamelliot!
You made my day!

**Comment by klimaye** [comment]
Thank you @adamelliot. That works!

**Comment by leichunfeng** [comment]
Thank you @adamelliot

**Comment by davidhernando** [comment]
I've also updated restkit version to 0.25.0 and it worked.
