### ISSUE TITLE
pod gem fails to initialize with any arguments

### ISSUE THREAD

**Issue by uson1x** [CocoaPods/CocoaPods#2129]
Hi

After updating to 0.32.1 I have the following problem: if I try to run
`$ pod`
with any arguments, it fails with the next message:

```
/Users/uson1x/.rvm/gems/ruby-2.1.1/bundler/gems/CocoaPods-2a48cdbbe659/lib/cocoapods/command.rb:26:in `<class:Command>': undefined method `version=' for Pod::Command:Class (NoMethodError)
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bundler/gems/CocoaPods-2a48cdbbe659/lib/cocoapods/command.rb:9:in `<module:Pod>'
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bundler/gems/CocoaPods-2a48cdbbe659/lib/cocoapods/command.rb:4:in `<top (required)>'
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bundler/gems/CocoaPods-2a48cdbbe659/bin/pod:33:in `<top (required)>'
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/uson1x/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

After some investigation, I found out that CocoaPods targets the 0.5.0 CLAide version, and there is no `version` attribute in the Command class in 0.5.0 release (https://github.com/CocoaPods/CLAide/blob/44938d0f602fb48e17d5f3b45ecf4764f4fd129d/lib/claide/command.rb).

Does anyone else have this problem too? Would you suggest anything as a hotfix?
