### ISSUE TITLE
Missing framework error when including a pod in one target and a subspec from that pod in another target

### ISSUE THREAD

**Issue by irace** [CocoaPods/CocoaPods#3838]
* Pod A has a dependency on Pod B
* Application target depends on A
* Extension target depends on A/Subspec
* Project fails to build due to an inability to link against B

Example:

```ruby
target :app do
    link_with 'FrameworkTest'

    pod 'TMTumblrSDK'
end

target :extension do
    link_with 'Share'

    pod 'TMTumblrSDK/APIClient'
end
```

As per Boris: “TMTumblrSDK gets duplicated because of the different subspecs, but JXHTTP is only there once and the framework search path of TMTumblrSDK isn’t set up correctly in that situation”

Sample project demonstrating this: http://cl.ly/0w2Q0l3F3y2a

**Comment by samdmarshall** [comment]
I took a look at this, and found some weird things with `Pods-app-TMTumblrSDK-Private.xcconfig` and `Pods-extension-TMTumblrSDK-Private.xcconfig`. 

There is some weird syntax that is being used for the first two variables in both these xcconfig files. Apple defines the syntax for variable substitution as:
> To reference a build setting value in a build setting specification, use the name of the build setting surrounded by parentheses and prefixed by the dollar-sign character ($). 

The variables in these two files lack parenthesis or braces around the variable name. I had trouble getting the Xcode project from forgetting that this value was set even after removing that value from the xcconfig file. This suggests to me that this is unintended behavior. 

The second thing I noticed was over-ridding the `BUILD_CONFIGURATION_DIR`. I see that the app and extension both produce frameworks with the same name, and it seems the `BUILD_CONFIGURATION_DIR` gets modified to give each a directory to build in. I haven't fully explored why that is but if possible i'd recommend not overriding that variable and name them differently instead. Doing this would resolve your issue with it not finding the correct location to search for; otherwise to work around the search locations issue you will have to assign:
`FRAMEWORK_SEARCH_PATHS = $(inherited) $(PODS_FRAMEWORK_BUILD_PATH)/.. $(PODS_FRAMEWORK_BUILD_PATH)`

Lastly, the FrameworkTest.app is referencing a Pods.framework to weaklink against. As far as I can tell this doesn't exist anywhere in this example so I removed that and everything builds fine now.

**Comment by PorterHoskins** [comment]
:+1: I am having this issue too.

**Comment by neonichu** [comment]
@PorterHoskins could you also share your Podfile?

**Comment by PorterHoskins** [comment]
Here is the pod spec for my private repo:
```
Pod::Spec.new do |s|
  s.name             = "RemoteApi"
  s.version          = "0.4.14"
  s.summary          = "RemoteApi"
  s.homepage         = "https://github.com/RemoteApi/api-ios.git"
  s.license          = 'MIT'
  s.author           = { "Chester" => "party@myhouse.com" }
  s.source           = { :git => "git@github.com:RemoteApi/api-ios.git", :tag => s.version.to_s }
  
  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.10'
  
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*'
  s.public_header_files = 'Pod/Classes/**/*.h'
  s.dependency 'XML'
  s.dependency 'AFNetworking'
  s.dependency 'JSONModel'
  
  no_arc_files = 'Pod/Classes/no-arc/*'
  s.exclude_files = no_arc_files
  
  s.subspec 'no-arc' do |ss|
    ss.requires_arc = false
    ss.source_files = no_arc_files
  end
end
```

Here is the Podfile:
```
source 'git@github.com:PrivateRepo/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def shared_pods 
  pod 'RemoteApi'

  pod 'SSKeychain'
  pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift', :branch => 'develop'
end

target 'MyApp' do 
  shared_pods
  
  pod 'GoogleAnalytics'
  pod 'GoogleSignIn'
end

target 'MyAppKit' do 
  shared_pods
end
```

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/issues/4146.

**Comment by benasher44** [comment]
I'm running into what I think is a similar scenario:

- Pod A has a dependency on Pod B and C
- Application target depends on A, B, and C
- Extension target depends on B/Subspec
- Project fails to build due to an inability to compile A

Some notes from the failing build:

- This build is failing because the framework search path when compiling Pod A is only looking at $BUILT_PRODUCTS_DIR/Pods-A, but C.framework only exists in $BUILT_PRODUCTS_DIR.
- B.framework exists in both $BUILT_PRODUCTS_DIR and $BUILT_PRODUCTS_DIR/Pods-A.

I'm using 1.0.0.beta.2, but I get similar compilation errors with a project build with 0.39.0. Would this PR fix this scenario? If this branch gets rebased, I'm happy to test out this branch locally and report back.

**Comment by keefmoon** [comment]
I'm having the same issue. Here is the relevant ```podspec``` from my private repo

```
Pod::Spec.new do |s|

  s.name         = "OperationArchitecture"
  s.version      = "0.1.3"
  s.summary      = "OperationArchitecture is a NSOperation based architecture base on the Advanced NSOperation WWDC talk"
  s.description  = <<-DESC
  This is set of NSOperations and other helpers to make creating responsive and complex apps easier.
  Inspired by the WWDC 2015 talk Advanced NSOperations
                   DESC

  s.homepage     = "https://github.com/keefmoon/operation-architecture"
  s.license      = "MIT"
  s.author             = { "Keith Moon" => "keef@keefmoon.com" }
  s.social_media_url   = "http://twitter.com/keefmoon"
  s.platform     = :ios, "8.0"
  s.source       = { :git => "git@github.com:keefmoon/operation-architecture.git", :tag => 'current' }
  s.module_name = "OperationArchitecture"

  s.source_files  = "OperationArchitecture/OperationArchitecture/**/*.{h,m,swift}"
  s.pod_target_xcconfig = { 'OTHER_SWIFT_FLAGS' => '-DCOCOAPODS' }

  # --- SubSpec -----------
  s.subspec "Core" do |sub|
    sub.source_files = "OperationArchitecture/OperationArchitecture/**/*.{h,m,swift}"
  end

### Some subspecs removed for brevity ###

  s.subspec "CoreLocation" do |sub|
    sub.source_files = "OperationArchitecture_CoreLocation/OperationArchitecture_CoreLocation/**/*.{h,m,swift}"
    sub.dependency "OperationArchitecture/Core"
    sub.frameworks = "CoreLocation"
  end

  s.subspec "Parse" do |sub|
    sub.source_files = "OperationArchitecture_Parse/OperationArchitecture_Parse/**/*.{h,m,swift}"
    sub.dependency "OperationArchitecture/Core"
    sub.dependency "Parse"
  end

end
```

And the ```podfile``` that uses it:
```
workspace 'GeoApps'

xcodeproj 'GeoApp/GeoApp.xcodeproj'
xcodeproj 'GeoData/GeoData.xcodeproj'
xcodeproj 'GeoEditor/GeoEditor.xcodeproj'

platform :ios, '9.0'
use_frameworks!

# Pods

target 'GeoData' do
  xcodeproj 'GeoData/GeoData.xcodeproj'
  pod 'OperationArchitecture/Parse', :git => 'git@github.com:keefmoon/operation-architecture.git'
end

target 'GeoEditor' do
  xcodeproj 'GeoEditor/GeoEditor.xcodeproj'
  pod 'OperationArchitecture/CoreLocation', :git => 'git@github.com:keefmoon/operation-architecture.git'
  pod 'RichEditorView'
end
```
I get ```No such module 'Parse'``` as it's trying to build the target ```Pods-GeoEditor-OperationArchitecture```
