### ISSUE TITLE
Simulator error with 1.5.3 or link error with 1.6.0 and above

### ISSUE THREAD

**Issue by KhiProjects** [CocoaPods/CocoaPods#8838]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
My basic setup is : Xcode 10.1 with CocoaPods 1.5.3. We create subpart of our app as private pod and each pods use some third parties pods as frameworks!. So far so good for One year.

## What did you do?
After installing Xcode 10.2.1, I get the 'pod spec lint error' -> fails because it can't find a simulator like #8163. So I update to CocoaPods 1.6.0 and above (1.7.0.rc..) but this time  I get a Linkage error  Undefined symbols for architecture i386:
      "_OBJC_CLASS_$_IMAAdEvent", referenced from: ... 

the Brightcove pods seems to de the guilty one.
  - Brightcove-Player-IMA (6.3.11):
    - Brightcove-Player-Core/dynamic (= 6.3.11)
    - GoogleAds-IMA-iOS-SDK (= 3.7.0.1)

## What did you expect to happen?
Validate my pods and push it on my private CocoaPodsSpecs

## What happened instead?
- Simulator error with 1.5.3
- Linkage error with 1.6.0 and above.

### Stack

```
   CocoaPods : 1.7.0.rc.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : brightcove - https://github.com/brightcove/BrightcoveSpecs.git @ 53a700dfdc02ec982829cb3b4015cf9783b8a904
               cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               cocoapodspecs - *** private pods specs on gitlab *** 
               master - https://github.com/CocoaPods/Specs.git @ 8163445984a6c052688391c4972ce8c89b1ae3d3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source *** private pod specs on gitlab ***
source 'https://github.com/brightcove/BrightcoveSpecs.git'

target 'HubForecasts_Example' do
  pod 'HubForecasts', :path => '../'

  target 'HubForecasts_Tests' do
    inherit! :search_paths

    
  end
end

## Project that demonstrates the issue
I will do a project on gitlab asap

### PodSpecs
Pod::Spec.new do |s|
  s.name             = 'ProjectName'
  s.version          = '0.4.5.0'
  s.summary          = 'A short description of ProjectName.'

  s.description      = todo

  s.author           = { 'KhiProjects' => ' }
  s.source           = { :git => 'http://gitlab.private/ProjectName/ProjectName.git', :tag => s.version.to_s }


  s.swift_version = '4.0'
  s.ios.deployment_target = '9.0'

  s.source_files = ['ProjectName/API/**/*',
                                        'ProjectName/Classes/**/*',
                                        'ProjectName/Models/**/*']

  s.resources = ['ProjectName/Storyboard/**/*.{storyboard}',
                             'ProjectName/Resources/**/*',
                                 'ProjectName/Assets/**/*']

  s.frameworks = 'Foundation', 'UIKit'
  s.dependency **private**
  s.dependency 'Brightcove-Player-IMA', '~> 6.3'

**Comment by KhiProjects** [comment]
I created a project showing the linkage error. 
Using Xcode 10.1 and cocoaPods 1.7.0.rc.2

https://github.com/KhiProjects/linkageError

**Comment by dnkoutso** [comment]
Can't find `Brightcove-Player-IMA` to debug this.

**Comment by KhiProjects** [comment]
Hello,

Thank you for checking this issue.

You might need to add:
pod repo add brightcove https://github.com/brightcove/BrightcoveSpecs

**Comment by dnkoutso** [comment]
Probably a bug because `Brightcove-Player-IMA` is not being built (has no sources)

**Comment by KhiProjects** [comment]
I just clone it on my personal iMac. Xcode 10.1 and CocoaPods 1.5.3 build and success to "lint".
After updating to 1.6.2, it failed:

>  Undefined symbols for architecture i386:
      "_OBJC_CLASS_$_IMAAdsManager", referenced from:
          objc-class-ref in LinkageErrorAPI.o
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    ** BUILD FAILED **

> 

Plus, I only have 2 local repo (pod repo list) brightcove and CocoaPods/Specs.

I hope my repo helped you to find a solution, cause i am very stuck on it.
Thank you for your help and this great project.

**Comment by KhiProjects** [comment]
Hello,
I just tried with the 1.8.0.beta.1 and the problem is still present.
I hope you can find the time for working on this problem, I do understand you have a lot to do.

We can't move forward in version (Xcode and cocoa pods) because of this and it's very problematic.

Regards,
KH
