### ISSUE TITLE
Cannot build MapBox with 36.beta.2

### ISSUE THREAD

**Issue by maciekish** [CocoaPods/CocoaPods#3114]
Hi,
If you add https://github.com/mapbox/mapbox-ios-sdk/ via CocoaPods in 36.beta.2 it fails to build because i guess some llvm settings for GRMustache change because of CocoaPods. The error is at line 650 in GRMustacheContext.m.

The error is the same as described here http://stackoverflow.com/questions/24922913/too-many-arguments-to-function-call-expected-0-have-3

And the reason i think this is CocoaPods fault is that everything works if i run pod install using CocoaPods 0.35 but breaks in 0.36.beta.2, and GRMustacheContext.m looks exactly the same after both `pod install`s

**Comment by segiddins** [comment]
Please give some more information about the error you are seeing. Are your pods being  installed as frameworks in 0.36?

**Comment by maciekish** [comment]
I'm getting exactly the same error as in the post i linked to `Too many arguments to function call, expected 0, have 3`.

How do i check how they are being installed? The only things i did was upgrade CocoaPods to `0.36.beta.2` and `pod install`.

**Comment by orta** [comment]
I think somewhere in there we use a new LLVM version, or new default settings from Xcode, that require changes like https://github.com/orta/ORSimulatorKeyboardAccessor/commit/5f43093553dd224d14b3d92ec1a14f8e52784655

**Comment by maciekish** [comment]
Yeah, i tried something like that and it worked. Won't you be able to add some kind of fallback for old repositories? For example MapBox has hardcoded a specific version of GRMustache that they want to use, and i believe upgrading CocoaPods shouldnt break the build like this.

**Comment by segiddins** [comment]
You can use the post install hook to change the build setting. 

-Samuel E. Giddins

On Feb 5, 2015, at 9:12 AM, Maciej Swic <notifications@github.com> wrote:

Yeah, i tried something like that and it worked. Won't you be able to add some kind of fallback for old repositories? For example MapBox has hardcoded a specific version of GRMustache that they want to use, and i believe upgrading CocoaPods shouldnt break the build like this.

**Comment by maciekish** [comment]
Any idea what build setting that would be please? Xcode just dumped this error on me without warning.

**Comment by orta** [comment]
`ENABLE_STRICT_OBJC_MSGSEND` from the looks of it inside Xcode. Given that this is the [new default]( https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L117) for all Xcode projects, we will probably end up keeping this in. 

I'm sure someone can put a `post_install` hook below if they have a working example I imagine it would look [something like this](https://github.com/artsy/eidolon/blob/7a1229b9e84234915275fdf1a87a579ebbcba193/Podfile#L80-L91).

**Comment by neonichu** [comment]
BTW, the reasoning for this is not casting `objc_msgSend` will cause crashes in some situations. See <https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html>

**Comment by groue** [comment]
Could it be related to https://github.com/groue/GRMustache/issues/86? I did not take this issue as one requiring immediate action, but maybe I'm wrong?

**Comment by maciekish** [comment]
Hmm so maybe the "fix" is to issue a PR to MapBox with a newer GRMustache version, if it doesn't break stuff.
