### ISSUE TITLE
Could not find or use auto-linked framework

### ISSUE THREAD

**Issue by khoogheem** [CocoaPods/CocoaPods#12672]
After updating to 1.16.0 on Xcode 16 and 16.1 

I am seeing this issue

```
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode_16.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
Undefined symbols for architecture arm64:
  "Cloudinary.CLDExpression.__allocating_init(expressionKey: Cloudinary.CLDExpression.ExpressionKeys) -> Cloudinary.CLDExpression", referenced from:
      full type metadata for Cloudinary.CLDConditionExpression in CLDConditionExpression.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by xygkevin** [comment]
Me to

**Comment by xygkevin** [comment]
me too

**Comment by arivas87** [comment]
Same here with [libsignal](https://github.com/signalapp/libsignal)
```
ld: warning: Could not find or use auto-linked library 'signal_ffi': library 'signal_ffi' not found
Undefined symbols for architecture arm64:
  "LibSignalClient.NativeHandleOwner.__allocating_init(borrowing: Swift.OpaquePointer?) -> LibSignalClient.NativeHandleOwner", referenced from:
      full type metadata for LibSignalClient.Aes256Ctr32 in Aes256Ctr.o
      full type metadata for LibSignalClient.Aes256GcmEncryption in Aes256Gcm.o
      full type metadata for LibSignalClient.Aes256GcmDecryption in Aes256Gcm.o
      full type metadata for LibSignalClient.Aes256GcmSiv in Aes256GcmSiv.o
      full type metadata for LibSignalClient.Cds2Client in Cds2.o
      full type metadata for LibSignalClient.ChatListenerBridge.(AckHandleOwner in _7880CDAD24B1514BE930FD806DBED1E8) in ChatListener.o
      full type metadata for LibSignalClient.AuthenticatedChatService in ChatService.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by allisonadam81** [comment]
Same - xcode 15.2 and 15.3.

**Comment by pastre** [comment]
Same - Xcode 15.4

**Comment by LukasCZ** [comment]
Same here - Xcode 16.1

**Comment by khoogheem** [comment]
1.16.2 seems to have fixed this issue for me

**Comment by arivas87** [comment]
Yes, it seems the latest release fixes the issue.

**Comment by Kayuii** [comment]
Same here - Version 16.1 (16B40)

**Comment by MReP1** [comment]
Same here - Version 16.1

**Comment by PirunSeng** [comment]
@khoogheem how do you solve this? what is 1.16.0 to 1.16.2?

**Comment by rsainiWin** [comment]
Yes what is 1.16.0 to 1.16.2

**Comment by rsainiWin** [comment]
@PirunSeng they're talking about pods version
I'm using 1.16.2 only but still same

**Comment by PirunSeng** [comment]
@rsainiWin I see, thanks, yeah I have 1.16.2 too while still having similar issue. I think my main issues is something related to @main annotation or AppRegistry, still finding solution...
`ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
Undefined symbols for architecture arm64:
  "_main", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by larrasket** [comment]
Same here. Also why are boneheads thumbing-down comments with "same here"?

**Comment by larrasket** [comment]
@khoogheem Why did you close this? Did you find a solution?

**Comment by aguilarpgc** [comment]
I changed the value for build settings property LIBRARY_SEARCH_PATHS from `$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)` to `$(SDKROOT)/usr/lib/swift`
