### ISSUE TITLE
"pod: command not found" after installing on OS X El Capitan Beta 2

### ISSUE THREAD

**Issue by danielbyon** [CocoaPods/CocoaPods#3736]
Trying to setup an OS X Server Mac Mini with El Capitan Beta 2 so I can try out the new Xcode server stuff. I'm able to run "sudo gem install cocoapods", and it seems to install everything properly without errors, but when I run "pod setup" I get the command not found error. Happens even after closing the current Terminal window and opening a new one.

Is there an issue specific to the 10.11 beta? I've been able to install cocoapods on my other macs (albeit I installed cocoapods way before I installed the 10.11 beta on those machines)

**Comment by segiddins** [comment]
What's the output of `gem list` ?

**Comment by leoMehlig** [comment]
I have the same problem. 
cocoa pods gets install just fine and its also in the gem list, but I can't call any commands.

**Comment by neonichu** [comment]
See <https://github.com/CocoaPods/CocoaPods/issues/3692#issuecomment-113847612>, binstubs are installed in a directory that is not part of the standard `PATH` when using OS X 10.11

**Comment by MarsCWD** [comment]
i have got the same problem...oh no ...

**Comment by yanko** [comment]
I tried the #3690 but it still not finding the pod command line. tells me it does not exist.

**Comment by remirobert** [comment]
Same issue here. :-1:

**Comment by wieseljonas** [comment]
Same for me

**Comment by neonichu** [comment]
Piling on doesn't really help anyone — you have to tell us what you tried and why that didn't work for you.

**Comment by mgmart** [comment]
Got the same problem. 

`gem install cocoapods` solved it for me.

**Comment by richardgroves** [comment]
Same here - trying to re-install cocoapods fails:

richard$ pod install
-bash: pod: command not found
richard$ sudo gem install cocoapods
Password:
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/pod

I suspect it is related to:

http://arstechnica.co.uk/apple/2015/09/os-x-10-11-el-capitan-the-ars-technica-review/8/#h1

which would block an install to /usr/bin - should be to /usr/local/bin

Trying it without 'sudo' in case it then finds local places to install fails too:

richard$ gem install cocoapods
Fetching: cocoapods-0.38.2.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

**Comment by neonichu** [comment]
@richardgroves interesting, I guess there's a problem with existing installations in the El Capitan Ruby there. Could you try uninstalling and then reinstalling CocoaPods?

**Comment by MarsCWD** [comment]
I have solved this problem. http://www.jianshu.com/p/c2624f916957?utm_campaign=hugo&utm_medium=reader_share&utm_content=note

**Comment by richardgroves** [comment]
@neonichu - Installing El Capitan **wipes out** the old version of cocoapods - the Ars Technica article has a link to where it 'migrates' all the files it finds in places it didn't like.

Hmmm....looks like the old versions are there - just the front end 'pod' launcher that got wiped:

richard$ pod --version
0.38.2
richard$ sudo gem uninstall cocoapods

Select gem to uninstall:
 1. cocoapods-0.32.1
 2. cocoapods-0.33.1
 3. cocoapods-0.34.1
 4. cocoapods-0.35.0
 5. cocoapods-0.35.0.rc2
 6. cocoapods-0.36.3
 7. cocoapods-0.37.1
 8. cocoapods-0.37.2
 9. cocoapods-0.38.0
 10. cocoapods-0.38.2
 11. All versions
> 10
Successfully uninstalled cocoapods-0.38.2
richard$ which pod
/usr/local/bin/pod
richard$ pod --version
0.38.0

So after uninstalling the 0.38.2 I still have the previous one working.

and then a straight install to get back to the latest fails:

richard$ sudo gem install cocoapods
Fetching: cocoapods-0.38.2.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/pod
richard$ which pod
/usr/local/bin/pod

leaving me at 0.38.0 until I use the '-n /usr/local/bin' positioning argument.

@MarsCWD - that will work (disabling the whole SIP system) but is a bit heavy handed.

**Comment by neonichu** [comment]
@richardgroves I can't reproduce this, if I uninstall all existing CP installations on OS X 10.11 and then reinstall, `/usr/local/bin` is used automatically.

**Comment by remirobert** [comment]
when i want reinstall cocoapods i got his : 

```
sudo gem install cocoapods
```

```
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/latest_specs.4.8.gz)
```

**Comment by richardgroves** [comment]
@neonichu Interesting - I wonder if there is a config setting in Ruby gems that indicates where to put things? The machine I'm on has also done updates from several previous OS X versions so might have inherited an install location from an old version?

**Comment by neonichu** [comment]
@richardgroves yah, I am assuming that is the case. I have updated the instructions in [this comment](https://github.com/CocoaPods/CocoaPods/issues/3692#issuecomment-113847612) to reflect the `-n` workaround if that happens. Thanks for reporting!

**Comment by MVakas** [comment]
Try the following command on OS X El Capitan
sudo gem install -n /usr/local/bin cocoapods

**Comment by TTVS** [comment]
thanks for your suggestion @MVakas. It solved the issue for me

**Comment by benjaminhorner** [comment]
@MVakas : thanks !! worked like a charm !
Guess we can close the issue.

**Comment by darioalessandro** [comment]
I just installed el capitan and ran into the same issue than you guys.

I did as @MVakas said, but I had to change permissions of /usr/local/bin/ 

with sudo chmod +rx /usr/local/bin/

**Comment by sicaboy** [comment]
same issue, not solved

**Comment by richardgroves** [comment]
The config problem appears to be in /Library/Ruby/Site/2.0.0/rubygems/defaults.rb - around line 118:

##
  # The default directory for binaries

  def self.default_bindir
    if defined? RUBY_FRAMEWORK_VERSION then # mac framework support
      '/usr/bin'
    else # generic install
      RbConfig::CONFIG['bindir']
    end
  end

it is setting up what is basically a not-allowed in OS X 10.11 directory to install binaries too. I'm on Ruby 2.0.0, so don't know if this is changed in the newer 2.2.3 build. The folder was the same back in 1.8 - http://stackoverflow.com/a/333639/701926

**Comment by neonichu** [comment]
Interesting, that configuration file doesn't even exist on my 10.11 installation. Maybe it's an upgrade leftover in certain situations?

**Comment by richardgroves** [comment]
Just updated to 2.2.3 using brew & rbenv - so that has moved everything into a local folder in my user account which should solve future problems. Here's hoping the bad bindir setup is some legacy issue that will fade out rapidly.

**Comment by neonichu** [comment]
I have filed a radar on this: http://www.openradar.me/22979372 — but pretty sure nothing will come out of it because it is way too vague.

**Comment by neonichu** [comment]
Got a reply for the radar:

> We need more information to investigate this issue.
>
> What is your RubyGems version? If you've installed a newer version then it won't install into /usr/local/bin unless you use
> -n /usr/local/bin
> The rubygems shipped with El Capitan will report
> $ gem env
> ...
> - EXECUTABLE DIRECTORY: /usr/local/bin
> ...
>
> Please provide your response or results by updating your bug report.

Could y'all check your `gem env` and verify if you updated RubyGems?

**Comment by Bizzi-Body** [comment]
Gems version...
RUBY VERSION: 2.0.0 (2015-04-13 patchlevel 645) [universal.x86_64-darwin15]

After running .... `sudo gem install -n /usr/local/bin cocoapods`  pod is available once more.

**Comment by Bizzi-Body** [comment]
Interesting... 

I ran `sudo gem install -n /usr/local/bin cocoa pods` and all looked good.  So I moved on to update the pods in my project.  

I ran `pod update` on the target project and got this output.

`Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Downloading dependencies`

**Comment by neonichu** [comment]
@Bizzi-Body that's just warnings, they're going to be silenced in a future release (see CocoaPods/Xcodeproj#312)

**Comment by Bizzi-Body** [comment]
@neonichu - thanks for clarifying.

**Comment by SirSJR** [comment]
@richardgroves Thanks for the help! 

This solution worked for me, updated to El Capitan from Yosemite yesterday.

**Comment by CoderMJLee** [comment]
```objc
sudo gem install -n /usr/local/bin cocoapods
```

**Comment by SongJiaqiang** [comment]
@CoderMJLee You are right! Thank Teacher Li.

**Comment by benjaminhorner** [comment]
same here

**Comment by the-scott-davis** [comment]
Like many of you, I had the same problem. Unfortunately for me nothing work until I stumbled on one of the comments above posted by @darioalessandro - 

As he suggested, I had to change permissions of /usr/local/bin/

The process I did, in case it's helpful to anyone, is below:

1) uninstall all instances of cocopods (just to be safe and keep things clean) sudo gem uninstall cocoapods
2) sudo gem install -n /usr/local/bin cocoapods
3) sudo chmod +rx /usr/local/bin/

After that, my pod commands all worked from the console as it used to before migration to El Capitan

**Comment by jdk89757** [comment]
@CoderMJLee You are right!

**Comment by footyapps27** [comment]
Tried the various commands posted in this thread but nothing works for me..
Posted the log below:-

    ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

    make "DESTDIR=" clean

    make "DESTDIR="
    compiling generator.c
    In file included from generator.c:1:
    In file included from ./../fbuffer/fbuffer.h:5:
    In file included from                       /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.1 0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
    #include "ruby/config.h"
             ^
    1 error generated.
    make: *** [generator.o] Error 1

    make failed, exit code 2

    Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/json-1.8.3 for inspection.
    Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/json- 1.8.3/gem_make.out

**Comment by neonichu** [comment]
@footyapps27 that looks like as if you are using the wrong version of Xcode, you can't install gems with Xcode 6 on OS X 10.11

**Comment by tonyli508** [comment]
Just use xcode-select -s (Xcode 7 version path) then
sudo gem install -n /usr/local/bin cocoapods

**Comment by ThomasCle** [comment]
I tried all the above. The only thing that worked was the solution @the-scott-davis suggested. Thanks!

**Comment by canaksoy** [comment]
@sicaboy  sudo chmod -R 755 /usr/local/bin   solved my problem

**Comment by catchZeng** [comment]
I had the same problem and solved it.
My process is below:
1.sudo chmod -R 755 /usr/local/bin
2.sudo gem uninstall cocoapods
3.sudo gem install -n /usr/local/bin cocoapods
4.sudo ./xcode-select -switch /Applications/Xcode.app/

**Comment by iMuFeng** [comment]
@CoderMJLee I fix it with this.

**Comment by aitbaali** [comment]
I had the same issue after upgrading to 10.11.1
I've fixed it with: 
```
$ sudo gem uninstall cocoapods
Remove executables:
	pod, sandbox-pod

in addition to the gem? [Yn]  Y
```

then
```
$  gem install cocoapods
```

**Comment by Nathan187** [comment]
@CatchZeng thanks...you helped me

**Comment by kbpontius** [comment]
+1 @the-scott-davis

**Comment by zhixia** [comment]
+1 @the-scott-davis Thanks a lot,it's worked.

**Comment by skyhacker2** [comment]
+1 @the-scott-davis

**Comment by skydivedan** [comment]
I was wondering if anyone has come across this running Xcode Server?

I tried the-scott-davis suggestions, and others, all to no avail. 

I'm still getting the "pod: command not found." The weird thing is, Xcode Server runs as user _xcsbuildd. If I "su" to that user and do a "pod --version", no problem, it finds the command. But if I run a bot, with a script that has "pod install" in it, it's like the command doesn't exist. Any help would be greatly appreciated.

**Comment by anas10** [comment]
+1 I have the same problem as @skydivedan. I tried all the things I could but nothing worked yet.

**Comment by elviin** [comment]
@the-scott-davis Thank you.

**Comment by anas10** [comment]
@skydivedan I made it work easily at the end. Just do as @the-scott-davis said above and add one more step : 
 Add the following in your bot trigger script `export PATH=$PATH:/usr/local/bin` so that the bot can look there as well and find the binary. 

Hope that helps.

**Comment by Cuuuurzel** [comment]
You can also just run :
gem uninstall cocoapods
(All versions + Executables)
gem install cocoapods

Worked for me

**Comment by OliverNielsen** [comment]
Removing all versions and sandbox of CocoaPods and installing it again solved the problem for me.

Uninstall: `sudo gem uninstall cocoapods`
Install: `sudo gem install cocoapods`

**Comment by eluck** [comment]
We can also make it work for local gem installation (a sudo-less one):

1. Follow instructions from the official cocoapods installation guide: https://guides.cocoapods.org/using/getting-started.html#sudo-less-installation
2. Run the following script:

    ```
    echo "export PATH=\$PATH$(gem env gempath)/bin" | sed 's/:/\/bin:/g' | sed 's/$PATH/$PATH:/g' >> ~/.bash_profile
    ```

3. **Restart terminal** and run `pod --help` to check whether it works.

**Comment by damirkotoric** [comment]
@MVakas Legend!

**Comment by WillemKuei** [comment]
+1 @the-scott-davis Thanks!

**Comment by tyxinger** [comment]
I ran sudo "chmod +rx /usr/local/bin/" and It can work as before

**Comment by rajeshm20** [comment]
Thanks..everyone @MVakas...

**Comment by rsahu34** [comment]
Thanks... @MVakas

**Comment by skydivedan** [comment]
wait a minute.... Cocoapods 1.0 just rolled out. Shouldn't this have been addressed in the big 1.0 update? Or will "sudo gem install" always need a path argument?

**Comment by PluginIO** [comment]
This happens because of a new security level in El Capitan, you can disable SIP or have the install use the -n flag along with the /usr/local/bin path however the route cause is the updated security model.

**Comment by SwamyChunchu** [comment]
i have tried all bellow Commands ....still iam getting this error
ERROR:  While executing gem ... (NoMethodError)
    undefined method `ord' for nil:NilClass

==>
sudo gem install -n /usr/local/bin cocoa pods

sudo gem install cocoapods
sudo gem install -n /usr/local/bin cocoapods
pod setup
pod setup --verbose

sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

sudo gem install activesupport -v 4.2.6 sudo gem install cocoa pods

sudo gem install -n /usr/local/bin cocoapods﻿

[sudo] gem install activesupport -v 4.2.6 [sudo] sudo gem install cocoapods

sudo gem install cocoapods -V
sudo gem update --system

**Comment by RMKitty** [comment]
@the-scott-davis  help me， thanks
![30802c42-3b72-44e6-ad98-43020d81a6d6](https://cloud.githubusercontent.com/assets/11688968/19415116/18de79e4-9398-11e6-9004-48bbd1fefe9d.png)

**Comment by SwamyChunchu** [comment]
Try this Commands

sudo gem install activesupport -v 4.2.6 ,
sudo gem install cocoa pods ,




sudo gem install cocoapods -V , sudo gem update --system

**Comment by vistatinchao** [comment]
when i run pod setup
i found some error that
 [!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

how to solve 
waiting..........

**Comment by enggmspl** [comment]
> I had the same problem and solved it.
> My process is below:
> 1.sudo chmod -R 755 /usr/local/bin
> 2.sudo gem uninstall cocoapods
> 3.sudo gem install -n /usr/local/bin cocoapods
> 4.sudo ./xcode-select -switch /Applications/Xcode.app/

Thanks CatchZeng, it's working for me. thanks a lot.

**Comment by hamidbin** [comment]
> sudo gem install -n /usr/local/bin cocoapods

Thanks, if you have installed cocoapads successfully, but :pod command not found, this is your solution. Don't listen to the cacophony around.

**Comment by IamSAL** [comment]
Guys, I tried every solution and was getting crazy when nothing was working.

`
sudo gem uninstall cocoapods

sudo gem install -n /usr/local/bin cocoapods`

It was still not working.

then I RESTARTED the mac, and it was all okay.
