### ISSUE TITLE
cocoapods 1.0 failed to pod spec lint, the error says can not find sqlite3.h.

### ISSUE THREAD

**Issue by casatwy** [CocoaPods/CocoaPods#5361]
# Report

## What did you do?

git clone git@github.com:casatwy/CTPersistance.git
pod spec lint ./CTPersistance.podspec --verbose

## What did you expected to happen?

success with lint

## What happened instead?

failed, but it works on 0.39

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ba85b321f21f68474b99e01aad1c3357cd42261f
               PodsWarehouse - ssh://git@gitlab.playplus.me:10022/iOS/PodsWarehouse.git @ f8c7a371afbb50f1950319be2c3b333f9a3902e9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by neonichu** [comment]
The error I'm seeing is:

```
CTPersistanceDataBase.h:10:9: error: include of non-modular header inside framework module 'CTPersistance.CTPersistanceDataBase' [-Werror,-Wnon-modular-include-in-framework-module]
#import <sqlite3.h>
        ^
1 error generated.
```

which is expected, because the iOS SDK does not ship with a module for SQLite. You probably linted with `--use-libraries` before. 

In any case, check out <https://github.com/stephencelis/SQLite.swift/blob/master/SQLite.swift.podspec> for how you could include SQLite in a Pod that can work as a framework.

**Comment by casatwy** [comment]
Yes, problem solved, thank you!
