### ISSUE TITLE
Podspec invalid after update to 1.0.0

### ISSUE THREAD

**Issue by vittoriom** [CocoaPods/CocoaPods#5339]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run `pod spec lint` of an already-deployed pod after upgrading to 1.0.0

## What did you expected to happen?

The podspec should have linted successfully

## What happened instead?

The following error popped up:

```
 -> Carlos.podspec
    - ERROR | spec: The specification defined in `Carlos.podspec` could not be loaded.


[!] Invalid `Carlos.podspec` file: undefined method `platform=' for #<Pod::Specification::DSL::PlatformProxy:0x007ff38a017db0>.

 #  from Carlos.podspec:20
 #  -------------------------------------------
 #
 >    s.ios.platform = :ios, "9.0"
 #    s.osx.platform = :osx, "10.10"
 #  -------------------------------------------


Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.2.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9aed74cbaff6c7f61ab47159ee14a40323812fe3
```

### Installation Source

```
Executable Path: /Users/MacBookPro/.gem/ruby/2.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate     : 1.0.0
cocoapods-plugins         : 1.0.0
cocoapods-rome            : 0.3.0
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.0.0
cocoapods-try             : 1.0.0
cocoapods-try-release-fix : 0.1.2
```

## Project that demonstrates the issue

The podspec is available [here](https://github.com/WeltN24/Carlos/blob/master/Carlos.podspec)

**Comment by segiddins** [comment]
change it to 
```ruby
s.ios.deployment_target = '9.0'
s.osx.deployment_target = '10.10'
```
