### ISSUE TITLE
dyld[19610]: Symbol not found: _$s10Foundation10URLRequestV10httpMethodSSSgvs

### ISSUE THREAD

**Issue by asoneji** [CocoaPods/CocoaPods#11284]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
In our application, we have over 189 pods based on the `Podfile.lock` with the release of Xcode13.3 we are getting linker error: `dyld[19610]: Symbol not found.`

The same exact project used to work in the previous Xcode release 13.2.1.

When working with Apple DTS we came to learn that the issue is related to the sheer volume of LC_RPATH results. Overrunning the 32 KB buffer size that dyld allocates to hold all of these references and their file paths. We believe the overrunning buffer size is to the sheer volume of dependencies in our project.

Any suggestion or workaround to resolve this issue?

## What did you do?
* Project with lots of dependencies ~189 pods based on the `Podfile.lock`
* `pod install`

## What did you expect to happen?
* Build and run our application successfully

## What happened instead?
* `dyld: Symbol not found.` crash happens
* We belive this is due to overrunning the 32 KB buffer size that dyld allocates to hold all of these references and their file paths

### Stack
```
   CocoaPods : 1.11.2
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
    RubyGems : 3.1.2
        Host : macOS 12.3 (21E230)
       Xcode : 13.3 (13E113)
         Git : git version 2.34.0
Ruby lib dir : /Users/asoneji/.rvm/rubies/ruby-2.7.1/lib
```

### Plugins

```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

WIP: Our current project has private cocoapods. We will try to create a project using public cocoapods only to demonstrate the issue and link it here.

**Comment by paulb777** [comment]
Based on https://developer.apple.com/forums/thread/702487, this does not seem to be a CocoaPods issue
