### ISSUE TITLE
Xcode 7 Archive Build rsync resources path not found

### ISSUE THREAD

**Issue by aaronvegh** [CocoaPods/CocoaPods#3738]
I've been trying to create an archive build of my project in Xcode 7 linking against the iOS 9 SDK. The build fails with this error:

```
sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
building file list ... done
rsync: push_dir#3 "/Users/aaron/Library/Developer/Xcode/DerivedData/VideoGrabber-gpyzpfvbijsnuyglzzvynckkuwee/Build/Intermediates/ArchiveIntermediates/VideoGrabber-iOS/InstallationBuildProductsLocation/Library/Frameworks" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at /SourceCache/rsync/rsync-45/rsync/main.c(580) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
Command /bin/sh failed with exit code 12
```

There's another similar issue #3721 but it's related specifically to Swift: all my pods are ObjC. In my case, the `InstallationBuildProductsLocation` directory does not exist. 

Please let me know what information I can provide to help troubleshoot!

**Comment by neonichu** [comment]
Could you please retry this with the 0.38 beta?

**Comment by aaronvegh** [comment]
Yes, the 0.38 beta seems to have dealt with this issue. Thank you!

**Comment by danielnordh** [comment]
Unfortunately the 0.38 beta didn't fix this issue for me. 
Fails on building a Share Extension target for the iOS app in Xcode 7 beta 2, works in Xcode 6.3.
Still getting the same error;

rsync: push_dir#3 "/Users/Daniel/Library/Developer/Xcode/DerivedData/Curator-fppjaspuvfpqzidgmfkjwqzvrsdy/Build/Intermediates/ArchiveIntermediates/Curator (Live)/InstallationBuildProductsLocation" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-45/rsync/main.c(580) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
Command /bin/sh failed with exit code 12

**Comment by neonichu** [comment]
@danielnordh are you saying that your project builds with Xcode 6.3, but breaks with 7 beta 2? If yes, this is probably a new issue, just with a similar result.

**Comment by danielnordh** [comment]
That's correct. Can't archive project from Xcode 7 while it works fine in 6.3. I'll gather some more info before possibly creating a new issue.

**Comment by TravisCrist** [comment]
I seem to have a similar issue using Xcode 7 Beta 3 when linking with iOS 9.0

"sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
building file list ... done
rsync: push_dir#3 "/Users/USER_DIR/Library/Developer/Xcode/DerivedData/APPNAME-brndwvawqziufcbioqjtodevvppi/Build/Intermediates/ArchiveIntermediates/APPNAME/InstallationBuildProductsLocation" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at /SourceCache/rsync/rsync-45/rsync/main.c(580) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]
Command /bin/sh failed with exit code 12"

Using pod 0.38.0.beta.2 with my post install instructions I now get an error: 
"pod _0.38.0.beta.2_  update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.5.4)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `project' for #<Pod::Installer:0x007fc7838fb090>

/APP_NAME/Podfile:24:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.0.beta.2/lib/cocoapods-core/podfile.rb:170:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.0.beta.2/lib/cocoapods-core/podfile.rb:170:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:756:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:744:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:743:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:154:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:149:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:109:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'"

My pod file has a post install section that looks like this: 
"post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        if target.name == "Pods-Today Extension Target-AFNetworking"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AF_APP_EXTENSIONS=1']
            end
        end
    end
end
"

This works just fine with version 0.37.2 but with that version I cannot make an archive.
