### ISSUE TITLE
[0.37.0] Install leveldb-library success, but some header files are not included

### ISSUE THREAD

**Issue by lzyy** [CocoaPods/CocoaPods#3491]
![screen shot 2015-05-04 at 14 27 36](https://cloud.githubusercontent.com/assets/35974/7449472/c1543ee6-f269-11e4-9afa-a91d204dc95f.png)

it seems `port.h` / `port_posix.h` are not downloaded which is contained in [Spec](https://github.com/CocoaPods/Specs/blob/master/Specs/leveldb-library/1.18.1/leveldb-library.podspec.json) file. after downgrade to 0.36, it works well.

**Comment by segiddins** [comment]
Neither of those header files are listed as header files in the podspec?

**Comment by lzyy** [comment]
yes,`port.h` / `port_posix.h` are downloaded, but not in `header files`, but why it works in 0.36.x ?

**Comment by kylef** [comment]
This has been fixed in 0.37.

### CocoaPods 0.37.0

```shell
$ pod spec lint leveldb-library.podspec.json --use-libraries --allow-warnings

 -> leveldb-library (1.18.1)
    - ERROR | Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR |  leveldb-library/util/coding.h:59:7: error: use of undeclared identifier 'port'
    - ERROR |  leveldb-library/util/coding.h:73:7: error: use of undeclared identifier 'port'
    ...

Analyzed 1 podspec.

[!] The spec did not pass validation.
```

### CocoaPods 0.37.1

```shell
$ pod spec lint leveldb-library.podspec.json --use-libraries --allow-warnings

 -> leveldb-library (1.18.1)
    ...

Analyzed 1 podspec.

leveldb-library.podspec.json passed validation.
```
